### ISSUE TITLE
SAM Hashes?

### ISSUE THREAD

**Issue by DaPhexion** [AlessandroZ/LaZagne#1]

**Comment by AlessandroZ** [comment]
Hi, 

At the beginning I wanted to retrieve windows credentials/hashes as well. However some awesome tools do it much better that I could have done (creddump, mimikatz, etc.). If the project grows up, maybe some windows feature will be added (SAM hashes recovery, etc.). 

Alessandro

**Comment by DaPhexion** [comment]
Ok. Won't close it yet though.

**Comment by DaPhexion** [comment]
Perhaps this might be of interest?

**Comment by AlessandroZ** [comment]
Thanks for the link, I will check it when I will have more time.

**Comment by DaPhexion** [comment]
No problem.

I am no expert in python, but I think we can call a  ```subprocess``` 3 times for ```reg.exe``` and save the files in the temp directory, then we can dump the hashes and print them out.

**Comment by AlessandroZ** [comment]
Ok, I have done it. I added Windows hashes and LSA secrets functionalities.
