### ISSUE TITLE
password from IE11 not showing up in Windows Server 2016

### ISSUE THREAD

**Issue by hubgitbb** [AlessandroZ/LaZagne#108]
Hi

im trying to get passwords out of memory from IE11 but i get only the blank password field. the user and website are showing up but no password.

i did this with version 2.0 and IE11 on windows server 2016.

**Comment by AlessandroZ** [comment]
Hi, 

I have never tested to retrieve passwords from the credential manager on a windows server 2016. So I don't know if it works. I do not have access to a win2016, if you have access to it and you find a way to retrieve these passwords (using another tool or your knowledge), I will be happy to know it.

**Comment by AlessandroZ** [comment]
Could you try the last [release](https://github.com/AlessandroZ/LaZagne/releases/tag/2.2) on the windows server 2016 please. 
I have changed the way to retrieve these passwords but I cannot test it on a Windows 2016, if you could do it for me, it will be nice. Thank you !
