### ISSUE TITLE
Error when running system_hash.py

### ISSUE THREAD

**Issue by cclements** [AlessandroZ/LaZagne#109]
On Windows 10 x64 build 15031.  Everything else seems to work normally.

```
########## User: SYSTEM ##########

Traceback (most recent call last):
  File "laZagne.py", line 116, in launch_module
  File "lazagne\softwares\windows\system_hash.py", line 591, in run
ValueError: need more than 1 value to unpack
```

**Comment by AlessandroZ** [comment]
I have fixed this issue, however, I have not build the executable yet. 
The problem occurred when spiting the hash returned using ":" as separator. I'm quite surprised the ":" was not present on the hash. 

So it should could be due to another error.
