### ISSUE TITLE
Program blocked by NOD32

### ISSUE THREAD

**Issue by chris96it** [AlessandroZ/LaZagne#112]
Caro Alessandro,

Ho notato che il software viene rilevato dagli antivirus, nel mio caso da ESET NOD 32.

Si potrebbe fare in modo che questo problema venga risolto?

Saluti,

-Chris96

**Comment by jboss38** [comment]
Disable ESET NOD 32 to run the soft

**Comment by chris96it** [comment]
Dear jboss38,

Thanks for your answer, i already know about it, i was wondering if there was another fix for this issue.
I hope to receive an answer from the owner itself.

Kind Regards,

-Chris96

**Comment by jboss38** [comment]
You can build the payload yourself editing some fonction to change the signature of the program or compress / pack the payload to change the header and compress strings to also change signature, you will bypass more antivirus but some will still detect the "behavior" of the payload
