### ISSUE TITLE
Keeps getting removed my AntiVirus Tool

### ISSUE THREAD

**Issue by konqui** [AlessandroZ/LaZagne#114]
Why ist this tool recognized as a Virus?
Is there a  possibility to make it stay eg. not recognized as a Virus so one can test his own pc for stored passwords - without whitelisting it?

Kaspersky says Trojan.Win32.Agent.nezdxp

Is this Tool using Code fragments that are also used by a Trojan?

**Comment by Eyremba** [comment]
> Why ist this tool recognized as a Virus?

Because it acts like a virus? *Facepalm*

> Is there a possibility to make it stay eg. not recognized as a Virus so one can test his own pc for stored passwords - without whitelisting it?

Most likely... No.

> Is this Tool using Code fragments that are also used by a Trojan?

Look at my first reply aboth.
