### ISSUE TITLE
cant run compiled executable

### ISSUE THREAD

**Issue by ASEyeV2** [AlessandroZ/LaZagne#115]
Hey there!

im having some issues with my lazagne program after i have build it from source. the issue i am having is that the compiled exe does absolutely nothing. and yes. i did follow all the steps. and yes. it compiles without any errors.

Does anyone has this issue too? 

http://image.prntscr.com/image/3e1674e8c4b04190a08df0c6040bfb02.png

**Comment by AlessandroZ** [comment]
Quite strange. 
Does it run correctly before to compile it using python ? ("python  lazagne.py all"). 

Try to follow all my recommendation to compile it: https://github.com/AlessandroZ/LaZagne/wiki/How-to-compile
And use the custom spec.

**Comment by ASEyeV2** [comment]
Yes it sure does. and i think i will stick to that .py file instead of the exe as i find that way now better heh.
And yes, i have tried that also but it gave me the same empty results :| it compiles fine but the program just wont do anything...

Buts thats fine now, as i said i now use the .py file directly instead of the exe.

Thanks you for your wonderful program

Regards,

**Comment by AlessandroZ** [comment]
Thanks for your feedback :)
