### ISSUE TITLE
Source code is not working! yet binary release working fine ?

### ISSUE THREAD

**Issue by roothaxor** [AlessandroZ/LaZagne#116]
Users\user\Desktop\laZagne\Windows\lazagne\config\manageModules.py", line 45, in <module>
    from lazagne.softwares.memory.memorydump import MemoryDump
  File "C:\Users\user\Desktop\laZagne\Windows\lazagne\softwares\memory\memorydump.py", line 12, in <module>
    from memorpy import *
ImportError: No module named memorpy

**Comment by AlessandroZ** [comment]
Read the temporary note: https://github.com/AlessandroZ/LaZagne/wiki/How-to-compile
