### ISSUE TITLE
LaZagne - Windows version 2.1 - Unexpected crash on Win10 after gathering

### ISSUE THREAD

**Issue by chris96it** [AlessandroZ/LaZagne#118]
Dear Alessandro,

Hope you're well, 

After testing the new release on windows 10 64bit, i noticed that after successfully running the software
in the command prompt with the query: "laZagne.exe all", it turned out with the results and an unexpected crash.
This been said, i am unable to save my passwords into a txt file using the query: laZagne.exe all > file.txt.

Here is a screenshot of my issue, kindly apologize for the editing, i had to remove the passwords.

![error](https://cloud.githubusercontent.com/assets/26190787/25701202/a3efd6ce-30cb-11e7-8d08-dd10ba0cb2c7.png)

Looking forward to receive your response,

Ciao!

-Chris96it

**Comment by AlessandroZ** [comment]
Hi, thank you for your feadback and sorry for my late answer. 

I will need you to test it again because I cannot reproduce this issue. It works on my win10 (x64). 
I have done some commit since my last release and I think the crash has already been corrected (I hope so). 

Could you please install Python and all [requirements](https://github.com/AlessandroZ/LaZagne/wiki/Requirements) needed to try again using the last version (not the release but using the python code from my github). 

If it's not possible I will send you a binary from a file sharing website tp try again. I don't want to build a new release without be sure it will correct your crash.

Thank you for your help. 

Alessandro

**Comment by chris96it** [comment]
Dear Alessandro,

Thanks a lot for your response, i was able to compile your Python Script (with all the requirements) and retry re-executing it on my Win10 x64.

Unfortunately it keep crashing after it has successfully gathered the results.

I tried with all the modules and it seems that the crash is only due to a specific module > *all*.
Infact the crash occurs only while writing and executing the following command:

laZagne.py all

Please find in this attachment the picture with the last crash.

![untitled](https://cloud.githubusercontent.com/assets/26190787/25928004/fe0569d4-35f9-11e7-8b53-87bb78a9acac.png)

Looking forward to receive your response,

Best regards,

-Chris96it

**Comment by AlessandroZ** [comment]
I don't think that it's related to the write action. A write error would print a stacktrace but would not crash the process like that. I think, this is more related to the impersonation mechanism. I suppose if you run lazagne without administrator privilege, there is no crash. 
I will try to check it soon and I will be back to you.

**Comment by chris96it** [comment]
Hi Alessandro, i tried to test your script also without the administration privilege, same error occurred.
Let's keep in touch!
-Chris96it

**Comment by AlessandroZ** [comment]
Hmm, this is really weird if you have the same error without admin rights. 

I need to know where the error occurs to be able to correct it. Could you please run lazagne with the debug output and give me the last module launched, an error message printed on the console or something to give me a clue to understand.
`python laZagne.py all -vv`

Some module should failed but which one, I don't know. So if you run any module individually, you do not have the crash ? You don't have error from the "windows" module ? 
`python laZagne.py windows`

If the program terminates and you see the last line on the console "elapsed time = xxx", tell me. 

Using old release, you didn't have this error or it was already present ? 

Thanks.

**Comment by chris96it** [comment]
Ciao Alessandro!

Yeah, it only happens with this current release and with only a specific module "all".

I am giving you the errors output below:

------------------- Cyberduck passwords -----------------

Cyberduck not installed.

[!] No passwords found

------------------- Puttycm passwords -----------------

[DEBUG] global name 'sx64' is not defined

Puttycm not installed

[!] No passwords found

------------------- Opensshforwindows passwords -----------------

[!] No passwords found

------------------- Filezilla passwords -----------------

Filezilla not installed.

[!] No passwords found

------------------- Apachedirectorystudio passwords -----------------

[!] No passwords found

------------------- Ftpnavigator passwords -----------------

FTP Navigator not installed or not found.

[!] No passwords found

------------------- Coreftp passwords -----------------

[DEBUG] global name 'sx64' is not defined

CoreFTP not installed

[!] No passwords found

------------------- Unattended passwords -----------------

[!] No passwords found

------------------- Winscp passwords -----------------

[DEBUG] global name 'sx64' is not defined

WinSCP not installed.

[!] No passwords found

------------------- Chrome passwords -----------------

[!] No passwords found

------------------- Internet explorer passwords -----------------

Internet Explorer passwords are stored in Vault (check vault module)

[!] No passwords found

------------------- Opera passwords -----------------

Opera is not installed.

[!] No passwords found

------------------- Firefox passwords -----------------

Profile path found: C:\Users\PC\AppData\Roaming\Mozilla\Firefox\Profiles/ee0mzvam.default-1431979649620

[DEBUG] key: 'CHIAVE NASCOSTA'

Profile path found: C:\Users\PC\AppData\Roaming\Mozilla\Firefox\Profiles/ee0mzvam.default-1431979649620

[DEBUG] key: 'CHIAVE NASCOSTA'

[!] No passwords found

------------------- Composer passwords -----------------

[!] No passwords found

------------------- Tortoise passwords -----------------

Tortoise not installed.

[!] No passwords found

------------------- Mavenrepositories passwords -----------------

[!] No passwords found

------------------- Gitforwindows passwords -----------------

[!] No passwords found

------------------- Dbvis passwords -----------------

Dbvisualizer not installed.

[!] No passwords found

------------------- Robomongo passwords -----------------

[!] No passwords found

------------------- Sqldeveloper passwords -----------------

SQL Developer not installed.

[!] No passwords found

------------------- Squirrel passwords -----------------

Squirrel not installed

[!] No passwords found

------------------- Credential manager passwords -----------------

Waiting for your response,

-Chris96it

**Comment by AlessandroZ** [comment]
I have added some debug output on my last commit. Could you please run it again using the last version from my github. 

Launch it using this command line and give me the output (hide your passwords if some are printed): 
`python laZagne.py windows --cred -vvv`

Thanks.

**Comment by chris96it** [comment]
Dear Alessandro,

Thanks a lot for your reply, i am sharing you the new crash image and it's output below:

![untitled](https://cloud.githubusercontent.com/assets/26190787/26013183/915ec1e0-3757-11e7-960a-ad5dbedd2a65.png)

Text Output:

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|


########## User: PC ##########

------------------- Credential manager passwords -----------------

[DEBUG] Run Credential manager function

[DEBUG] CredEnumerate executed successfully

[DEBUG] cound variable: c_ulong(13L)

[DEBUG] Number of value: 13

[DEBUG] cred[i] variable: <lazagne.config.WinStructure.LP_CREDENTIAL object at 0x00000000038B7248>

[DEBUG] c variable: <lazagne.config.WinStructure.CREDENTIAL object at 0x00000000038B7348>

[DEBUG] cred[i] variable: <lazagne.config.WinStructure.LP_CREDENTIAL object at 0x00000000038B7448>

[DEBUG] c variable: <lazagne.config.WinStructure.CREDENTIAL object at 0x00000000038B7548>

[DEBUG] cred[i] variable: <lazagne.config.WinStructure.LP_CREDENTIAL object at 0x00000000038B7348>

[DEBUG] c variable: <lazagne.config.WinStructure.CREDENTIAL object at 0x00000000038B7248>

[DEBUG] value to decrypt found

[DEBUG] target: WindowsLive:(token):name=ACCOUNT NASCOSTO;serviceuri=ssl.live.com

[DEBUG] username: ACCOUNT NASCOSTO

Thanks a lot again and let me know!

Buona serata,

-Chris96it

**Comment by AlessandroZ** [comment]
Could you try again. I have done some changes on the line which produces the error.
Thanks for your help, I appreciate.

**Comment by chris96it** [comment]
Dear Alessandro,

Now it works perfectly, no errors occurred, also tested with the other module, it works perfectly!

As from my side, the issue has been resolved, waiting to see the new Windows release!

Thanks a lot ;-)

-Chris96it

**Comment by AlessandroZ** [comment]
Great, we did it :+1: 

Thank you for your help, I appreciate a lot. I will build a new release soon. Thanks again.

**Comment by chris96it** [comment]
I appreciate! Thank you very much, especially for your patience! :lulz: 👍
