### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by thelittlefireman** [AlessandroZ/LaZagne#12]
In windows 10 it doesn't work, it can't find the windows password and decrypt it

**Comment by AlessandroZ** [comment]
Hi,
"No credentials" does not mean that it does not work.

The difference between win7 and win8 or win10 is that LaZagne does not retrieve the credential manager on Win8 or higher (internet explorer, etc, use the credential manager to store their credentials).
However, Firefox, opera and the other softwares do not change their way to store the password.

Launch it with the -v option for more information.
If you have some explicit error messages, send it to me. Thank you.

ps: LaZagne does not retrieve the windows password in cleartext but his hash.
