### ISSUE TITLE
Virus signature in keethief.py

### ISSUE THREAD

**Issue by CaledoniaProject** [AlessandroZ/LaZagne#120]
Can you encode the powershell script embedded in keethief.py?

The KeeThief.launch_keeThief method contains virus signatures

**Comment by AlessandroZ** [comment]
For bypassing AV, I let you modify the code, I cannot do it myself because it will be soon detected as malware again. You could check closed issues to find a solution or get a look to the pupy project that I talk on the readme, in order to use lazagne without writing files on the disk.

**Comment by CaledoniaProject** [comment]
Right, make sense
