### ISSUE TITLE
Requesting new Windows release

### ISSUE THREAD

**Issue by chris96it** [AlessandroZ/LaZagne#122]
Dear Alessandro,

Thanks a lot for your recent fixes! since the issue has been resolved and i can't run the previous release due to it's previous issues, i was wondering, when will you release the new Windows version? 

Could you please let us know as soon as you can?

Looking forward to hearing from you!

Thanks again.

Best Regards,

-Chris96it

**Comment by AlessandroZ** [comment]
Here it is: https://github.com/AlessandroZ/LaZagne/releases/tag/2.2
