### ISSUE TITLE
Detected by Antivirus

### ISSUE THREAD

**Issue by ConTRoniiX** [AlessandroZ/LaZagne#124]
As I said in the title, it gets detected by AV. I did a  VirusTotal.com test and this was the result: 17/61

Is there a way to bypass the Antivirus?

ConTRoniiX

**Comment by KiUserExceptionDispatcher** [comment]
Are you a cyber-criminal?

**Comment by byt3bl33d3r** [comment]
yeah i think he's this guy 
![r9km_9xbyazk-gplzvyqgxijecbrsjlowzpukga6wug](https://cloud.githubusercontent.com/assets/5151193/26268983/4303b07a-3caf-11e7-9e01-4ad670d21c75.jpg)

**Comment by 0E800** [comment]
I think if you add a couple comments to the source and recompile you will maybe not get detected to easily.

I've also noticed NOD32 blocking it. Not sure if it's just by hash or from a/v heuretics. I've been using this tool for sometime and just recently (as of a few months ago) noticed my endpoint AV flag it.

Maybe try using an older version? Do you get same results?

**Comment by ConTRoniiX** [comment]
> Are you a cyber-criminal?
Yea im the guy who coded WannaCry and I need this for my next virus lol

> yeah i think he´s this guy
Yep, that´s me. There is no way you commented here xD

> Maybe try using an older version?
I‘ll try that, thanks for your suggestion.

**Comment by jboss38** [comment]
See https://github.com/AlessandroZ/LaZagne/issues/112

**Comment by AlessandroZ** [comment]
@byt3bl33d3r, Ahaha you found him :)

@ConTRoniiX, Do not be suprised that antivirus detects Lazagne as a malware, you just helping them putting the tool on Virus Total.

**Comment by usama7628674** [comment]
@ConTRoniiX @jboss38 @0E800 Bypass all antivirus.See results here https://antiscan.me/scan/new/result?id=eqTaPhIGSR93.This site does not deliver to av's just like nodistribute but I still recommend to use virtual machine.
