### ISSUE TITLE
Skype hash

### ISSUE THREAD

**Issue by hikjik** [AlessandroZ/LaZagne#127]
Hi!

1. I've found a small typo in lazagne.config.WinStructure.py in method OpenKey.
I think there should be 
    if isx64:
instead of
    if sx64:
Could you check it please

2. Your program returns me the following hash of the password from Skype:
    21e6fe41060f6c4413a18542add5ebcc
It's just a md5 of the string '\nskyper\n' with a empty username and password. I'm doing something wrong?

**Comment by AlessandroZ** [comment]
I have correct the missing char on the "isx64", thanks for your remark. 

I have changed the way to retrieve the username (if it fails, another method is used). If the problem still persist, open the issue again. 

Thanks !
