### ISSUE TITLE
Add support for SecureCRT

### ISSUE THREAD

**Issue by CaledoniaProject** [AlessandroZ/LaZagne#128]
Can you kindly add support for SecureCRT? Which is a popular SSH software

https://github.com/gitPoc32/Forensic/blob/master/VanDykeSecureCRT/SecureCRT-decryptpass.py

**Comment by AlessandroZ** [comment]
Hi, this  script is not up to date, it has been built in 2014 and does not work anymore. I have tried it without success and I don't have time to understand its new way to store passwords. 
Sorry.

**Comment by CaledoniaProject** [comment]
No problem :-)
