### ISSUE TITLE
SQLite issue

### ISSUE THREAD

**Issue by evadeo** [AlessandroZ/LaZagne#13]
Hey, that's a nice program that you have here ;)
Unfortunately I can't seem to make it work on my computer
Here are tracebacks after my error occurs, and it seems that sqlite is the prolem.
Thanks !

|====================================================================|
|                                                                                                                                        |
|                        The LaZagne Project                                                                               |
|                                                                                                                                        |
|                          ! BANG BANG !                                                                                       |
|                                                                                                                                        |
|====================================================================|

------------------- Skype passwords -----------------

Password not found !!!
Username: XXX
Hash_md5: XXX
shema to bruteforce: XXX
Traceback (most recent call last):
  File "<string>", line 181, in <module>
  File "<string>", line 109, in runAllModules
  File "<string>", line 74, in launch_module
  File "C:\Users\John\LaZagne-master\Windows\src\LaZagne\build\laZagne\out00-PYZ.pyz\softwares.browsers.chrome", line 41, in run
sqlite3.OperationalError: unable to open database file

**Comment by AlessandroZ** [comment]
Hi, thank you for your feedback. 
Could you try the last version, I patched the error. Thank you.

**Comment by evadeo** [comment]
Hi, thank you for your fix, I don't have any more error messages so I guess you did a good job !! =)
Bye.
