### ISSUE TITLE
vers. 2.1 vs 2.2

### ISSUE THREAD

**Issue by dimforensic** [AlessandroZ/LaZagne#130]
just tried to extract passwords with versions 2.1 and 2.2 to see difference bitween them.
And there is an issue with vers. 2.2, that didnt extract the data from Outlook account. 
But version 2.1 extracted very well such as: IMAP User; IMAP Password, Account Name, Email, etc.

**Comment by Banaanhangwagen** [comment]
v2.2 does not dump SYSTEM pwd (like lsa, hashdump,...)

**Comment by AlessandroZ** [comment]
There is not difference between 2.2 and 2.1 so it should work as well. Check the description of the version 2.2 (https://github.com/AlessandroZ/LaZagne/releases). 

The only problem that I'm aware is sometimes System pwd are not retrieved even with System rights. If it occurs, launch again the tool (2 or 3 times) and it should work. I cannot reproduce the error when I want so it's difficult to correct it. 

I will try to better understand the problem to find a solution.
