### ISSUE TITLE
Closing when I open it.

### ISSUE THREAD

**Issue by AMagicCamel** [AlessandroZ/LaZagne#132]
How exactly do I fix this? I've tried writing a batch file for it, but it either has the same problem, says "error too few arguments", or passwords don't show. If anyone could write a batch file for me or tell me how to fix that'd be great.

**Comment by SecureThisShit** [comment]
Just execute it with one of the following parameters:

positional arguments:
  {chats,mails,all,git,svn,database,windows,wifi,sysadmin,browsers,games,memory,php,maven}

For Example: lazagne.exe all

**Comment by 0E800** [comment]
Sometimes you dont want other peoples passwords flooding the screen.
For this reason I typically use:
`lazagne.exe all > creds.txt`

This will populate creds.txt with the passwords.

**Comment by AlessandroZ** [comment]
Check on youtube, you could find lots of tutorials how to use it with a bat file: 
https://www.youtube.com/watch?v=nVaXQ8CIFWg

**Comment by arjunsahajan** [comment]
I am able to execute lazagne.py in my windows system but it is not quitting automatically.
When I interrupt it is giving me series of errors. Its working fine on linux.
