### ISSUE TITLE
I can't find the .exe [Yes, i have no idea what the fuk im doing]

### ISSUE THREAD

**Issue by MA19112001** [AlessandroZ/LaZagne#139]
Well iam trying to find the .exe but i cant find it. Can someone give my the location of the .exe . Thanks

**Comment by AlessandroZ** [comment]
![images duckduckgo com](https://user-images.githubusercontent.com/10668373/29179031-88506d5a-7df3-11e7-9f67-9f4517fddb45.jpeg)


Here are all releases: https://github.com/AlessandroZ/LaZagne/releases
And here is the last windows version: https://github.com/AlessandroZ/LaZagne/releases/download/2.2/Windows.zip
