### ISSUE TITLE
Quiet Mode

### ISSUE THREAD

**Issue by rivermont** [AlessandroZ/LaZagne#140]
Another `verbosity` mode, silent, would be nice. Perhaps only printing start, stop, errors.

**Comment by AlessandroZ** [comment]
I don't understand the purpose of this mode if you cannot see the passwords.

**Comment by rivermont** [comment]
If you run the program with the password dump option (`-oN`/`-oJ`/`-oA`), it will still dump all output to a file.

I was just thinking if the user doesn't want all the data printed onto the screen; it could be useful in some scenarios.

**Comment by AlessandroZ** [comment]
It should work now: 
`lazagne.exe all -quiet -oA `

I have pushed the code but I will build the executable soon. The functionality will be present on the next release. (https://github.com/AlessandroZ/LaZagne/commit/3616def7f7295df475d8e53f7605ab94ef1f7e55#diff-04c6e90faac2675aa89e2176d2eec7d8R61)
