### ISSUE TITLE
Request for add CocCoc browser module

### ISSUE THREAD

**Issue by ITsenhong** [AlessandroZ/LaZagne#141]
Hello all!
First, I want to introduce little about CocCoc browser
Cốc Cốc browser (previously Cờ Rôm+) is a freeware web browser focused on the Vietnamese market, developed by Vietnamese company Cốc Cốc and based on Chromium open source code,[1] which is the same platform used by Google Chrome,...
See more: https://en.wikipedia.org/wiki/C%E1%BB%91c_C%E1%BB%91c
Note: CocCoc is most used browsesr, it is a default browser for a large amount of computer in VietNam. And now, it has 22+ million Monthly active user
Because it base on chromium, I think it very easy to add it as a module.
I want to say I am a programmer, but  I think you need only add
homedrive + homepath + '\\AppData\\Local\\CocCoc\\Browser\\User Data',
homedrive + homepath + '\\Local Settings\\Application Data\\CocCoc\\Browser\\User Data',
as pathTap in Chrome module
I have a demo but not with laZagne, because i have error when run laZagne's script on My Windows computer. Instead with WebBrowserPassView. But I think it has the same result
DEMO https://www.youtube.com/watch?v=dZKwhm7WZjo
And for expanse. we can do the same for other chrowser base on Chromium.
I will very happy if the next build has CocCoc module
Sorry for my poor english, but I think I have explained clear.
Thanks!

**Comment by AlessandroZ** [comment]
Ok I will try to do it.

**Comment by ITsenhong** [comment]
CocCoc browser homepage: https://coccoc.com/en
I've done it successfully with the same way as above for enum_chrome metasploit post module. But I still can't well configured LaZagne 's script on Windows to test it
I hope you will test it and add CocCoc as a module into your wonderful tool

**Comment by AlessandroZ** [comment]
I have implement it, I will push it soon.

**Comment by AlessandroZ** [comment]
I have added the coccoc module (https://github.com/AlessandroZ/LaZagne/commit/aea492931b945470776cb3afb2dbafbc041ce242). I didn't build the executable yet because I'm still working on another things. It should be present on the next release (2.3).

**Comment by ITsenhong** [comment]
This work is great for me and possible some other people. I will check it when binaries version release! Thank you for module!
