### ISSUE TITLE
Request to Retrieve passwords from another destination

### ISSUE THREAD

**Issue by brunofs-br** [AlessandroZ/LaZagne#142]
Is it possible to retrieve passwords from another destination then the installation drive ?
My intention is to retrieve passwords from a disk image, or at least a different drive destination (where the images could be mounted)

For example:
	lazagne.exe all -d "myImage.e01" -oN
	lazagne.exe all -d "D:/" -oN
Thank you !

**Comment by AlessandroZ** [comment]
Right now, it's not possible to do it. 

It should be possible to do it from a different drive location but lots of password could not been retrieved using this method. Lots of windows passwords should be encrypted and decrypted in the same user environment. So if you mount a different windows drive, you change the user environment. For example, you could not retrieve passwords from ie, chrome, opera, etc. but Firefox, Jitsi, etc yes. 
So I don't know yet if I will implement it.

**Comment by AlessandroZ** [comment]
The next release will allow you to choose another drive (https://github.com/AlessandroZ/LaZagne/commit/3616def7f7295df475d8e53f7605ab94ef1f7e55#diff-04c6e90faac2675aa89e2176d2eec7d8R68). 

However, you should know, that no all passwords will be retrieved as I explained you before. Moreover, the check will be always done on the current user retrieving passwords using the homedrive environment variable and then it will check for other users using the drive passed as parameter. So don't be surprised if passwords from your current user are printed.
