### ISSUE TITLE
laZagne is not working on Mac.

### ISSUE THREAD

**Issue by elgplayer** [AlessandroZ/LaZagne#145]
LaZagne is not working on the latest version of macOS, macOS Sierra 10.12.6. Really don't know what the problem is, maybe the latest version broke the program but a fix would be appreciated.
This is your latest release.

![lazagne problem](https://user-images.githubusercontent.com/6267293/30226278-be07f654-94d5-11e7-9c69-9893f517c94e.jpg)

**Comment by AlessandroZ** [comment]
Lazagne on mac OS is not stable yet. Only Firefox passwords are managed. 
However, your error message means that you should install some python dependency to run the python code (here it's written that you don't have pyasn1 installed).

**Comment by elgplayer** [comment]
If it won't work without installing dependencies, then what's the point? Also do you have an ETA on when it will be available to Mac?

**Comment by AlessandroZ** [comment]
Only the source code is available, but you should be able to create a binary which will embed all dependency. However, your screenshot shows that you use the python code which of course cannot be used as a standalone. 
I have no idea when I will work on a Mac, I don't have one, so it's complicated to work on it.

**Comment by leperjulien** [comment]
Hi @AlessandroZ 

You tools is one awesome project and is amongst the fews that made me want to lear python earlier this year ;)

I currently trying to compile the python script for mac into a binary using pyinstaller and py2app but so far no success..

Should i also copy all the dependencies's folder over to where my laZagne script is and add their paths to the .spec file or is there something else i forgot ?

Thanks :)

**Comment by AlessandroZ** [comment]
Hi, 

I have just released a new Mac os version, it is still in beta. So get the new version before to compile it. 
Try to install all [dependencies](https://github.com/AlessandroZ/LaZagne/wiki/Requirements) to be able to run the script using python. Then you will be able to build your portable binary. 

I have never done it on a Mac, but it should work. You could use [pyinstaller dev](https://github.com/pyinstaller/pyinstaller) or [py2app](https://wiki.python.org/moin/MacPython/py2app). 

Dependencies are embedded automatically on the binary (at least this is how it works on linux and windows).

**Comment by leperjulien** [comment]
Wow thats one fast answer !
It took me almost all night but i figured out how to compile on my Mac , and my binarie is working on multiple Mac OS computer so its perfect thanks !

Here is how i did it if anyone is also having trouble : 
Create a custom folder in the same directory than laZagne.py and name it hooks, inside create a file named hook-Crypto.py and put this inside : 
```
#-----------------------------------------------------------------------------
# Copyright (c) 2005-2016, PyInstaller Development Team.
#
# Distributed under the terms of the GNU General Public License with exception
# for distributing bootloader.
#
# The full license is in the file COPYING.txt, distributed with this software.
#-----------------------------------------------------------------------------

"""
Hook for Crypto module: https://pypi.python.org/pypi/pyCryptox

Tested with Cryptox 3.4.2, Python 2.7 & 3.5, Windows
"""

import os
import glob

from PyInstaller.compat import EXTENSION_SUFFIXES
from PyInstaller.utils.hooks import get_module_file_attribute

# Include the modules as binaries in a subfolder named like the package.
# Crypto's loader expects to find them inside the package directory for
# the main module. We cannot use hiddenimports because that would add the
# modules outside the package.

binaries = []
binary_module_names = [
    'Crypto.Cipher',
    'Crypto.Util',
    'Crypto.Hash',
    'Crypto.Protocol',
]

for module_name in binary_module_names:
    m_dir = os.path.dirname(get_module_file_attribute(module_name))
    for ext in EXTENSION_SUFFIXES:
        module_bin = glob.glob(os.path.join(m_dir, '_*%s' % ext))
        for f in module_bin:
            binaries.append((f, module_name.replace('.', '/')))

```

And issue this command to compile (there might be some useless arguments since it tooks me many tries before getting it to work so if someone want to clean it feel free ;)

`cd Mac`
`pyinstaller --onefile --additional-hooks-dir=hook/ -p /Library/Python/2.7/site-packages/Crypto --hidden-import pyasn1 --hidden-import Crypto -p lazagne/ laZagne.py`

And if everything went fine : 

`cd dist/`
`./laZagne`

```
|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

error: too few arguments

usage: laZagne [-h] [--version] {mails,all,browsers} ...

positional arguments:
  {mails,all,browsers}  Choose a main command
    mails               Run mails module
    all                 Run all modules
    browsers            Run browsers module

optional arguments:
  -h, --help            show this help message and exit
  --version             laZagne version
```

If you need someone to test stuff on MacOs platform feel free to ask @AlessandroZ :)

**Comment by AlessandroZ** [comment]
Waahou I didn't expect it was so complicated to build a binary on mac. I though only doing `pyinstaller --onefile lazagne.py ` will work. Thanks to adding your code, I will avoid spending a night finding a way :)

Read the last comment I added to understand what it's still not working on the Mac version: https://github.com/AlessandroZ/LaZagne/issues/24. 

Thanks for your help, have a nice day.

**Comment by Vladimir351** [comment]
Как установить Lazagne на Mac Os High Sierra версия 10.13
