### ISSUE TITLE
error to compile on windows :(

### ISSUE THREAD

**Issue by gearcapitan** [AlessandroZ/LaZagne#146]
sorry,,, but i have this problem 
![captura de pantalla 37](https://user-images.githubusercontent.com/13740942/30362201-855811ba-9820-11e7-9e89-dfba3f64dc34.png)

**Comment by AlessandroZ** [comment]
Follow all steps describe on the wiki: https://github.com/AlessandroZ/LaZagne/wiki/How-to-compile

See the Windows part and use use a spec file to build it. 
`python pyinstaller.py --onefile lazagne.spec`

**Comment by gearcapitan** [comment]
![captura de pantalla 38](https://user-images.githubusercontent.com/13740942/30389418-5f67b0a2-9878-11e7-9c3a-cfa5c604d2e1.png)
