### ISSUE TITLE
error at the compilation

### ISSUE THREAD

**Issue by PandoraSec** [AlessandroZ/LaZagne#147]
i compile the lazagne,py as the tutorial says but when i execute the exe it show this issue
![sin titulo](https://user-images.githubusercontent.com/22203976/30399781-0cce8be4-9892-11e7-96cf-a1f98eb0b63a.png)
i try some other ways but it always the same problem

**Comment by AlessandroZ** [comment]
I have never had this problem. I cannot help you without more information. Does it run using the python code ? (before creating the exe). Have you follow all steps on the wiki ? (https://github.com/AlessandroZ/LaZagne/wiki/How-to-compile). 

I put all my steps on the wiki, so if it does not work, I cannot help you more (if it's a pyinstaller problem, I have no idea how to resolve the problem).
