### ISSUE TITLE
the program does not get firefox passwords

### ISSUE THREAD

**Issue by gearcapitan** [AlessandroZ/LaZagne#149]
![captura de pantalla 42](https://user-images.githubusercontent.com/13740942/30403576-07d6cae6-98a8-11e7-9925-7e32bbf68d46.png)

**Comment by AlessandroZ** [comment]
I cannot reproduce your error using the exact version as yours. Try to launch lazagne with more verbose output (-vv). 
`lazagne.exe browsers -f -vv`

Do you have firefox files on the following locations: 
`C:\Users\<current_user>\AppData\Roaming\Mozilla\Firefox\Profiles`

It could fail if your installation is not on the default path.

**Comment by gearcapitan** [comment]
![captura de pantalla 44](https://user-images.githubusercontent.com/13740942/30485968-b3284648-99f4-11e7-8753-defedcac5f00.png)

**Comment by AlessandroZ** [comment]
I cannot understand the problem. If you compiled the exe, could you please debug the problem yourself. 

Mozilla path is well found (https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/browsers/mozilla.py#L438) but profiles are not (it never goes here: https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/browsers/mozilla.py#L452).

I suppose "profile_list" should be empty, so "get_firefox_profiles" returns None (https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/browsers/mozilla.py#L278). Could you print before this line https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/browsers/mozilla.py#L448 the value of the variable "path". 

If you can try to understand the problem it should be easy for me. 

Be sure to have passwords in the database as well and always use verbose mode. Thanks
