### ISSUE TITLE
No Wifi password found

### ISSUE THREAD

**Issue by superjimmy7** [AlessandroZ/LaZagne#15]
Bonjour,
J'utilise Windows 7 pro sp1 x64 et lors ce que j'ai utilisé votre utilitaire avec "laZagne.exe wifi" (executer en tant qu'administrateur) il me dis qu'il n'y a pas de mot de passe wifi trouvé. Or j'utilise au moins 3 réseau wifi securisé par jour. M'y suis-je mal pris ou y a t'il une procedure a faire pour que cela fonctionne ? 
De plus "laZagne.exe Windows", "laZagne.exe sysadmin" et "laZagne.exe database" ne trouvent également rien est-ce normal ?

**Comment by AlessandroZ** [comment]
Bonjour, 
Merci pour ton retour. 

- Pour ce qui concerne les mots de passe wifi, le pré-requis nécessaire est qu'il soit lancé en tant qu'administrateur, sinon ça ne peut pas marcher. Après peux-tu voir dans le répertoire suivant, si des fichiers/répertoires existent ou non : 
```C:\ProgramData\Microsoft\WwanSvc\Profiles```
S'il s'agit d'une tablette ou autre machine particulière, merci de me le signaler. 

- Pour ce qui est de sysadmin et database, ça va dépendre des logicielles que tu as installé, je ne peux pas t'en dire plus si tu me donnes pas plus de détails. 

Télécharge la dernière version, des mis à jour on été apporté et lance le avec beaucoup de verbosité: laZagne.exe -vv

Merci.

**Comment by patelkunala** [comment]
When I download the exe file from 'https://github.com/AlessandroZ/LaZagne/tree/master/Windows/standalone' and run (with admin cmd on Windows 7 64-bit) it gives me following error.
"This version of c:\Users\kunal.patel\Desktop\laZagne.exe is not compatible with the version of windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher."

Any idea what am I missing?

**Comment by AlessandroZ** [comment]
This error happens on tablets (ex: surface). It's a 32 bits binary so it has to work on 32 or 64 bits OS. However, tablet does not support 32 bits binary. It could be the reason.

**Comment by patelkunala** [comment]
Not really as I'm working on a workstation. Dell Precision T1500 tower, to be precise.

**Comment by AlessandroZ** [comment]
Quite weird. I do not have a solution right now. I will try to do a 64 bits version in the future. It could be a solution. However, a 32 bits binary has to run on a 32 bits and 64 bits OS, so that is not normal to have this problem.

**Comment by patelkunala** [comment]
That's exactly what I thought, usually 32 bit assemblies run quite merrily on 64 bit OS. But upon inspection I found this dialog.

![image](https://cloud.githubusercontent.com/assets/8613550/7862587/d094b3a2-054e-11e5-91d4-58ade352a7c1.png) and in the title it says "16-bit" application. Just wondering if the .exe is actually a 16-bit executable? Tried getting details using InspectExe, but surprisingly that tab on the properties window didn't show anything!

**Comment by AlessandroZ** [comment]
No it's not a 16 bits executable, I do not know why you have this error.

If you really want to understand, the best way is to try to launch it using the code source but all requirements have to be completed (so you have to install python and all requirements defined at the end of the README). If you do not have any error, it means that the problem is from pyinstaller (the tool used to build the executable, so to debug is more difficult).

**Comment by 0E800** [comment]
Its working for me on Win8.1 x64. I will test on Win7 x64. Note that I did
not run it as admin.

@op _ did you run the exe from elevated command prompt?

**Comment by patelkunala** [comment]
@AlessandroZ - hmmm....I think I'll have to bit the bullet and step in to 'uncharted waters'.
@0E800  - yes I did that same error. I will await your test result on Win7 64bit...

**Comment by 0E800** [comment]
Apologies, didn't realize this was about WiFi passwords. I will test that
as well.

**Comment by patelkunala** [comment]
@0E800 - Not really, I just wanted to run the utility in the first place, and doing so gives me the aforementioned error dialog. Haven't got to run it so can't say if it does work correctly.

**Comment by 0E800** [comment]
So I can verify it works on Dell Latitude laptop running Windows 7 x64,
also tested on x86 Windows 7. Was able to get all my Chrome credentials,
windows hashes, and the wifi passwords.. All in all, an excellent tool. I
was using 2 or 3 tools to get what this one does in 1.

Let me know if there is anything I can do to help. I am using US keyboard.

BTW what version of Windows 7 do you have? If its not Pro then that could
be the issue.

On Thu, May 28, 2015 at 8:50 AM, Kunal Patel <notifications@github.com>
wrote:

> @0E800 <https://github.com/0E800> - Not really, I just wanted to run the
> utility in the first place, and doing so gives me the aforementioned error
> dialog. Haven't got to run it so can't say if it does work correctly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AlessandroZ/LaZagne/issues/15#issuecomment-106433026>.
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>

**Comment by patelkunala** [comment]
@0E800 - That's strange because I've got Win7 Professional SP1. :-( I'm now burning to get this working since you report that its an excellent one! I'm running out of things to try out....

**Comment by 0E800** [comment]
Have you tried running in compatibility mode? I wonder if it has anything
to do with what windows updates you have or if its a missing c++ run-time
library.

I tested this on a out-of-the-box Dell laptop, just ran windows updates and
that was it.

I wonder if maybe it could be your antivirus interfering. I am using
malwarebytes and nod32 - it didn't post any alerts, but I remember having
to disable my AV when I was using py2exe to convert a python script to
windows executable.

I will do some looking.

On Thu, May 28, 2015 at 9:15 AM, Kunal Patel <notifications@github.com>
wrote:

> @0E800 <https://github.com/0E800> - That's strange because I've got Win7
> Professional SP1. :-( I'm now burning to get this working since you report
> that its an excellent one! I'm running out of things to try out....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AlessandroZ/LaZagne/issues/15#issuecomment-106454800>.
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>

**Comment by patelkunala** [comment]
I have another Vista Home (32bit) Laptop at home will try on it to see if its something on my work machine. I did try the compatibility mode but it didn't look happy at all. I've got C++ 2010 and 2012 redistributables installed. Shall report the results tomorrow, if not tonight.

**Comment by 0E800** [comment]
This might be related?

http://stackoverflow.com/questions/16597867/issue-compiling-using-py2exe-on-windows-7-x64

Unfortunately its not resolved issues.

If you want we can compare installed updates/programs. In the mean time, I
would put lazagne.exe on a usb thumb drive and test it out on some other
computers. ;)



On Thu, May 28, 2015 at 9:20 AM, 0E800 <0ld3nglish800@gmail.com> wrote:

> Have you tried running in compatibility mode? I wonder if it has anything
> to do with what windows updates you have or if its a missing c++ run-time
> library.
>
> I tested this on a out-of-the-box Dell laptop, just ran windows updates
> and that was it.
>
> I wonder if maybe it could be your antivirus interfering. I am using
> malwarebytes and nod32 - it didn't post any alerts, but I remember having
> to disable my AV when I was using py2exe to convert a python script to
> windows executable.
>
> I will do some looking.
>
> On Thu, May 28, 2015 at 9:15 AM, Kunal Patel <notifications@github.com>
> wrote:
>
>> @0E800 <https://github.com/0E800> - That's strange because I've got Win7
>> Professional SP1. :-( I'm now burning to get this working since you report
>> that its an excellent one! I'm running out of things to try out....
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/AlessandroZ/LaZagne/issues/15#issuecomment-106454800>
>> .
>>
>
>
>
> --
>
> [image: --]
> 0E 800
> [image: http://]about.me/oe800
> <http://about.me/oe800>
>
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>

**Comment by patelkunala** [comment]
@0E800 - Right.....came home, tried on my Vista, with and without compatibility mode, I get following error dialog now...

![image](https://cloud.githubusercontent.com/assets/8613550/7865659/31352990-0562-11e5-925d-fa75fd249f61.png)

Had a look at the stackoverflow issue, seems like I might be one of those unlucky souls. I'm running out of options here, quite literally... :P Can compare the installed updates/programs tomorrow (or if you're free later tonight?)

**Comment by 0E800** [comment]
Im in California/USA its still morning my friend. I wonder if it has
anything to do with locale? Unicode or something else I have no clue about.
Keep at it :)


On Thu, May 28, 2015 at 9:55 AM, Kunal Patel <notifications@github.com>
wrote:

> @0E800 <https://github.com/0E800> - Right.....came home, tried on my
> Vista, with and without compatibility mode, I get following error dialog
> now...
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/8613550/7865659/31352990-0562-11e5-925d-fa75fd249f61.png>
>
> Had a look at the stackoverflow issue, seems like I might be one of those
> unlucky souls. I'm running out of options here, quite literally... :P Can
> compare the installed updates/programs tomorrow (or if you're free later
> tonight?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AlessandroZ/LaZagne/issues/15#issuecomment-106486174>.
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>

**Comment by 0E800** [comment]
I will try to compile from source, and see if that exe works for you.

On Thu, May 28, 2015 at 10:03 AM, 0E800 <0ld3nglish800@gmail.com> wrote:

> Im in California/USA its still morning my friend. I wonder if it has
> anything to do with locale? Unicode or something else I have no clue about.
> Keep at it :)
>
>
> On Thu, May 28, 2015 at 9:55 AM, Kunal Patel <notifications@github.com>
> wrote:
>
>> @0E800 <https://github.com/0E800> - Right.....came home, tried on my
>> Vista, with and without compatibility mode, I get following error dialog
>> now...
>>
>> [image: image]
>> <https://cloud.githubusercontent.com/assets/8613550/7865659/31352990-0562-11e5-925d-fa75fd249f61.png>
>>
>> Had a look at the stackoverflow issue, seems like I might be one of those
>> unlucky souls. I'm running out of options here, quite literally... :P Can
>> compare the installed updates/programs tomorrow (or if you're free later
>> tonight?)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/AlessandroZ/LaZagne/issues/15#issuecomment-106486174>
>> .
>>
>
>
>
> --
>
> [image: --]
> 0E 800
> [image: http://]about.me/oe800
> <http://about.me/oe800>
>
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>

**Comment by 0E800** [comment]
Okay so I am still very noobish with python. Try this:

https://drive.google.com/file/d/0BzolLN2vKwxjY3JJT19TdnBJc3c/view?usp=sharing

LaZagne.zip  19.xmb

Extract it and you will get a LaZagne folder
Inside folder there will be some files and a folder - sorry I could not get
it to be one exe file.
From here you have 2 options:
Open the folder in cmd prompt and run lazagne.exe all
    OR
Double click on Export2TXT.exe which will give you passwords.txt which
includes your passwords.

Let me know if it works.

On Thu, May 28, 2015 at 10:06 AM, 0E800 <0ld3nglish800@gmail.com> wrote:

> I will try to compile from source, and see if that exe works for you.
>
> On Thu, May 28, 2015 at 10:03 AM, 0E800 <0ld3nglish800@gmail.com> wrote:
>
>> Im in California/USA its still morning my friend. I wonder if it has
>> anything to do with locale? Unicode or something else I have no clue about.
>> Keep at it :)
>>
>>
>> On Thu, May 28, 2015 at 9:55 AM, Kunal Patel <notifications@github.com>
>> wrote:
>>
>>> @0E800 <https://github.com/0E800> - Right.....came home, tried on my
>>> Vista, with and without compatibility mode, I get following error dialog
>>> now...
>>>
>>> [image: image]
>>> <https://cloud.githubusercontent.com/assets/8613550/7865659/31352990-0562-11e5-925d-fa75fd249f61.png>
>>>
>>> Had a look at the stackoverflow issue, seems like I might be one of
>>> those unlucky souls. I'm running out of options here, quite literally... :P
>>> Can compare the installed updates/programs tomorrow (or if you're free
>>> later tonight?)
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/AlessandroZ/LaZagne/issues/15#issuecomment-106486174>
>>> .
>>>
>>
>>
>>
>> --
>>
>> [image: --]
>> 0E 800
>> [image: http://]about.me/oe800
>> <http://about.me/oe800>
>>
>>
>
>
>
> --
>
> [image: --]
> 0E 800
> [image: http://]about.me/oe800
> <http://about.me/oe800>
>
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>

**Comment by 0E800** [comment]
Okay here is a single exe:

https://drive.google.com/file/d/0BzolLN2vKwxjV2ZuNlpVRlF1cWc/view?usp=sharing

One of these should work.

On Thu, May 28, 2015 at 11:25 AM, 0E800 <0ld3nglish800@gmail.com> wrote:

> Okay so I am still very noobish with python. Try this:
>
>
> https://drive.google.com/file/d/0BzolLN2vKwxjY3JJT19TdnBJc3c/view?usp=sharing
>
> LaZagne.zip  19.xmb
>
> Extract it and you will get a LaZagne folder
> Inside folder there will be some files and a folder - sorry I could not
> get it to be one exe file.
> From here you have 2 options:
> Open the folder in cmd prompt and run lazagne.exe all
>     OR
> Double click on Export2TXT.exe which will give you passwords.txt which
> includes your passwords.
>
> Let me know if it works.
>
> On Thu, May 28, 2015 at 10:06 AM, 0E800 <0ld3nglish800@gmail.com> wrote:
>
>> I will try to compile from source, and see if that exe works for you.
>>
>> On Thu, May 28, 2015 at 10:03 AM, 0E800 <0ld3nglish800@gmail.com> wrote:
>>
>>> Im in California/USA its still morning my friend. I wonder if it has
>>> anything to do with locale? Unicode or something else I have no clue about.
>>> Keep at it :)
>>>
>>>
>>> On Thu, May 28, 2015 at 9:55 AM, Kunal Patel <notifications@github.com>
>>> wrote:
>>>
>>>> @0E800 <https://github.com/0E800> - Right.....came home, tried on my
>>>> Vista, with and without compatibility mode, I get following error dialog
>>>> now...
>>>>
>>>> [image: image]
>>>> <https://cloud.githubusercontent.com/assets/8613550/7865659/31352990-0562-11e5-925d-fa75fd249f61.png>
>>>>
>>>> Had a look at the stackoverflow issue, seems like I might be one of
>>>> those unlucky souls. I'm running out of options here, quite literally... :P
>>>> Can compare the installed updates/programs tomorrow (or if you're free
>>>> later tonight?)
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/AlessandroZ/LaZagne/issues/15#issuecomment-106486174>
>>>> .
>>>>
>>>
>>>
>>>
>>> --
>>>
>>> [image: --]
>>> 0E 800
>>> [image: http://]about.me/oe800
>>> <http://about.me/oe800>
>>>
>>>
>>
>>
>>
>> --
>>
>> [image: --]
>> 0E 800
>> [image: http://]about.me/oe800
>> <http://about.me/oe800>
>>
>>
>
>
>
> --
>
> [image: --]
> 0E 800
> [image: http://]about.me/oe800
> <http://about.me/oe800>
>
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>

**Comment by patelkunala** [comment]
@0E800 - Thanks a lot for the exes, but I'm getting following errors:

![image](https://cloud.githubusercontent.com/assets/8613550/7869688/5b2af418-057c-11e5-8622-2c248ea47917.png)

And for the zip file earlier, Mr. Google doesn't let me download it, it thinks zip file has got some viruses (exe files)

**Comment by 0E800** [comment]
Hmm...okay try this zip file:
https://drive.google.com/file/d/0BzolLN2vKwxjb05iaXR2WkhLUlk/view?usp=sharing

Password is: malt


On Thu, May 28, 2015 at 1:00 PM, Kunal Patel <notifications@github.com>
wrote:

> @0E800 <https://github.com/0E800> - Thanks a lot for the exes, but I'm
> getting following errors:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/8613550/7869688/5b2af418-057c-11e5-8622-2c248ea47917.png>
>
> And for the zip file earlier, Mr. Google doesn't let me download it, it
> thinks zip file has got some viruses (exe files)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AlessandroZ/LaZagne/issues/15#issuecomment-106581207>.
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>

**Comment by patelkunala** [comment]
@0E800 - Same error. :-( Double clicking on the EXPORT2TXT.exe does nothing. I had to turn off my anti-virus to extract and run exe. Dont know what else I could try now....(sigh)

**Comment by 0E800** [comment]
Yeah the export2txt would only work if lazagne did. There has got to be a
reason why its not working for you. All 3 ways work for my own computer or
else I would not have bothered.

Do you have Microsoft C++ 2008 runtime files?

Found this:

5.2. Python 2.6, 2.7, 3.0, 3.1

For Python 2.6, the DLL you need is called MSVCR90.dll. Py2exe is not able
to automatically include this DLL in your dist directory, so you must
provide it yourself.

To complicate things, there is more than one version of this DLL in
existance, each with the same filename. You need the same version that the
Python interpreter was compiled with, which is version 9.0.21022.8. Through
the remainder of these instructions, hover your mouse over the dll file (or
the vcredist_x86.exe installer executable) to confirm which version you've
got. You'll need the vcredist_x86.exe that contains the Microsoft Visual
C++ 2008 Redistributable Package
<http://www.microsoft.com/downloads/en/details.aspx?FamilyID=9b2da534-3e03-4391-8a4d-074b9f2bc1bf&displaylang=en>
published
29-11-2007, so not the VS2008 SP1 one (tested with Python 2.7.1).


So try installing Microsoft Visual C++ 2008 Redistributable Package
<http://www.microsoft.com/downloads/en/details.aspx?FamilyID=9b2da534-3e03-4391-8a4d-074b9f2bc1bf&displaylang=en>

http://www.microsoft.com/en-us/download/details.aspx?id=29



On Thu, May 28, 2015 at 1:30 PM, Kunal Patel <notifications@github.com>
wrote:

> @0E800 <https://github.com/0E800> - Same error. :-( Double clicking on
> the EXPORT2TXT.exe does nothing. I had to turn off my anti-virus to extract
> and run exe. Dont know what else I could try now....(sigh)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AlessandroZ/LaZagne/issues/15#issuecomment-106586933>.
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>

**Comment by patelkunala** [comment]
I think I got higher versions of those than the one you've mentioned, as seen in the following screenshot:
![image](https://cloud.githubusercontent.com/assets/8613550/7870724/fba906c2-0582-11e5-9057-c0b4e53a42f4.png)

Tried installing but it wont let me install, assuming I've got a higher version already installed. Unless I uninstall all 4 of those and then install this one...unsure about it. What do you reckon?

**Comment by 0E800** [comment]
[image: Inline image 1]

I notice that you dont have any x64 versions of Visual C++ not that I know
if it makes a difference.

Here too you can see what is installed on the Win7  x64  laptop:

[image: Inline image 2]

I would suggest installing both x86 and x64 versions of Microsoft Visual
C++ 2012 like you see in the picture above this text.

Hopefully we are onto something mate

On Thu, May 28, 2015 at 1:48 PM, Kunal Patel <notifications@github.com>
wrote:

> I think I got higher versions of those than the one you've mentioned, as
> seen in the following screenshot:
> [image: image]
> <https://cloud.githubusercontent.com/assets/8613550/7870724/fba906c2-0582-11e5-9057-c0b4e53a42f4.png>
>
> Tried installing but it wont let me install, assuming I've got a higher
> version already installed. Unless I uninstall all 4 of those and then
> install this one...unsure about it. What do you reckon?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AlessandroZ/LaZagne/issues/15#issuecomment-106591028>.
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>

**Comment by patelkunala** [comment]
@0E800 - This is my 32 bit Vista Home Premium laptop. I think it'll cough up if I try to install anything 64 bit. Btw, I can't see your images, or am I missing something?

**Comment by 0E800** [comment]
Win 8.1 x64
![image](https://cloud.githubusercontent.com/assets/6632069/7871129/c40f86cc-0542-11e5-8235-3cf85cd6b8ac.png)


Win 7 x64
![image](https://cloud.githubusercontent.com/assets/6632069/7871126/bb1fc93c-0542-11e5-909a-bedb4c442c4e.png)

My bad, I have been using my email client to communicate, apparently github doesnt add the attached images.

**Comment by 0E800** [comment]
Here is what I got on 32bit Win7 laptop:

![image](https://cloud.githubusercontent.com/assets/6632069/7871507/18046372-0545-11e5-8438-59bb962a8d4a.png)

I suggest installing those VC++

**Comment by patelkunala** [comment]
@0E800 - Hmmm....I'm perplexed as in I've got all the VC++ redist with the same versions as you have apart from the one ending with 6161. Installed the ones for VS2012 and 2013, but no luck. Will check again on my work machine tomorrow.

**Comment by patelkunala** [comment]
@0E800 - Dude.....your exe works on my work machine! :-D I'm now more intrigued to why it doesn't work on my Vista laptop. Also the exe from standalone folder here doesn't work on any of my machines. Very strange that....

**Comment by 0E800** [comment]
Glad you got it work in some shape or form. There are multiple ways to
compile a python script to a windows executable.
As I said before I am not a programmer, just a tinkerer. Anyways... with
great power comes great responsibility.
I am always forgetting my passwords, this is a great tool for me in that
aspect. :)

On Fri, May 29, 2015 at 5:51 AM, Kunal Patel <notifications@github.com>
wrote:

> @0E800 <https://github.com/0E800> - Dude.....your exe works on my work
> machine! :-D I'm now more intrigued to why it doesn't work on my Vista
> laptop. Also the exe from standalone folder here doesn't work on any of my
> machines. Very strange that....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AlessandroZ/LaZagne/issues/15#issuecomment-106794395>.
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>

**Comment by patelkunala** [comment]
@0E800 - You're right about multiple ways to compile python. Its a complicated beast, this compiling business :P I must admit you're damn good tinkerer! This is a great tool undoubtedly for people like you & me who cant recall passwords :-) Thanks once again for your help!

**Comment by AlessandroZ** [comment]
@0E800 Could you please give me your way to compile the python script to make it work. Thank you. 

Here is my way, using the pyinstaller development version: python pyinstaller --onefile Lazagne.py

**Comment by 0E800** [comment]
I'll try to make sometime this week to document. I used py2exe on one and
pyinstaller on the other. Pretty sure I manually copied over some extra eggs

**Comment by AlessandroZ** [comment]
@0E800 If you have more information about your way to compile, I could do it by myself and it could help other people I think. Thank you ;)

**Comment by 0E800** [comment]
I am working on build instructions. I cant remember how I did it. One way
is to use py2exe or pyinstaller but dont use the --one-file options, but
use winrar to compress all files into self extracting exe. The issue I am
having with py2exe is that its not including some of the packages needed. I
will try again on Monday.

On Fri, Jun 19, 2015 at 5:43 AM, AlessandroZ <notifications@github.com>
wrote:

> @0E800 <https://github.com/0E800> If you have more information about your
> way to compile, I could do it by myself and it could help other people I
> think. Thank you ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AlessandroZ/LaZagne/issues/15#issuecomment-113504660>.
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>
