### ISSUE TITLE
Error: unrecognised arguments: -drive E

### ISSUE THREAD

**Issue by w3aryb0arpig** [AlessandroZ/LaZagne#151]
I have mounted an external HDD which contains a Windows OS as E drive. I have tried to run the below command but it returns the error, _'error: unrecognised arguments: -drive E'_

lazagne.exe all -drive E

I am running the v2.2 compiled executable file as downloaded from [here](https://github.com/AlessandroZ/LaZagne/releases/) however when I run the --version parameter, it still shows as version 2.1. The MD5 for the .exe is 69c752ccbcbe76645e7f974058952569

**Comment by AlessandroZ** [comment]
This option has already been developed but the binary has not been compiled yet. It will be available on the next release (2.3): https://github.com/AlessandroZ/LaZagne/blob/master/CHANGELOG#L9
