### ISSUE TITLE
[LINUX && OSX] grap .ssh folder and search for .pem files 

### ISSUE THREAD

**Issue by Franco-Poveda** [AlessandroZ/LaZagne#155]
.ssh folder inside user's home dir generally contains private keys for ssh auth. A copy of this files should be made.
Searching for .pem files (generally used for aws ssh auth) on users's home directory sounds like a good idea too. #

**Comment by AlessandroZ** [comment]
Hi, ssh module already exists on the Linux version, it checks for [these files](https://github.com/AlessandroZ/LaZagne/blob/master/Linux/lazagne/softwares/sysadmin/ssh.py#L19).

The problem with .pem files is that theses files are not stored on a default directory so except doing a research in the entire disk, it would be difficult to get it.
