### ISSUE TITLE
lazagne with pupy not working on windows 2008 r2

### ISSUE THREAD

**Issue by cnilsecure** [AlessandroZ/LaZagne#159]
hi I cloned the lastest version of pupy but when i tried to run lazagne module on windows 2008
this is what i get
[!] Error loading package lazagne.config.WinStructure (lazagne/config/WinStructure.pyc pkg=False) : Traceback (most recent call last):
WindowsError: [Error 126] The specified module could not be found
[!] Error loading package lazagne.config.changePrivileges (lazagne/config/changePrivileges.pyc pkg=False) : Traceback (most recent call last):
WindowsError: [Error 126] The specified module could not be found
[!] Error loading package laZagne (laZagne.pyc pkg=False) : Traceback (most recent call last):
WindowsError: [Error 126] The specified module could not be found
[-] (126, 'The specified module could not be found')

========= Remote Traceback (1) =========
Traceback (most recent call last):
WindowsError: [Error 126] The specified module could not be found
Traceback (most recent call last):
  File "/root/pupy/pupy/pupylib/PupyJob.py", line 129, in module_worker
    module.run(args)
  File "/root/pupy/pupy/modules/lazagne.py", line 72, in run
    self.client.conn.modules["laZagne"].runLaZagne,
  File "/usr/lib/python2.7/site-packages/rpyc/core/netref.py", line 213, in method
    return syncreq(_self, consts.HANDLE_CALLATTR, name, args, kwargs)
  File "/usr/lib/python2.7/site-packages/rpyc/core/netref.py", line 72, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/root/pupy/pupy/network/lib/connection.py", line 109, in sync_request
    raise obj
exceptions.WindowsError: (126, 'The specified module could not be found')

========= Remote Traceback (1) =========
Traceback (most recent call last):
WindowsError: [Error 126] The specified module could not be found

any idea what is wrong?

**Comment by AlessandroZ** [comment]
Have you tried in another windows ? (such as win7, 8, 8.1, 10). I have never had this error.

If it doesn't work on another windows, your repo should have a problem. If it works the module should not be compatible for windows 2008 (I have never tested on a Win2008 so maybe it fails).
