### ISSUE TITLE
Are you accepting Pull Requests?

### ISSUE THREAD

**Issue by ben174** [AlessandroZ/LaZagne#16]
I can think of a couple of pieces of software I could contribute to the discoveries.

**Comment by DanMcInerney** [comment]
seconded

**Comment by byt3bl33d3r** [comment]
thirded (??)

**Comment by AlessandroZ** [comment]
Yes of course. 
Do not hesitate to add new modules. Add on the top, in comment, your name to sign in. 

Thanks for your help !!!

**Comment by ben174** [comment]
AlessandroZ - sounds great! If you could add me, ben174 I'd appreciate it!

**Comment by AlessandroZ** [comment]
You could fork the project to add new modules and then push it to my github. I will accept pull request like that. It's easy to do. Thanks for your help.
