### ISSUE TITLE
Kwallet and Gnomekeyring errors on Linux

### ISSUE THREAD

**Issue by TDaglis** [AlessandroZ/LaZagne#160]
After installing the requirements needed for compiling LaZagne (on Ubuntu 16.04), I run the following:
```
pyinstaller --onefile laZagne.py
./dist/laZagne all -v
```
In the Kwallet and Gnomekeyring sections I get the following errors:
```
------------------- Kwallet passwords -----------------

[ERROR] An error occurs with KWallet: No module named QtNetwork

[!] No passwords found

------------------- Gnomekeyring passwords -----------------

[ERROR] An error occurs with the Gnome Keyring wallet: could not import gobject (error was: 'No module named gobject')

[!] No passwords found
```

It appears that the errors occur at the [KWallet](https://github.com/AlessandroZ/LaZagne/blob/master/Linux/lazagne/softwares/wallet/kde.py#L21) and [gnomekeyring](https://github.com/AlessandroZ/LaZagne/blob/master/Linux/lazagne/softwares/wallet/gnome.py#L16) imports.
Running the same imports in a python shell produces no errors.

I'm probably missing something. Any idea what I'm doing wrong?

<details>
 <summary>Requirements installed</summary>

```shell
pip install pyinstaller pycrypto pyasn1 psutil
pip install https://github.com/n1nj4sec/memorpy/archive/master.zip
apt-get install python-gnomekeyring python-kde4 python-dbus python-secretstorage
```
</details>

  
**UPDATE:**
After searching the issues a bit further, I found out [this](https://github.com/AlessandroZ/LaZagne/issues/37#issuecomment-122923271)
>For more passwords, you could try it using the source code, it doesn't manage the system wallet (ex: gnome keyring, Kwallet) with the binary. I don't know why.

So I guess it is a known issue and not a setup/compilation problem from my side

**Comment by AlessandroZ** [comment]
Yes it's a well known issue. However, if you want to work with a binary file (without any dependency), you could use the [pupy](https://github.com/n1nj4sec/pupy) project. Generate a binary, and then call the module lazagne. The wallets module will work. 

Have a nice day !
