### ISSUE TITLE
The system cannot execute the specified program.

### ISSUE THREAD

**Issue by JohnAntonusMaximus** [AlessandroZ/LaZagne#161]
Trying to run the laZagne.exe in a powershell script by downloading the file remotely, unzipping, and the executing the program all via powershell, but Windows is telling me 'The system cannot execute the specified program'. Any idea why?

**Comment by AlessandroZ** [comment]
The error could be done because of a not compatible "Microsoft VC++ runtime Library" between the compiled executable and your windows. Try to compile it yourself or install a new version of the runtime library, it should work.
