### ISSUE TITLE
Empty Directories

### ISSUE THREAD

**Issue by Cech1337** [AlessandroZ/LaZagne#163]
I have just updated Bash Bunny to 1.4 and added the following files to the switch2 directory (d.exe, e.exe, i.vbs, lazagne.exe, lazagne.py, payload.txt and readme.md). Once everything set to arming mode, I've switched it to attack mode 2 and plugged in to a PC. Once the green light finished and plugged it back again to my PC in arming mode, the directories and notepad files were all empty.

Am I doing something wrong or ? 

Thank you in advance :)

**Comment by AlessandroZ** [comment]
Sorry but I have never used Bash Bunny so I cannot help you.

**Comment by 0ri0n1** [comment]
i experienced the same issue with 1.5 fw on the Bash Bunny
