### ISSUE TITLE
Not getting passwords from chrome when i compile it myself

### ISSUE THREAD

**Issue by SpeedBird95** [AlessandroZ/LaZagne#164]
Hi , when i use the distributed exe I can extract chrome passwords , however when i use pyinstall on windows with python 2.7 and follow all instructions to compile I only get half as much passwords , in particular chrome passwords are missing.

**Comment by SpeedBird95** [comment]
I get the following in the warnings file generated by pyinstalled in build/lasagne

missing module named org - imported by copy
missing module named EasyDialogs - imported by getpass
missing module named termios - imported by getpass
missing module named pwd - imported by posixpath, getpass, shutil, tarfile, psutil
missing module named _sysconfigdata - imported by distutils.sysconfig
missing module named fcntl - imported by tempfile, subprocess
missing module named grp - imported by shutil, tarfile
missing module named readline - imported by cmd, pdb
missing module named 'org.python' - imported by pickle, xml.sax
missing module named riscosenviron - imported by os
missing module named riscospath - imported by os
missing module named riscos - imported by os
missing module named ce - imported by os
missing module named _emx_link - imported by os
missing module named os2 - imported by os
missing module named posix - imported by os
missing module named resource - imported by posix
missing module named psutil._psutil_aix - imported by psutil, psutil._psaix
missing module named psutil._psutil_sunos - imported by psutil, psutil._pssunos
missing module named ElementC14N - imported by xml.etree.ElementTree
missing module named _scproxy - imported by urllib
missing module named SOCKS - imported by ftplib
missing module named rourl2path - imported by urllib
missing module named 'java.lang' - imported by platform, xml.sax._exceptions
missing module named _xmlplus - imported by xml
missing module named psutil._psutil_bsd - imported by psutil, psutil._psbsd
missing module named psutil._psutil_osx - imported by psutil, psutil._psosx
missing module named enum - imported by psutil._common, psutil._pslinux, psutil._pswindows
missing module named _psutil_linux - imported by psutil
missing module named psutil._psutil_posix - imported by psutil, psutil._pslinux, psutil._psosx, psutil._psbsd, psutil._pssunos, psutil._psaix
missing module named _dummy_threading - imported by dummy_threading
missing module named vms_lib - imported by platform
missing module named java - imported by platform
missing module named 'Carbon.File' - imported by plistlib
missing module named 'Carbon.Files' - imported by plistlib
missing module named Carbon - imported by plistlib
missing module named MacOS - imported by platform
missing module named macresource - imported by MacOS
missing module named gestalt - imported by platform
missing module named pydasm - imported by memorpy.WinProcess
missing module named Crypto.PublicKey._fastmath - imported by Crypto.PublicKey, Crypto.Util.number, Crypto.PublicKey.RSA, Crypto.PublicKey.DSA

**Comment by AlessandroZ** [comment]
I don't think that warnings from pyinstaller are the problem. I have never had this problem, so I cannot help you. Tell me if you find the solution, I would be interested. Thanks.
