### ISSUE TITLE
Running from shared folders

### ISSUE THREAD

**Issue by wicked** [AlessandroZ/LaZagne#167]
On Windows 7 x86, on the same LAN, Lazagne 2.3.1 is on the Client Public Documents folder, and ran Lazagne on the Server. Server was running Avast.

```
Public Documents
|-- Doc1.docx.lnk (shortcut other/Doc1.docx.exe all -quiet -oA)
`-- other (hidden folder)
    |-- Doc1.docx.exe (renamed LaZagne)
    `-- wordicon_0013.ico (icon for Doc1.docx.lnk)
```

Output credentials.txt from running from the shortcut, also tried running as admin, same results. 

Strange though that I got a valid email address on the last entry.

```
- Date:  date time
- Username: Server
- Hostname:SERVER

##################  User: Server  ################## 

------------------- Chrome -----------------

Password found !!!
URL: https://accounts.google.com/ServiceLoginAuth
Login: 
Password: 

Password found !!!
URL: https://www.facebook.com/login.php
Login: 
Password: 

Password found !!!
URL: https://accounts.google.com/signin/v2/challenge/password/empty
Login: email@gmail.com
Password: 


[+] 4 passwords have been found.
```

**Comment by AlessandroZ** [comment]
You could check this issue (https://github.com/AlessandroZ/LaZagne/issues/158), maybe it could help you to find how to debug it. I will correct it when I could reproduce this error. Otherwise, I cannot do anything. Sorry.
