### ISSUE TITLE
Problems with compilation

### ISSUE THREAD

**Issue by Patrhal** [AlessandroZ/LaZagne#168]
Hi Alessandro,

sorry to bother you. I have some problems with compilation. 

I try to compile it on Windows 7 (x64), Python 3.6.3. I have some problems with syntax of LaZagne.py:
```
314: except Exception, e: (the comma)
315: print e
432: print '\nelapsed time = ' + str(elapsed_time)
```

Maybe it is because of the different Python version?

If I fix the the syntax and compile it, than I get an error during execution of the LaZagne.exe:

```
Traceback (most recent call last):
  File "laZagne.py", line 13, in <module>
    from lazagne.softwares.browsers.mozilla import Mozilla
ModuleNotFoundError: No module named 'lazagne.softwares.browsers.mozilla'
[4888] Failed to execute script laZagne
```

Do you have some ideas?

**Comment by AlessandroZ** [comment]
Hi, I do not recommend using the python 3 version. The syntax is different and some error could happened. 

Use Python 2.7 instead.

**Comment by Patrhal** [comment]
Sorry. I have missed the requirements https://github.com/AlessandroZ/LaZagne/wiki/Requirements .

Now these errors are gone.

However I still have an error after compilation.

`ImportError: No module named memorpy`

I have found our old temporary note. But even if I copy the memorpy folder to the "LaZagne-master\Windows\lazagne\softwares\memory" I still have the problem.

Do you have any clues?

**Comment by AlessandroZ** [comment]
It's all explained on the wiki 

`pip install https://github.com/n1nj4sec/memorpy/archive/master.zip`
