### ISSUE TITLE
Unicode problem on 2.3.1

### ISSUE THREAD

**Issue by GamersForOne** [AlessandroZ/LaZagne#169]
Using my Microsoft account which contains my swedish name on Windows 10, I get this error
```
D:\Root\Desktop>laZagne.exe all

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

Traceback (most recent call last):
  File "laZagne.py", line 423, in <module>
  File "laZagne.py", line 267, in runLaZagne
  File "laZagne.py", line 226, in set_env_variables
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 8: ordinal not in range(128)
[19328] Failed to execute script laZagne
```
the character which failed is ``ö``

**Comment by AlessandroZ** [comment]
Launch it again writing the result on a file (json or txt) and tell me if the password is well decoded. 
`lazagne.exe all -oA `

**Comment by GamersForOne** [comment]
I did that, and this was the only thing that showed up, no sensitive information at this point.
```
|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|
		
- Date: 2017-12-05 17:18:05
- Username: Dennis Rönn
- Hostname:MSI
```
From what I understand it's my Windows username, which is bound to my Microsoft account, which causes it since my surname contains special characters.

**Comment by AlessandroZ** [comment]
So it worked or it failed ? 
Your name is well printed but no passwords or you do not have stored passwords on your computer ? 
If you could try to run the python script instead of the exe it will be easily for me to help you to debug. I had done some tests some times ago with a username containing russian char and it worked. So maybe it's another error.

Run it again with -vvv to check where the error appears. `lazagne.exe all -vvv`

**Comment by AlessandroZ** [comment]
I have fixed an issue coming from the "set_env_variables" function which appeared on your error message.
