### ISSUE TITLE
Outlook

### ISSUE THREAD

**Issue by hostbob** [AlessandroZ/LaZagne#174]
i tried lazagne against outlook 2010-2016 but couldnt see it recover the passwords. do you notice this or it doesnt support it anymore

**Comment by AlessandroZ** [comment]
Outlook password are stored in different ways depending on if it uses exchange or not. If it does not use Exchange, the password is stored on the windows registry. However, for Exchange password, the password is stored in the credentials manager as Domain type. So right now, these kind of passwords are not supported yet. I have opened an issue called "Decrypting Domain Passwords" for some help. 

Moreover, you should have admin privilege to decrypt it.

**Comment by hostbob** [comment]
thank you for the heads up. i have a remote desktop which uses outlook 2016 and has user and password already saved, but when using a software for recovery it couldnt recover the password but the software could recover other system outlook password. i do not know if you might create a chance for IM chat i can show this on TV just to know where to begin with
