### ISSUE TITLE
Not Pulling Admin Passwords

### ISSUE THREAD

**Issue by ThatAlbinoFrog** [AlessandroZ/LaZagne#179]
Hey, whenever I run Lazagne, in admin it's unable to get any of the admin required passwords. e.g Wifi passwords.

Any help would be Appreciated

P.S - Could you add a public IP grabber? Would be really useful in this tool

**Comment by AlessandroZ** [comment]
It should work now. I didn't build the executable yet, so you should wait some days, but the code has been fixed (do not hesitate to open it again if you have the same issue).
