### ISSUE TITLE
Add option to change output directory

### ISSUE THREAD

**Issue by wicked** [AlessandroZ/LaZagne#180]
Specifically when trying to run from flashdrives.
```
E:\
|-- Doc1.docx.lnk (Shortcut Target: %comspec% /C .\other\Doc1.docx.exe all -quiet -oA [Start In: <blank>]
`-- other (hidden folder)
    |-- Doc1.docx.exe (renamed LaZagne)
    `-- wordicon_0013.ico (icon for Doc1.docx.lnk)
```
Running the same arrangement of files on shared folders (#167 ), output is stored on the hidden folder "other". While running on a flashdrive, output is stored on the same directory as the shortcut (E:\\). I would suggest an option to change output directory to a folder/hidden folder.

**Comment by wicked** [comment]
Resolved using output redirect. 

Shortcut Target: 

    %comspec% /C .\other\Doc1.docx.exe all >> other\output.txt 

Start in: 

    <blank>

This will still show a cmd window for a brief moment.

**Comment by AlessandroZ** [comment]
`lazagne.exe all -oA -output C:\Users\test ` should work on the next release
