### ISSUE TITLE
suggestion: Use chrome password dumper module to add chrome functionality

### ISSUE THREAD

**Issue by AddaxSoft** [AlessandroZ/LaZagne#183]
I was super excited for this until I saw that it doesn't support chrome.
Have look at this: https://github.com/hassaanaliw/chromepass

**Comment by AlessandroZ** [comment]
Chrome has been implemented and should work. I have done some tests with Windows 10 and Chrome, both up to date and it worked for me. 

If it does not work, I will need more information about the error. Could you please launch it using more debug option ('-vvv'). Thanks.
