### ISSUE TITLE
Detected by Windows Defender

### ISSUE THREAD

**Issue by tiny3001** [AlessandroZ/LaZagne#186]
Detected as:

```
Trojan:Win32/Tilken.B!cl

Alert level: Severe
Status: Active
Date: 2018/01/04

Recommended action: Remove threat now.
```

**Comment by AlessandroZ** [comment]
I'm sorry but I won't correct all issue related to bypass antivirus. Lots of methods exist and are easy to implement. Sorry.

**Comment by tiny3001** [comment]
Thanks. Just wanted to make sure it's not an actual issue.
