### ISSUE TITLE
requirements for python 

### ISSUE THREAD

**Issue by csmali** [AlessandroZ/LaZagne#187]
maybe it would be better to have requirements.txt for python libraries to make installation easier

**Comment by AlessandroZ** [comment]
The problem is that requirements depends on the system you want to install (Linux, Windows, Mac). That's why I have done a wiki explaining all dependencies needed by OS: https://github.com/AlessandroZ/LaZagne/wiki/Requirements
Otherwise, I will have to do 3 different requirements file, one by OS.

**Comment by csmali** [comment]
Ultimately as an end-user , process of using tool ends up with installation dependencies one by one. I thought creating 3 different requirements  file would be reasonable. If you agree too I would like to contribute.

**Comment by killercoderz4** [comment]
Good day alessandoz. I am using lazagne via pupy. It great but I can't enable persistence on my power shell one liner . itest it on my VM and when I restart my VM I loose session.I want to auto enable persistence and lazagne using puppy scriptlet. Any sample command line snippet would be OK. Thanks

**Comment by AlessandroZ** [comment]
@csmali, do not hesitate to contribute. You could do a file called `requirement.txt` and you could put it in in each repository by OS ([Linux](https://github.com/AlessandroZ/LaZagne/tree/master/Linux), [Mac](https://github.com/AlessandroZ/LaZagne/tree/master/Mac), [Windows](https://github.com/AlessandroZ/LaZagne/tree/master/Windows)).
