### ISSUE TITLE
lazagne not working on VM

### ISSUE THREAD

**Issue by oczz** [AlessandroZ/LaZagne#189]
Hello. I am working actually with a company to retrieve some password's on windows 10 and windows 7 environment. I already used lazagne in the past and it worked well, first time i try to use it on a VM. Now, i downlaoded the lazagne.exe, i have 2 hard drive (one with windows 10, other one with windows 7). I ran a VM on both of them. Ran CMD as admin on both, ran lazagne -all module. It extracts alot of username (30+) but ALL the passwords are: False

First time it happen, for mostly firefox. 

I tried with the -drive C  to be sure i was aiming the right path.. same results

I ran -vvv option, i got this: DEBUG temporary file removed c:/users/users/appdata/local/temp/qmzgabd

i have the latest version of lazagne, running in windows environment.

whats wrong?

**Comment by oczz** [comment]
If its the vm causing the problem, could i extract the appdata folder , put it on a usb Drive and run lazagne -drive Myusbkey 

Or its going further than the appdata to retriever the credentials? Which other folder id need?

**Comment by AlessandroZ** [comment]
For forensic usage: https://github.com/AlessandroZ/LaZagneForensic

**Comment by oczz** [comment]
Merci pour ton suivi, j'ai pas encore tester la VM j'étais en formation hors province.

Mon prochain test sera de réinitialiser le password d'une session Windows 10 pro avec une clé passware, mettre comme mot de passe 12345 , ouvrir la session en VM avec le mot de passe 12345 et lancer lazagne

J'ai envoyé ton script forensic à  notre analyste scripteur pour qu'il fasse ses tests de son côté

Un grand merci, tu n'as pas idée comment ça nous aide, simplement récupérer les password de cloud tel que box et méga , où la majorité des suspects y cachent de plus en plus des plans de terrorismes ou leur pornographie juvénile , entre autre. Plus sécuritaire qu'une simple clé usb, permet à plusieurs complices d'avoir accès simultanément aux fichiers sur un cloud...

Bref , merci du coup de pouce

Télécharger Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by AlessandroZ** [comment]
Content que ce soit utile !!
