### ISSUE TITLE
Doesnt work in some W10 PCs

### ISSUE THREAD

**Issue by almaefogo** [AlessandroZ/LaZagne#192]
i cant get to work in some windows 10 computers, in my computer it works, but in my buddy computer its doesnt works both running w10.
It only shows the name of the computer.

**Comment by almaefogo** [comment]
i did it with verbose enabled here is the result
[cmd.txt](https://github.com/AlessandroZ/LaZagne/files/1642616/cmd.txt)

**Comment by AlessandroZ** [comment]
should be filxed on the next release
