### ISSUE TITLE
pb with firefox

### ISSUE THREAD

**Issue by Cezanna** [AlessandroZ/LaZagne#193]
Firefox version >=57
mac os x up to date
Mac root# ./laZagne.py  browsers -vvv
.........
 ------------------- Firefox passwords -----------------

[INFO] Firefox not installed.

[!] No passwords found

**Comment by AlessandroZ** [comment]
Is this path exists on your system : ~/Library/Application Support/Firefox/

**Comment by Cezanna** [comment]
Yes this path exists
But I solve my problem.
1) from FF under macos on my imac, I organized to sync with my other devices
2) from safari I import everything including password and propagate them using iCloud
3) on my macbook pro and imac, I import for opera and chrome. 

So, I consider, my probleme is solved.
