### ISSUE TITLE
\Windows\laZagne.py error line 317

### ISSUE THREAD

**Issue by clirimfurriku** [AlessandroZ/LaZagne#196]
> I get this error while compiling 

Syntax error in C:\Users\PC1\Documents\LaZagne\Windows\laZagne.py
  File "C:\Users\PC1\Documents\LaZagne\Windows\laZagne.py", line 3
17
     except Exception, e:
                     ^
 SyntaxError: invalid syntax

> Lines in code \Windows\laZagne.py

310				# Launch module wanted
311					for r in runModule(category_choosed, need_system_privileges=_need_system_privileges, cannot_be_impersonate_using_tokens=_cannot_be_impersonate_using_tokens):
312						yield r
313					
314					rev2self()
315					stdoutRes.append(constant.finalResults)
316					break
317				except Exception, e:
318					print e
319					pass

**Comment by WinXprt** [comment]
For windows system directly download from the following link:
https://github.com/AlessandroZ/LaZagne/releases/

**Comment by AlessandroZ** [comment]
Check the wiki if you want to compile it.
