### ISSUE TITLE
LaZagne doesn't work in Windows XP right now

### ISSUE THREAD

**Issue by alxchk** [AlessandroZ/LaZagne#197]
Yes, it's Y2018..
But anyway.

At least in WinStructure.py there are functions which are missing in winxp, for example Vault.
It's better to handle their absence properly.

**Comment by AlessandroZ** [comment]
Wish you an happy 2018 !! :) 

I will be in holiday for a week, so I will check that  later. I should create an XP VM, because right now, I never tried it on an XP. I will check it soon.

**Comment by m41nt41n3r** [comment]
The problem is that vault functions are not available in XP.
WinStruct.py:332
```

prototype 						= WINFUNCTYPE(ULONG, DWORD, LPDWORD, POINTER(LPGUID))
vaultEnumerateVaults 			= prototype(("VaultEnumerateVaults", windll.vaultcli))

```
It produces an unhandled exception. It's necessary to try->except this part of code and check for availablity when vault is processed.

**Comment by AlessandroZ** [comment]
Thanks, I have corrected it and tested it.
