### ISSUE TITLE
Windows 8.1

### ISSUE THREAD

**Issue by glira** [AlessandroZ/LaZagne#2]
I tried to use in Windows 8.1 did not work, said there were no credentials.

**Comment by AlessandroZ** [comment]
Hi, 
"No credentials" does not mean that it does not work. 
I have done some tests on Windows 8.1 and I have no errors. 

The difference between win7 and win8 is that LaZagne does not retrieve the credential manager on Win8 (internet explorer, network passwords, etc, use the credential manager to store their credentials). 
However, Firefox, opera and the other softwares do not change their way to store the password. 

Launch it with the -v option for more information. 
If you have some explicit error messages, send it to me. Thank you.
