### ISSUE TITLE
python-kde4» no tiene un candidato para la instalación

### ISSUE THREAD

**Issue by gearcapitan** [AlessandroZ/LaZagne#200]
└─[$] <git:(master)> apt-get install python-gnomekeyring python-kde4 python-dbus
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
El paquete python-kde4 no está disponible, pero algún otro paquete hace referencia
a él. Esto puede significar que el paquete falta, está obsoleto o sólo se
encuentra disponible desde alguna otra fuente

E: El paquete «python-kde4» no tiene un candidato para la instalación

**Comment by AlessandroZ** [comment]
Yo lo tengo en los paquetes: 

```
yo:~$ apt search python-kde4
Sorting... Done
Full Text Search... Done
python-kde4/artful 4:4.14.2-0ubuntu8 amd64
  Python bindings for the KDE Development Platform

python-kde4-dbg/artful 4:4.14.2-0ubuntu8 amd64
  debugging symbols for the PyKDE bindings

python-kde4-dev/artful,artful 4:4.14.2-0ubuntu8 all
  UIC compiler and SIP files for PyKDE

python-kde4-doc/artful,artful 4:4.14.2-0ubuntu8 all
  documentation and examples for PyKDE
```
