### ISSUE TITLE
DPAPI password check

### ISSUE THREAD

**Issue by KiUserExceptionDispatcher** [AlessandroZ/LaZagne#202]
Hello.
This code from lazagne/config/dpapi_structure.py:70:

> 	if self.umkp.try_credential(self.sid, password):

checks already found passwords for current windows user account. But if the password is invalid (for example it's generally not a string) exception happens in Windows/lazagne/config/dpapi/DPAPI/Core/masterkey.py:281:

>  self.decryptWithHash(userSID, hashlib.new(algo, pwd.encode('UTF-16LE')).digest())

As a solution it's possible try to encode('UTF-16LE') before try_credential call.

**Comment by KiUserExceptionDispatcher** [comment]
PS: it's a good practice to use simplejson instead of json ;)

**Comment by AlessandroZ** [comment]
Thanks for your feedback. 
I forced the password as string doing a [cast](https://github.com/AlessandroZ/LaZagne/commit/61379c6f3ecb53e7c939943403ef3616ebcbb330). It should work now. 

I cannot understand why password are empty or not as a string. If you could help me to understand the problem, it should be great. 

And why do you prefer simplejson instead json ? I know that there are more uptades in simplejson package put it's not a default package of python, so it has to be installed and I tried to remove all external package to decrease the size of the tool. 

Open the issue again, if you still having problems with this DPAPI check.
