### ISSUE TITLE
thunderbird category

### ISSUE THREAD

**Issue by m41nt41n3r** [AlessandroZ/LaZagne#206]
Hello. There is a small bug: Windows/lazagne/softwares/browsers/mozilla.py:109:

`ModuleInfo.__init__(self, 'thunderbird', 'browsers', options, suboptions, need_to_be_in_env=False)`

Should be:

`ModuleInfo.__init__(self, 'thunderbird', 'mails', options, suboptions, need_to_be_in_env=False)`

**Comment by AlessandroZ** [comment]
This is not an error, try `lazagne browsers -h` and you will see firefox only, and `lazagne mails -h` you will see thunderbird.
