### ISSUE TITLE
compiled lazagne.exe file execution error!

### ISSUE THREAD

**Issue by Kivancx** [AlessandroZ/LaZagne#208]
![se] (https://user-images.githubusercontent.com/37018518/36934771-478f779c-1ebc-11e8-9277-38eca18c289b.PNG)

Hello,
I am trying to execute the .exe file compiled using the method that has been given but after I execute/run the .exe file on windows, it gives the error shown in the above image. Need help with this please!

**Comment by AlessandroZ** [comment]
You should install all requirements needed: https://github.com/AlessandroZ/LaZagne/wiki/Requirements
