### ISSUE TITLE
WiFi module bug

### ISSUE THREAD

**Issue by m41nt41n3r** [AlessandroZ/LaZagne#209]
Hello.
Example output:

> [Wifi] {'Authentication': 'open', 'Protected': 'true', 'SSID': 'coffeshop', 'Password': '\x11\x11\x11\x11\x11"""""'}

So here is the easiest solution (softwares\wifi\wifi.py):
```
if values and values['Authentication'] != 'open':
	pwdFound.append(values)	
```

**Comment by AlessandroZ** [comment]
Thanks, I did the [correction](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/wifi/wifi.py#L69)
