### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by tautology0** [AlessandroZ/LaZagne#21]
I've got a few bits and pieces around to rip passwords from Android files and directories (either through the userdata partition mounted or the adb debugging protocol) which I intended to write something similar and never got around to.

It is possible to get an empty version set up that I can plagurise erm... add modules for? (I'm an old perl coder, and my python is usually used for messing around in scapy or amending other code.)

And basic documentation on how to add new OSes?

**Comment by AlessandroZ** [comment]
I am not sure to understand very well your request. 

However, to manage modules in python, you could use as example some of my files: 
- the main file: https://github.com/AlessandroZ/LaZagne/blob/master/Linux/src/LaZagne.py
	=> import all modules into a dictionary to manage it

- module information: https://github.com/AlessandroZ/LaZagne/blob/master/Linux/src/config/moduleInfo.py
	=> class to store all information about a module

- import module: https://github.com/AlessandroZ/LaZagne/blob/master/Linux/src/config/manageModules.py
	=> used to import classes (adding a new module will be done here)

Doing so for Android would be a great idea. Good luck!

**Comment by lclevy** [comment]
Hi Alessandro,
Nothing related with Android. Just to avoid (under Linux and Windows) using nss library to recover Mozilla passwords, that's all. My python code reimplements nss features in python (more portable)

Le 27 mai 2015 13:41:02 GMT+02:00, AlessandroZ <notifications@github.com> a écrit :
>I am not sure to understand very well your request. 
>
>However, to manage modules in python, you could use as example some of
>my files: 
>- the main file:
>https://github.com/AlessandroZ/LaZagne/blob/master/Linux/src/LaZagne.py
>	=> import all modules into a dictionary to manage it
>
>- module information:
>https://github.com/AlessandroZ/LaZagne/blob/master/Linux/src/config/moduleInfo.py
>	=> class to store all information about a module
>
>- import module:
>https://github.com/AlessandroZ/LaZagne/blob/master/Linux/src/config/manageModules.py
>	=> used to import classes (adding a new module will be done here)
>
>Doing so for Android would be a great idea. Good luck!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/AlessandroZ/LaZagne/issues/21#issuecomment-105880151

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by iwundu** [comment]
Hello everyone! Can lazagne work on android? Or does anybody knows how to run similar task on android devices?
