### ISSUE TITLE
filezilla small bug

### ISSUE THREAD

**Issue by m41nt41n3r** [AlessandroZ/LaZagne#210]
Hello.

> Traceback (most recent call last):
> ...
>   File "lazagne\softwares\sysadmin\filezilla.py", line 39, in run
> KeyError: 'encoding'

So here is a small fix (softwares\sysadmin\filezilla.py):

`if 'encoding' in password.attrib and password.attrib['encoding'] == 'base64':`

**Comment by AlessandroZ** [comment]
Fixed, thanks :)
