### ISSUE TITLE
ie.py unreferenced variable and exception handling

### ISSUE THREAD

**Issue by m41nt41n3r** [AlessandroZ/LaZagne#211]
Hello.

Here is the code:

```
		pwd = Win32CryptUnprotectData(cipher_text, u)
		if pwd:
			for i in range(len(pwd)):
				try:
					a = pwd[i:].decode('UTF-16LE')
					a = a.decode('utf-8')
					break
				except Exception, e:
					result = ''
		
		# the last one is always equal to 0
                secret = a.split('\x00')
```

Sometimes I causes:

> UnboundLocalError: local variable 'a' referenced before assignment

I hope the solution is clear ;)

Also here is one more bug. If exception causes then it's necessary to return pfound = [], not simply to set result ='' (which is no more used below).

**Comment by AlessandroZ** [comment]
Fixed, thanks :)
