### ISSUE TITLE
XML parsing suggestion

### ISSUE THREAD

**Issue by m41nt41n3r** [AlessandroZ/LaZagne#212]
Hello.

Due to malformed XML's it's better to surroud all ElementTree calls with try->except ParseError.
For example I had such exception in puttycm.py module.

**Comment by AlessandroZ** [comment]
I didn't find your example? 
And I don't see the utility of using this exception, all modules are launched using a try and catch and the error will be printed using the [traceback](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/laZagne.py#L104) function. So if the xml is not correct, we should see it on this output. 

Maybe I'm wrong, but right now I don't see the purpose of using it. No?

**Comment by m41nt41n3r** [comment]
May be you are right but I don't think this information (traceback) could be helpful.

**Comment by AlessandroZ** [comment]
The traceback is used to print errors in order to be able to debug, not only for xml errors.
