### ISSUE TITLE
Problem when running lazagne.

### ISSUE THREAD

**Issue by hanton95** [AlessandroZ/LaZagne#214]
Hello, I have a problem, I've been trying for 30 minutes to make LaZagne work but I can not get it, every time I run the command it gives "error" and even though I see videos of other people, it does work for them. I use Windows 10 x64. I'm sorry for my English, it's a little bad.

![simbolo del sistema 08_03_2018 12_21_20](https://user-images.githubusercontent.com/15985059/37148655-88a09ed8-22cb-11e8-8770-134ea214c22d.png)

**Comment by AlessandroZ** [comment]
Hi, you should try the last version (from the source code and not the last release). I didn't build a release yet.
