### ISSUE TITLE
credman suggestion

### ISSUE THREAD

**Issue by m41nt41n3r** [AlessandroZ/LaZagne#216]
Hello.

Sometimes this module produces smth like this:

`[Credman] {'URL': 'MicrosoftOffice16_Data:ADAL:67fc256b-8308-4c70-82f4-798e92fe92f4@@@2.000000', 'Login': None, 'Password': '32UMIe5Rbqm24LJndQjQaj5ttg7ApaBFjoKCfhtBngRgRK8jXXYOjjZ6Os4sx/x0mUcY1iGY4PZl6sOn10elKvJpyCxL9Wbf/fRyu79+3kUZB1K6gU6A7MvSARP29Z12HVQigSW1X6VdD7Fth72EZ9Wb7DSH3H5sAdjc98LpMTMzgPaEkIVxwTtOikF5FTzCMTpj7Ugejt7oXskgSA9xf2+y/srum4WGT2Xur5Y+u2o3a5N4xeDuGTN3XIQ1ddL5RtLAb8fR3Ryrb6htFBkrhJ3OBK2cKYr/VDyx7rTNVORoS5sp8pk3XEjmMGADffsrVF8/yKu8OaktTRepMXRY4LBmwVVtiI2o0JUOQ+JtDxq5Hm+IKOIraYarbWOpM91JQS5yQTGa7lkhnlg+hM79DeRWPFGwhnXbX3q+Wm2uu02B5CczwvSmc0V7wAlUQY3pGiv64JtmkXmauF8FBUaxr3WiQrRL1o+5ysn42uJEIc9UfjX4BZn8+72yjIEu94eT+2qnU67Y7ysr1bUndZHRffOlayPda6IN3Wu5dRSv57AzNSWUNxY+j/+89/DO1H85T/9w+P5KStcuhZdAsU7J9Bz9kELP/n932hWWJGhNNx8qsEeCEvsgQhHCvnmwctfMSsIhMYLxA9YwdQZfP+AFTQ+GNTNr5UVYiihKZCGNHI+yRbfR3FivmP6mOPE9d4b/gVmNBZIdoGxIjEmE8ZqALyCs4JdQswmrqOPIC9G17njBbKPLCSJ+VuUr+8ynKXeMcndUePX/V3ml7D3qaGGMj431N5tLbH9tS+j2C/FFh4fGek9Cz2ybuWdIPLRp8yDCJdKkS/1bz4giQWU75lZwUzMEOqGYUDGDOr0cOavjUs+Z6/VOzu4NCzBqJoww2wyAVzl4/qTBhuCuTPJ3gxYTbqzCkSYRcsHc1Uc+YabgjFaT4CAklEIuCpAEiDcR9YOKPXOpplOiQ3EfumettMebRFmxFNQIgIeOd51BoyNk'} `

I don't think this data may be useful so we can filter it. The simplest way is to hardcode password length limit (credman.py):

```

if login or password:
	if password and len(password) > 100: # Enough for human passwords
		continue

```

**Comment by m41nt41n3r** [comment]
The same with vault.py.

**Comment by AlessandroZ** [comment]
I have removed it on both module. Thanks
