### ISSUE TITLE
Boot from usb

### ISSUE THREAD

**Issue by ReiSixx9** [AlessandroZ/LaZagne#217]
I'm trying to use LaZagne to find the passwords on a computer without knowing the windows password. As you can probably tell, I'm using Windows 7.

Anyways, I was hoping you could help me with a small problem I have. As I said, I need to run LaZagne from a cmd prompt without logging into windows. I have this all worked out except I can't figure out how to run it from a USB as when I do no passwords are found (I'm guessing because it's searching the USB instead of the computer). 

Thanks!

**Comment by m41nt41n3r** [comment]
A lot of modules require active user session due to [cryptunprotectdata](https://msdn.microsoft.com/en-us/library/windows/desktop/aa380882(v=vs.85).aspx).

**Comment by ReiSixx9** [comment]
So I the target user just needs to be signed in?

**Comment by ReiSixx9** [comment]
Okay, never mind, that's not it. So how would I run LaZagne without knowing the target user's password?

**Comment by Prince-741152** [comment]
If it was windows 10 then I could help...!!

**Comment by AlessandroZ** [comment]
If you connected to the windows system, you should be able to use lazagne without knowing his password. If the system is locked and you cannot connect to it, you should use [lazagneforensic](https://github.com/AlessandroZ/LaZagneForensic) to launch it from a live cd.
