### ISSUE TITLE
Regular laZagne output being sent to stderr instead of stdout

### ISSUE THREAD

**Issue by newlog** [AlessandroZ/LaZagne#223]
Hi there!

First of all, thanks for your amazing work on this tool.

I'm starting to play a little bit with it and I realized that many logs (e.g. not found passwords) are sent to stderr.

For example, the category titles (e.g. "------------ Ssh ------------") are sent to stderr instead of stdout, along with the "No password found" string. In my opinion, this should also be part of the standard output given that it's not a tool execution error but rather regular tool output.

I saw that anything not using the `do_print` (write_output.py, L116) method is printing to stderr.

This is happening because in the `verbosity` (laZagne.py, L68) method, the `logging.StreamHandler()` is executed without parameters instead of something like `logging.StreamHandler(stream=sys.stdout)`.

Is this by design or should it be changed? To be honest, having the categories and the password not found lines being sent to stderr makes the output really difficult to parse.

I want to parse both the successful hits and the failed category attempts. If I try it using the script output I have the problem regarding stderr and stdout. If I try to store it in a file, the failed attempts do not get logged :(

What do you think? Any workaround? I'd like to avoid a `2>&1` so I don't end up ignoring real errors. 

If you find this reasonable (`StreamHandler(stream=sys.stdout)`), I can send a PR.

Thanks for your hard work!

--------

As a side note:

<img src="https://user-images.githubusercontent.com/950789/37677261-d97b47a0-2c7a-11e8-8645-c8ce8d673e7a.png" width="300">

From laZagne.py, L97. As far as I can tell, `b` will never exist, so `modulesToLaunch` will always be empty.

**Comment by newlog** [comment]
Hey,

Perfect. I'll send a PR.

About the side note, it's in the Linux directory, not the Windows one ;) Actually, everything that I said, applied to the Linux version.

**Comment by AlessandroZ** [comment]
I don't remember at all why I used modulesToLaunch. I don't use it anymore, so I removed it. Thanks

**Comment by m41nt41n3r** [comment]
This fix may be applied to windows version, isn't it?

**Comment by AlessandroZ** [comment]
It has already been applied to all versions (Windows, Linux and Mac)
