### ISSUE TITLE
JSON format stores multi-line string for SSH keys

### ISSUE THREAD

**Issue by newlog** [AlessandroZ/LaZagne#226]
Hi again,

I saw that when an SSH key is found, when saved in JSON format to a file, the SSH key is written as a multi-line string. JSON format does not support multi-line strings, thus failing when trying to load that data with the Python json module.

More info can be found here:

- https://stackoverflow.com/questions/16690101/can-a-json-value-contain-a-multiline-string

Problematic output example:

```
"Passwords": [
            [
                {
                    "Category": "Ssh"
                },
                [
                    {
                        "KEY": "-----BEGIN RSA PRIVATE KEY-----
<string>
<string>
<string>
```

If a json.load() is executed upon that data, it will fail, rendering the feature of storing data as json kind of useless.

**Comment by newlog** [comment]
Also, there's another problem with the generated json data.

With firefox passwords the following entry is generated:

`"Password": "{"version":1,"accountData":{"<data1>":"<data2>","<data3>":"<data4>"}}",`

The double quote enclosing the dictionary inside "Password", also makes the Python `json.load()` fail. If those are removed, the json is properly loaded. Example:

`"Password": {"version":1,"accountData":{"<data1>":"<data2>","<data3>":"<data4>"}},`

**Comment by AlessandroZ** [comment]
I have added a link to this issue on the Readme. Thanks for your help.
