### ISSUE TITLE
Some kind of regression with Wifi passwords

### ISSUE THREAD

**Issue by alxchk** [AlessandroZ/LaZagne#228]
I didn't spent much time to find out the way to reproduce previous behaivour, but now for 1 PC (Windows 7 x64) I can't derive Wifi Password (older versions did work, sure 100500%).

I see two problems.
1. netsh method. In some cases subprocess.*.communicate will not work if stdin is not PIPE. So, please, specify PIPE there
2. DPAPI doesn't work for me either. I do have KEY blob, but looks like "class Decrypt_DPAPI" umkp is not initialized. I run with account "All users" :)

**Comment by AlessandroZ** [comment]
I have changed lot of things, I hope this issue is corrected. I have never managed to reproduce it. 
However, it should be more stable now.
