### ISSUE TITLE
Compiled Build error

### ISSUE THREAD

**Issue by bkr32** [AlessandroZ/LaZagne#230]
Hi, i built lazagne from source using this guide https://github.com/AlessandroZ/LaZagne/wiki/How-to-compile
however on running the program i get `Program 'laZagne.exe' failed to run: The specified executable is not a valid application for this
OS platform`
thanks

**Comment by AlessandroZ** [comment]
Try to compile the tool again, it should be easier now that the pycrypto lib has been removed.
