### ISSUE TITLE
Run LaZagne Browsers through Meterpreter session ?!

### ISSUE THREAD

**Issue by user2618** [AlessandroZ/LaZagne#233]
hi, is the way to run windows script of LaZagne in local machine (Kali linux) after get meterpreter session for grab browser pass on to the target machine (Windows) ? i try to do this after installing the program by using python_import in meterpreter session and nothing happen ? plz help 

meterpreter > load python 
Loading extension python...Success.
meterpreter > python_import -f /root/Desktop/LaZagne/Windows/laZagne.py
[*] Importing /root/Desktop/LaZagne/Windows/laZagne.py ...
[+] Command executed without returning a result
meterpreter >

**Comment by m41nt41n3r** [comment]
There are too much dependencies to run lazagne as is.

**Comment by AlessandroZ** [comment]
Sorry, @m41nt41n3r has right, if you can install python dependencies using meterpreter you should be able to use Lazagne. Otherwise, no.
