### ISSUE TITLE
freeze when run through wifi module

### ISSUE THREAD

**Issue by u4113057** [AlessandroZ/LaZagne#234]
![bug](https://user-images.githubusercontent.com/33534198/40411565-0a30a44c-5e9b-11e8-826c-973517c0b78d.png)

freeze when run through wifi module. just stop right there and didnt process the rest of the module or write log file

**Comment by u4113057** [comment]
![bug2](https://user-images.githubusercontent.com/33534198/40470846-e7394b32-5f5e-11e8-8f7e-9032a2345fcf.jpg)

**Comment by AlessandroZ** [comment]
Try the last version please, and open it again if you still have errors.
