### ISSUE TITLE
Dumping pageant keys

### ISSUE THREAD

**Issue by DiabloHorn** [AlessandroZ/LaZagne#236]
Hi,

What would be the best approach to integrate this:

https://github.com/DiabloHorn/pageant_xkeys

It only needs a memory dump, so would integrating memorydump capabilities into lazagne be a requirement?

**Comment by AlessandroZ** [comment]
Another thing, I saw that you use construct on your code. This lib has changed a lot, so I had to fix the version in the requirement https://github.com/AlessandroZ/LaZagne/blob/f9dc346dd55d644a0ac94f5b8e27be4aa281e637/Windows/requirement.txt#L1
So please, respect this version or we will have conflict between them. 

Check some examples [here](https://github.com/AlessandroZ/LaZagne/blob/c6e72c22edcfb9077e299adb5bcb67a3828f7af9/Windows/lazagne/config/DPAPI/structures.py) and [here](https://github.com/AlessandroZ/LaZagne/blob/f9dc346dd55d644a0ac94f5b8e27be4aa281e637/Windows/lazagne/softwares/windows/mimikatz.py)

**Comment by DiabloHorn** [comment]
Hi,

Do you mean that you prefer for the code to be rewritten to read directly from memory instead of first dumping the process memory to a file? 

Yeah the construct code is an external library I used, I would have to check if I can easily update to this to match your version.

Cheers,
DH

**Comment by AlessandroZ** [comment]
No I don't ask you to rewrite your code. It was just to let your know how I used the memorpy lib but if you find a way to do a process dump using it, it would be nice, otherwise, maybe some other tools exists (but try to not use big libs or embedded exe). 
Thanks.

**Comment by AlessandroZ** [comment]
Other thing, I saw that [you use](https://github.com/DiabloHorn/pageant_xkeys/blob/master/pageant_xkeys.py#L38) the Pycrypto library. I have lots of problems with this lib (for compatibility with old hosts, etc.) so I have decided to remove it. Right now, I don't have time to do it but when I can, I will do it. So if you could find another way in pure python to implement RSA and DSA, it would help me. 

Thanks a lot.

**Comment by DiabloHorn** [comment]
hmmm I understand. I'll investigate to see what is possible. Replacing pycrypto with custom implementation is like a huge job :( there are some online versions with pure rsa/dsa implementations:

https://github.com/sybrenstuvel/python-rsa
https://github.com/rrottmann/pydsa

Just not sure if they are safe to use. Writing a custom crypto implementation is like really really difficult.

**Comment by AlessandroZ** [comment]
Sorry, I know that using pycrypto would be more easy to integrate your module. I fight to remove it. If you find a way to do it without it, I will be hapy to merge your PR. 
Have a nice day.
