### ISSUE TITLE
Message printed in quiet mode

### ISSUE THREAD

**Issue by eranzim** [AlessandroZ/LaZagne#238]
When constant.st.print_output is called (e.g. from run_module) and no password was found, logging.info is called without checking the value of quiet_mode (Windows\\...\write_output.py:238), so even though I passed the -quiet flag, I still get "[!] No passwords found" logs.

**Comment by eranzim** [comment]
I found another place where printing is happening regardless of the quiet setting. In Windows\laZagne.py, in run_module, in the except clause, there is a call to `traceback.print_exc()` and then `print`, both should be only if -quiet is not provided IMO

**Comment by AlessandroZ** [comment]
Thanks, you are right, I will take care of that soon.

**Comment by AlessandroZ** [comment]
You had this error because you used the verbose mode (-v) with the quiet mode at the same time. 
That's why I never noticed this output. It should be fixed now.
