### ISSUE TITLE
Feature request: allow setting log severities

### ISSUE THREAD

**Issue by eranzim** [AlessandroZ/LaZagne#239]
Allow setting (e.g. in constant.constant) the severity with which log messages will be written (and then use .log() instead of .info(), etc.)
This could be helpful for me, because I want to run LaZagne as part of a larger project, and I try to minimize the number of INFO log messages, only "really important" messages are INFO rather than DEBUG. It would be nice to get data (logs) from LaZagne, but I would like the option to get them as DEBUG instead.

Thanks :)

**Comment by AlessandroZ** [comment]
I'm not sure to understand your problem, for me log severities is already managed [here](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/laZagne.py#L79).

**Comment by eranzim** [comment]
It's not about which logs I want to see (which is the verbosity code you pointed to), but rather which severity I want them to have.
My code also uses the `logging` module, so I'm getting log messages from many places. I would like to be able to control the logs from LaZagne - to still receive them, but as debug rather than info.
There is no need for this to reflect in the CLI flags, just in the code itself, because it's meaningless to change if you're just running LaZagne from the command line.
The way I would've probably done it is by adding a field to constant.constant named `info_severity` (or something similar) having a default value of `logging.INFO`, then instead of calling `logging.info(xyz)` you would call `logging.log(constant.info_severity, xyz)`.
Then, in my code, I could overwrite `constant.info_severity` with `logging.DEBUG` before calling `runLaZagne`.

**Comment by AlessandroZ** [comment]
Hi,
I close the issue because it is really specific to your tool and I cannot have time to spend on it. However, if you want to do a PR to add it, you're welcome. 

Have a nice day.
