### ISSUE TITLE
runLaZagne runs many times for each sid

### ISSUE THREAD

**Issue by eranzim** [AlessandroZ/LaZagne#241]
I reproduced this when running LaZagne as local system account, 64-bit. `list_sids()` returns a record for (almost) each process in the system, and then inside `impersonateUsers[user]` there are many duplicates (it is essentially a list with the same sid string again and again, many times).
After populating `impersonateUsers`, it is essential to remove duplicates from those lists.

**Comment by AlessandroZ** [comment]
Should be fixed now: https://github.com/AlessandroZ/LaZagne/blob/master/Windows/laZagne.py#L297
