### ISSUE TITLE
Non-ASCII characters in passwords cause UnicodeDecodeError

### ISSUE THREAD

**Issue by eranzim** [AlessandroZ/LaZagne#242]
I have a password with non-ascii characters (for example \xc1) stored on my computer, and decoding it to ascii (which happens implicitly when encode is called) raises an exception. Here is the traceback:

```
Traceback (most recent call last):
    File "...\contrib\LaZagne\Windows\laZagne.py", line 312, in runLaZagne
      for r in runModule(category_choosed, registry_used=False):
    File "...\contrib\LaZagne\Windows\laZagne.py", line 176, in runModule
      constant.dpapi.check_credentials(constant.passwordFound)
    File "...\contrib\LaZagne\Windows\lazagne\config\dpapi_structure.py", line 67, in check_credentials
      for r in self.umkp.try_credential(sid=self.sid, password=password):
    File "...\contrib\LaZagne\Windows\lazagne\config\DPAPI\masterkey.py", line 268, in try_credential
      self.credhists[sid].decrypt_with_password(password)
    File "...\contrib\LaZagne\Windows\lazagne\config\DPAPI\credhist.py", line 66, in decrypt_with_password
      self.decrypt_with_hash(hashlib.sha1(password.encode("UTF-16LE")).digest())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 0: ordinal not in range(128)
```

**Comment by ingested** [comment]
Can you provide more details?

- What Windows version are you using
- What is your system locale and interface language (this should not be relevant but just in case)
- Which module caused this error
- Which of your applications contains non-ascii characters

**Comment by ingested** [comment]
@eranzim Can you confirm this PR #254 fixed your error? Can you pull the latest version and test it again?

**Comment by eranzim** [comment]
Tested it with the chrome flow, works now. If it pops up again in another flow I'll let you know. Thanks!

On a side note, thanks for all the fixes and contributions! It's also nice to see you "PEP8" the files, makes it easier to read and debug it (please continue with other files as well 😃 ). Kudos!

**Comment by eranzim** [comment]
@ingested 
Actually, I see that when I run it from the command line (as a blackbox), I get "[-] Password not found !!!" for the direct WiFi, however I can see a binary password if I call LaZagne's functions (runModule) directly. Is this behavior on purpose or should I open another issue for it?
