### ISSUE TITLE
global name 'passwords' is not defined.

### ISSUE THREAD

**Issue by negru555** [AlessandroZ/LaZagne#243]
I am getting this error(global name 'passwords' is not defined) on 64 bits then I do not run it with admin rights.
But using the 32 bits exe does give me this error even if I run it with admin rights... Why?
This is how I start it:
laZagne_x86.exe all -quiet -oN

**Comment by AlessandroZ** [comment]
Hi, 

Without more information, I cannot check your error message. I need as stracktrace, to know where the error occurs, etc.

**Comment by AlessandroZ** [comment]
Reopen the issue if you have more information... Thanks
