### ISSUE TITLE
Leftover temp files

### ISSUE THREAD

**Issue by eranzim** [AlessandroZ/LaZagne#246]
Several temp files are created in windows' temp folders when the code is run (probably created with the tempfile python module), containing registry saves of Security, SAM and SYSTEM (or so it seems). I think they might be originating from (at least) the Hashdump and WiFi modules, but I'm not completely sure.
These files should be properly cleaned up after they're no longer needed (e.g. in a finally block).
This is especially bothersome to me, since it creates about 25MB per run, and I'm running it a **lot** of times, and so I find myself needing to manually delete dozens of files weighing hundreds of MBs every few days.

Thanks!

**Comment by AlessandroZ** [comment]
This one will be completely fixed when #258 will be fixed
