### ISSUE TITLE
config\dpapi_structure.py::Decrypt_DPAPI.check_credentials runs on duplicate passwords

### ISSUE THREAD

**Issue by eranzim** [AlessandroZ/LaZagne#255]
I ran the code (with "all -v" params) from PyCharm running as system, and it seemed like it entered an infinite loop. When I paused it, I saw a few things:

1. The `passwords` list in check_credentials contains duplicate passwords
1. Every few iterations, we reach this loop again and the passwords list gets longer (with more repetitions in it)

I'm thinking there's something updating `constant.passwordFound` while we loop, and since we loop on that list (it is passed by reference) - we get an infinite loop.

**Comment by AlessandroZ** [comment]
I have done some tests but I cannot reproduce the error. I already do a check to not add duplicate values. Please use the verbose mode (-vv) to be sure that these values are duplicated. Thanks.
