### ISSUE TITLE
Add some automated testing?

### ISSUE THREAD

**Issue by cclauss** [AlessandroZ/LaZagne#262]
Is it time to add some automated testing like Travis CI, Circle CI, Appveyor, etc.? https://github.com/marketplace/category/continuous-integration

**Comment by AlessandroZ** [comment]
I agree, I should take a look on it, to see how it works.

**Comment by AlessandroZ** [comment]
I wanted to do it, but the problem will concern Windows and Mac OS. It's complicated to test it from a docker environment. So I close this issue.
