### ISSUE TITLE
Wont save passwords as txt

### ISSUE THREAD

**Issue by Maybegus** [AlessandroZ/LaZagne#264]
When i run lazagne to save passwords a
[credentials_25082018_232624.txt](https://github.com/AlessandroZ/LaZagne/files/2321266/credentials_25082018_232624.txt)
s txt it will create a file but the file only says this

**Comment by AlessandroZ** [comment]
try the last version please and if you have some problems, give me more information (module lanunch, output with -vv, etc.).
