### ISSUE TITLE
pypykatz

### ISSUE THREAD

**Issue by alround** [AlessandroZ/LaZagne#267]
pypykatz
Runs on all OS's which support python>=3.6
how can i installer it with python2.7
use pip installer https://github.com/AlessandroZ/pypykatz/archive/master.zip ?
but i have try it and it can't worked

**Comment by AlessandroZ** [comment]
It should work, my fork is compatible with python 2.7: https://github.com/AlessandroZ/pypykatz/blob/master/setup.py#L30

Could you give me the output of the error please ? 
Try `pip install https://github.com/AlessandroZ/pypykatz/archive/master.zip ` and give me the output

If it fails, try this and give me the output: 
```
git clone https://github.com/AlessandroZ/pypykatz
cd pypykatz
python setup.py install 
```
Thanks
