### ISSUE TITLE
Error in Skype passwords

### ISSUE THREAD

**Issue by eranzim** [AlessandroZ/LaZagne#269]
When running with `chats -vvv`, I see the following in the output:
```
 ------------------- Skype passwords -----------------

[!] 'utf8' codec can't decode byte 0x9a in position 2: invalid start byte
[-] The salt has not been retrieved
[!] No passwords found
```
Another encoding issue?

**Comment by eranzim** [comment]
That was with 32-bit python. When I run the same with 64-bit python, I get this instead:
```
 ------------------- Skype passwords -----------------

[!] [Error 2] The system cannot find the file specified
[-] The salt has not been retrieved
[!] No passwords found
```

**Comment by AlessandroZ** [comment]
This is not an error, the registry key has not be found: https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/chats/skype.py#L34

**Comment by eranzim** [comment]
@AlessandroZ So shouldn't it be 'file not found' also in 32-bit?
