### ISSUE TITLE
DPAPI bug

### ISSUE THREAD

**Issue by KiUserExceptionDispatcher** [AlessandroZ/LaZagne#270]
Hi.
Traceback:

>   File "\lazagne\config\dpapi_structure.py", line 94, in check_credentials
>   File "\lazagne\config\DPAPI\masterkey.py", line 359, in try_credential
>   File "\lazagne\config\DPAPI\masterkey.py", line 68, in decrypt_with_password
>   File "\lazagne\config\DPAPI\masterkey.py", line 55, in decrypt_with_hash
>   File "\lazagne\config\DPAPI\masterkey.py", line 83, in decrypt_with_key
>   File "\lazagne\config\DPAPI\crypto.py", line 342, in dataDecrypt
> AttributeError: type object 'triple_des' has no attribute 'new'

The error line is:
>         cipher = cipherAlgo.module.new(key, CBC, iv)
Is it a bug? I don't see any "new" in pyDes as in hmac for example:

> >>> hmac.new
> <function new at 0x035F3AF0>

**Comment by AlessandroZ** [comment]
Thanks for your issue, it should be fixed now. Open the issue again, if you still have errors. Thanks
