### ISSUE TITLE
Version 2.4 finds 4 passwords, version 2.3.2 finds 9 passwords

### ISSUE THREAD

**Issue by billybob3** [AlessandroZ/LaZagne#272]
I'm running Windows 10 Pro 64-bit fully patched (Version 1803, OS Build 17134.228).  LaZagne 2.4 (LaZagne all) finds 4 passwords in 55 seconds and 2.3.2 finds 9 passwords in 33 seconds. 2.3.2 finds 8 Chrome passwords and 1 Microsoft Edge (Internet Explorer) password.  2.4 finds only 4 Chrome passwords.

**Comment by billybob3** [comment]
Alessandro,

Yes, you are correct.  4 passwords are unique and 4 passwords are duplicates.

The time duration to run both versions on my second test are: version 2.4 is 43 seconds and version 2.3.2 is 28 seconds.  


Here is the Vault module on version 2.3.2:

C:\Users\Admin\Desktop>LaZagne windows -vault -vvv

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

########## User: Admin ##########

 ------------------- Vault passwords -----------------

[+] Password found !!!
URL: https://www.linkedin.com/
Login: xxxxxxxxx@gmail.com
Password: xxxxxxxxxxxxxxxx
Name: Internet Explorer

[-] Password not found !!!
URL: MicrosoftAccount:target=SSO_POP_Device
Login: 02elfplpqzzj

[-] Password not found !!!
URL: Domain:target=xxxxxxx
Login: xxxxxx\HomeGroupUser$


[+] 1 passwords have been found.

elapsed time = 0.0309998989105

————————————————-

Here is the Vault module on version 2.4:

C:\Users\Admin\Desktop>laZagne.exe windows -vault -vvv

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

########## User: Admin ##########

[-] Admin not ok for masterkey 5306acd9-f1f9-420f-93cf-e46e496e8315
[-] Admin not ok for masterkey abd844e1-2112-4d7e-ad3d-a08143d61390
[-] Admin not ok for masterkey 83e73bae-7589-4bc8-8cb1-04d0c0b01061
[-] Admin not ok for masterkey 38a6ae89-f99b-420e-9385-9fa2f8ad861e
[-] Admin not ok for masterkey 48479385-e093-4752-a257-9b865f8e905c
[-] Admin not ok for masterkey ba5e8268-01cd-452b-b7c0-4cb2603e5d5a
[-] Admin not ok for masterkey 0e363156-ee57-4493-92ee-5116d3c87e6a
[-] Admin not ok for masterkey 99cc0c68-53c9-4e21-85e0-62a4c60eacd4
[-] Admin not ok for masterkey a9f0567d-34eb-4dd8-a2f5-6aa0f9c586b2

[+] 0 passwords have been found.

elapsed time = 7.90600013733

**Comment by KiUserExceptionDispatcher** [comment]
> Try again the last python code please 
You could add a git revision number/some other counter into startup banner to know surely what version used.

**Comment by AlessandroZ** [comment]
You mean, updating the version [variable ](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/config/constant.py#L18) after each commit ?

**Comment by KiUserExceptionDispatcher** [comment]
Yep, it may be useful for debug I think.

**Comment by AlessandroZ** [comment]
I will try to do it. Hope to not forget.
