### ISSUE TITLE
TypeError: 'bool' object is not iterable

### ISSUE THREAD

**Issue by Banaanhangwagen** [AlessandroZ/LaZagne#278]
Latest lazagne.py version gives this error (printed 50 times), but only when executing it in admin-cmd

`[!] Traceback (most recent call last):
  File "xxx\LaZagne-master\Windows\lazagne\config\change_privileges.py", line 95, in list_sids
    token_sid, owner = get_token_info(hToken)
TypeError: 'bool' object is not iterable`

**Comment by KiUserExceptionDispatcher** [comment]
https://github.com/AlessandroZ/LaZagne/pull/280

**Comment by AlessandroZ** [comment]
Should be fixed thanks to @KiUserExceptionDispatcher. If you still have problems, open the issue again. Thanks !
