### ISSUE TITLE
Erreur d'historique sur IE11

### ISSUE THREAD

**Issue by EmmanuelBeziat** [AlessandroZ/LaZagne#28]
Salut à toi,

Je suis tombé sur cette erreur : 

```winbatch
C:\User\moi\AppData\Local\Temp\_MEI11562\softwares\browsers\ie.py:210: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
[ERROR] Browser history has failed to load, only few url will be tried

[!] No passwords found

[INFO] No credentials stored in the IE browser.

[+] 0 passwords have been found.

elapsed time = 0.156999826431
```

J'ai cru comprendre que la partie du *credential* était relative au réglages du navigateur ; y a-t-il quelque chose à faire ? Est-ce que l'erreur Unicode est liée au fait qu'il ne trouve rien dans l'historique (et par extension, qu'il ne trouve aucun mot de passe) ?

Sur trois PC testé, un seul a eu ce problème. Windows 8.1 / IE11, système en français.

Merci !

**Comment by AlessandroZ** [comment]
Salut, 

Je vais regarder l'erreur de plus près quand j'aurai un peu de temps. Mais pour ton usage c'est pas vraiment une erreur car les mots de passe sous IE 11 (à partir de win8) sont sauvegardés dans le credential manager et non plus en base de registre. Donc plus besoin de récupérer l'historique de navigation. 
En revanche, LaZagne ne prend pas en charge le credential manager sous win8 donc les mots de passe de peuvent pas être récupérés en utilisant cette technique. Tu peux utiliser mimikatz qui le fait très bien si tu veux vraiment trouver ces mots de passe. 

Bonne journée.
