### ISSUE TITLE
Windows Defender Virus HackTool:Win32

### ISSUE THREAD

**Issue by Tox86** [AlessandroZ/LaZagne#284]
Hello, i just discovery your program and downloaded, but Defender say is a virus.
![lazagnevirus](https://user-images.githubusercontent.com/7013508/45906013-f8cb9300-bdc8-11e8-9dcb-296a3905be2a.png)
Addio.

**Comment by KiUserExceptionDispatcher** [comment]
It's ok.

**Comment by AlessandroZ** [comment]
The source code is opened, do not hesitate to do a code review to be sure it's not a virus, and compile it yourself. :)
