### ISSUE TITLE
Python 2.7 related performance tip

### ISSUE THREAD

**Issue by KiUserExceptionDispatcher** [AlessandroZ/LaZagne#290]
Hello.
There are lots of "for x in range(y)" calls in LaZagne. Most of them should be replaced with xrange because "range" allocates y*z bytes of memory (so much and so slow if y is big). For example top hardware makes range(10000000) in ~0.15s :)
```
>python -m timeit range(10000000)
10 loops, best of 3: 140 msec per loop
```

**Comment by AlessandroZ** [comment]
You're right, I have removed some xrange when trying to be compatible with python 3. 
I should have done something like that to keep the compatibility: 
```
try:
   xrange
except ImportError:
  xrange = range
```

**Comment by KiUserExceptionDispatcher** [comment]
Sometimes "range" is needed, for example:

```
def rc4_crypt(data, key):
    x = 0
    box = range(256)

    for i in xrange(256):
        box[i] ^= ord(key[i % len(key)])
```
