### ISSUE TITLE
Run command args on launch

### ISSUE THREAD

**Issue by SpeedBird95** [AlessandroZ/LaZagne#294]
Hi , 

I am new to python and was wondering where the entry point for parsing arguments is.
I would like to run lazagne with 'all -oN' by defualt when launched..

Any help is much appreciated

**Comment by SpeedBird95** [comment]
I have fingured out to default to -oN on line 128
PWrite.add_argument('-oN', dest='write_normal', action='store_true', default='-oN',

Just need some help to default on launch to 'all' argument.

**Comment by SpeedBird95** [comment]
It's very hard for me to explicitly add 'all' because argparse wont allow no arguments

**Comment by AlessandroZ** [comment]
Here is it: https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/config/run.py#L132
