### ISSUE TITLE
Lasagne won't run

### ISSUE THREAD

**Issue by goldpill** [AlessandroZ/LaZagne#296]
<img width="571" alt="screen shot 2018-09-30 at 5 13 18 pm" src="https://user-images.githubusercontent.com/43064543/46264718-a1b67400-c4d4-11e8-8bac-12b97e3d5c90.png">

This is a screenshot of me trying to run it from the python file and it won't work. It won't run when compiled as an executable, so, I thought to try this and it's the same.

**Comment by AlessandroZ** [comment]
Use python 2.7.
