### ISSUE TITLE
laZagne won't run

### ISSUE THREAD

**Issue by goldpill** [AlessandroZ/LaZagne#297]
![virtualbox_windows10_01_10_2018_04_23_36](https://user-images.githubusercontent.com/43064543/46285971-3d2a0200-c532-11e8-9258-42787ec73803.png)

I just used python 2.7 and got this error message.

**Comment by AlessandroZ** [comment]
This is weird, does the python version work ? Sometimes, AV remove well known files containing signatures as lazagne.py, maybe write_output.py as well. Try to test with the python version and disable AV. When it will work, the exe should work as well.

**Comment by KiUserExceptionDispatcher** [comment]
May be it's a good idea to check [python version](https://docs.python.org/3/library/sys.html#sys.version)at the beginning of laZagne.py

**Comment by goldpill** [comment]
I just tried starting it with python and it gives the same error, I have all AV switched off too.

**Comment by goldpill** [comment]
The files being downloaded are incomplete, even with AV off.
