### ISSUE TITLE
LaZange - error

### ISSUE THREAD

**Issue by Salaratron** [AlessandroZ/LaZagne#303]
E:\>LaZagne.exe all

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

Traceback (most recent call last):
  File "laZagne.py", line 234, in <module>
  File "laZagne.py", line 87, in runLaZagne
  File "lazagne\config\run.py", line 197, in run_lazagne
  File "lazagne\config\users.py", line 57, in set_env_variables
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 0: ordinal not in range(128)
[7252] Failed to execute script laZagne

wtf?

**Comment by vitos4chitos** [comment]
I have same problem

**Comment by AlessandroZ** [comment]
I close this issue because I have another one opened [here](https://github.com/AlessandroZ/LaZagne/issues/304). Please refer to this issue to find a solution and comment there if needed. Thanks.
