### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by vitos4chitos** [AlessandroZ/LaZagne#304]
Hi
Can you help me?
![1](https://user-images.githubusercontent.com/43905444/46571587-21828980-c980-11e8-9d64-d3c75086e1b2.png)

**Comment by AlessandroZ** [comment]
Try the last python version, not the release and say me if it works.

**Comment by vitos4chitos** [comment]
> Try the last python version, not the release and say me if it works.

Do I need to do this in Python 2.7 or not?

**Comment by AlessandroZ** [comment]
You need python 2.7. Install all dependencies from [requirements](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/requirement.txt) with pip and you should run it using the last repository.

**Comment by Teamate1703** [comment]
> 
> 
> You need python 2.7. Install all dependencies from [requirements](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/requirement.txt) with pip and you should run it using the last repository.

How to use it to install pypykatx master?

**Comment by Teamate1703** [comment]
I dont understand

**Comment by AlessandroZ** [comment]
To install dependencies, you should use pip. On Windows, it should be located on `C:\Python27\Scripts` and then run: 
`pip.exe install -r requirements.txt`

Then you will be able to run lazagne: 
`C:\Python27\python.exe lazagne.py all`

**Comment by Roodnik** [comment]
> Чтобы установить зависимости, вы должны использовать pip. В Windows он должен быть расположен `C:\Python27\Scripts`и запускаться:
> `pip.exe install -r requirements.txt`
> 
> Тогда вы сможете запустить lazagne:
> `C:\Python27\python.exe lazagne.py all`

hi, i from russia, and i have question. how to install requirements?

**Comment by Roodnik** [comment]
![image](https://user-images.githubusercontent.com/45007866/48524980-2eaa6680-e8a4-11e8-9017-75d5829d6dcf.png)
this?

**Comment by torerobo** [comment]
Hey. Similar error.
The problem is that in python 2.7 for windows there is no option "-r"
Tell me how to install dependencies?
![1](https://user-images.githubusercontent.com/35532898/48614152-a52b8f00-e99e-11e8-9b5e-34c5118cf0bb.jpg)
@AlessandroZ

**Comment by pretech86** [comment]
thanks for your effort but i have the following error 

C:\Python27\Scripts>python.exe laZagne.py all
Traceback (most recent call last):
  File "laZagne.py", line 19, in <module>
    from lazagne.config.manage_modules import get_categories
  File "C:\Python27\Scripts\lazagne\config\manage_modules.py", line 48, in <module>
    from lazagne.softwares.sysadmin.vnc import Vnc
  File "C:\Python27\Scripts\lazagne\softwares\sysadmin\vnc.py", line 3, in <module>
    import d3des as d
ModuleNotFoundError: No module named 'd3des'

**Comment by plonibarploni** [comment]
@pretech86 If you're having a different issue, please open a separate issue for it. It looks like you haven't installed the dependencies from requirements.txt
