### ISSUE TITLE
Binary file won't run after compilation

### ISSUE THREAD

**Issue by T1MOXA** [AlessandroZ/LaZagne#305]
Hi.
I'm having trouble running your utility...

Precompiled binary file:
```
C:\LaZagne>lazagne.exe -version
Version 2.4
```

Binary file compiled by me:
```
Building EXE from EXE-00.toc completed successfully.
C:\LaZagne\Windows\dist>lazagne.exe -version
```

What could be wrong ?

**Comment by AlessandroZ** [comment]
try to install all dependencies and follow instruction from the wiki: https://github.com/AlessandroZ/LaZagne/wiki/How-to-compile

**Comment by T1MOXA** [comment]
I'm following the instructions and did everything.
The compilation went without problems, I think if I had not installed all the dependencies the code would not have compiled...

**Comment by AlessandroZ** [comment]
Run it using python first and when it works, try to compile it. Otherwise, it won't work.

**Comment by T1MOXA** [comment]
py -2.7 laZagne.py -version
Version 2.4.2

**Comment by T1MOXA** [comment]
What could be wrong ?
