### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by goldpill** [AlessandroZ/LaZagne#308]
<img width="870" alt="screen shot 2018-10-16 at 4 25 55 pm" src="https://user-images.githubusercontent.com/43064543/47053102-636db580-d160-11e8-81f6-397838952b61.png">

Can you tell me what I need to do in order to still use this version and have it run properly2.3.2? I noticed this not too long ago, even though it always ran properly until yesterday.

**Comment by AlessandroZ** [comment]
Use the last python version and not the release and put again your stacktrace If you're not up to date, I cannot help you. Sorry.
