### ISSUE TITLE
Standard output contains only hashdumps and LSA secrets.

### ISSUE THREAD

**Issue by patrickteivas** [AlessandroZ/LaZagne#312]
Running from cmd on desktop as administrator "laZagne.exe all -oA". Standard output contains only hashdumps and count of found passwords under LSA secrets category, but not passwords themselves. JSON format contains all found passwords. Without administrator privileges it`s working normally.

**Comment by KiUserExceptionDispatcher** [comment]
Need more information (OS, software installed, language, etc).

**Comment by torerobo** [comment]
> Running from cmd on desktop as administrator "laZagne.exe all -oA". Standard output contains only hashdumps and count of found passwords under LSA secrets category, but not passwords themselves. JSON format contains all found passwords. Without administrator privileges it`s working normally.

This is an old problem, no one wants to deal with it. Want to save a full report in .txt, use this
laZagne.exe all > file.txt

**Comment by AlessandroZ** [comment]
Should be fixed now. :+1:
