### ISSUE TITLE
laZagne is not compatible with the version of Windows you're running

### ISSUE THREAD

**Issue by xBlankx** [AlessandroZ/LaZagne#314]
I'm using windows 8.1(windows is not activated )my test machine, System type 32-bit Operating System, x64-based processor

**Comment by KiUserExceptionDispatcher** [comment]
Is it a windows message or python? Do u launch executable or script?

**Comment by xBlankx** [comment]
a windows message and I run it through the executable file.

**Comment by AlessandroZ** [comment]
On a 32 bits OS, you could not use a x64 bit executable. You should compile the tool for 32 bits.
