### ISSUE TITLE
about python3 support？

### ISSUE THREAD

**Issue by vevenlcf** [AlessandroZ/LaZagne#324]
this project is running in the py3‘s environment, will be reportting exception!!!!!

about ：
```
Traceback (most recent call last):
  File "D:/python3-test/laZagne.py", line 235, in <module>
    for r in runLaZagne(category_selected=category, subcategories=subcategories, password=args.get('password', None)):
  File "D:/python3-test/laZagne.py", line 87, in runLaZagne
    for pwd_dic in run_lazagne(category_selected=category_selected, subcategories=subcategories, password=password):
  File "D:\python3-test\lazagne\config\run.py", line 203, in run_lazagne
    for r in run_category(category_selected, subcategories):
  File "D:\python3-test\lazagne\config\run.py", line 119, in run_category
    constant.user_dpapi.check_credentials(constant.password_found)
  File "D:\python3-test\lazagne\config\dpapi_structure.py", line 68, in check_credentials
    for ok, r in self.umkp.try_credential(sid=self.sid, password=password):
  File "D:\python3-test\lazagne\config\DPAPI\masterkey.py", line 358, in try_credential
    mk.decrypt_with_password(sid, password)
  File "D:\python3-test\lazagne\config\DPAPI\masterkey.py", line 67, in decrypt_with_password
    self.decrypt_with_hash(sid=sid, pwdhash=hashlib.new(algo, pwd).digest())
  File "D:\python3-test\lazagne\config\DPAPI\masterkey.py", line 54, in decrypt_with_hash
    self.decrypt_with_key(crypto.derivePwdHash(pwdhash=pwdhash, sid=sid))
  File "D:\python3-test\lazagne\config\DPAPI\masterkey.py", line 82, in decrypt_with_key
    self.rounds)
  File "D:\python3-test\lazagne\config\DPAPI\crypto.py", line 333, in dataDecrypt
    derived = pbkdf2(encKey, iv, cipherAlgo.keyLength + cipherAlgo.ivLength, rounds, hname)
  File "D:\python3-test\lazagne\config\DPAPI\crypto.py", line 317, in pbkdf2
    buff += derived
TypeError: can only concatenate str (not "bytes") to str
```

could you solve this issue as soon as fast?

and, i will be want to write  the exe project with pyqt5 after this issue fixed！！and it's easy to do something on the windows‘s system！

**Comment by vevenlcf** [comment]
the last  version. and windows's enviroment!!!

**Comment by x011** [comment]
@vevenlcf 
You'll need to change several parts of `laZagne `in order to make it work (at 100%) in `py3`.
When you try to run `laZagne`,  several `encode` related errors popup. Those are easy to solve, for example, line `39` of [`wifi.py`](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/wifi/wifi.py) module needs to be changed from:

` for st in stdout.split('\n'):` 
  to:
 `for st in stdout.decode("UTF8").split('\n'):`

`FF`/`TB `SQLite errors (see below) are normal, due to either `laZagne's` searching `SQLite `database files in several paths which doesn't exist or the database structure is different.

```
# Different DB structure: Changes in fields name
[!] Profile path found: C:\Users\USER\AppData\Roaming\Mozilla\Firefox\Profiles/3l5szukx.default
[!] Traceback (most recent call last):
  File "mozilla.py", line 117, in get_key
    c.execute("SELECT item1,item2 FROM metadata WHERE id = 'password';")
sqlite3.OperationalError: no such table: metadata

# Different Versions: Change in file-names and paths 
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\USER\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles/8vj8u64x.dev-edition-default-461049959481\\key3.db'`
```

- I've been trying to make `laZagne `work on `python3 ` and at the moment _most_ of the errors are corrected, including file exporting, which never worked for me on `py3`.

- I also changed the modules  load **order**,  to one in which the _easiest_ passwords (I personally leave browsers for last) are tried first and least probable only after, as this will increase the number of passwords available to be used on later and more difficult attacks, i.e.:

```
[!] Master Password is used !
[!] 515 most used passwords !!! 
[!] Master password found: XXXXX
```

- I noticed that `py2/3` the modules are loaded in a different order, and if you choose `all `in `py3`, it starts with `FF `and it _skips_ some modules. 
- On `py2 ` , `FF ` module is only loaded later and `laZagne `doesn't skip any modules. I say _skip_, because no errors were reported, but also no passwords were dump, so I assume they were just skipped for some reason.

**Comment by byehack** [comment]
> this project is running in the py3‘s environment, will be reportting exception!!!!!
> 
> about ：
> 
> ```
> Traceback (most recent call last):
>   File "D:/python3-test/laZagne.py", line 235, in <module>
>     for r in runLaZagne(category_selected=category, subcategories=subcategories, password=args.get('password', None)):
>   File "D:/python3-test/laZagne.py", line 87, in runLaZagne
>     for pwd_dic in run_lazagne(category_selected=category_selected, subcategories=subcategories, password=password):
>   File "D:\python3-test\lazagne\config\run.py", line 203, in run_lazagne
>     for r in run_category(category_selected, subcategories):
>   File "D:\python3-test\lazagne\config\run.py", line 119, in run_category
>     constant.user_dpapi.check_credentials(constant.password_found)
>   File "D:\python3-test\lazagne\config\dpapi_structure.py", line 68, in check_credentials
>     for ok, r in self.umkp.try_credential(sid=self.sid, password=password):
>   File "D:\python3-test\lazagne\config\DPAPI\masterkey.py", line 358, in try_credential
>     mk.decrypt_with_password(sid, password)
>   File "D:\python3-test\lazagne\config\DPAPI\masterkey.py", line 67, in decrypt_with_password
>     self.decrypt_with_hash(sid=sid, pwdhash=hashlib.new(algo, pwd).digest())
>   File "D:\python3-test\lazagne\config\DPAPI\masterkey.py", line 54, in decrypt_with_hash
>     self.decrypt_with_key(crypto.derivePwdHash(pwdhash=pwdhash, sid=sid))
>   File "D:\python3-test\lazagne\config\DPAPI\masterkey.py", line 82, in decrypt_with_key
>     self.rounds)
>   File "D:\python3-test\lazagne\config\DPAPI\crypto.py", line 333, in dataDecrypt
>     derived = pbkdf2(encKey, iv, cipherAlgo.keyLength + cipherAlgo.ivLength, rounds, hname)
>   File "D:\python3-test\lazagne\config\DPAPI\crypto.py", line 317, in pbkdf2
>     buff += derived
> TypeError: can only concatenate str (not "bytes") to str
> ```
> could you solve this issue as soon as fast?
> 
> and, i will be want to write the exe project with pyqt5 after this issue fixed！！and it's easy to do something on the windows‘s system！



> @vevenlcf
> You'll need to change several parts of `laZagne` in order to make it work (at 100%) in `py3`.
> When you try to run `laZagne`, several `encode` related errors popup. This type of errors are easy to solve, for example, line `39` of [`wifi.py`](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/wifi/wifi.py) module needs to be changed from:
> 
> ` for st in stdout.split('\n'):`
> to:
> `for st in stdout.decode("UTF8").split('\n'):`
> 
> `FF`/`TB` SQLite errors (see below) are normal, due to either `laZagne's` searching `SQLite` database files in paths which doesn't exist or the database structure is different.
> 
> ```
> 
> [!] Profile path found: C:\Users\USER\AppData\Roaming\Mozilla\Firefox\Profiles/3l5szukx.default
> [!] Traceback (most recent call last):
>   File "mozilla.py", line 117, in get_key
>     c.execute("SELECT item1,item2 FROM metadata WHERE id = 'password';")
> sqlite3.OperationalError: no such table: metadata
> 
> `FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\USER\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles/8vj8u64x.dev-edition-default-461049959481\\key3.db'`
> ```
> * I've been trying to make `laZagne` 100% compatible with `py3 ` and at the moment _most_ of the errors are gone.  The project already contains several parts where `py2` and `py3` code is divided, but not  everything is covered yet.
> * I'm trying to fix the file exporting module, which never worked for me on `py3`. I'm parsing the output via [write_ouput.py](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/config/write_output.py) inside the `print_logging() `function. Please note than I'm not planning to build an `exe`, so using ` laZagne.exe all > file.txt`, isn't really an option.
> * I also changed the modules  load **order**,  to one in which the _easiest_ passwords are tried first and the least probable only after. I personally leave browsers for last. This change in module order, increased the number of passwords available to be used on the brute-force (BF) process of FF profiles, i.e.:
> 
> ```
> [!] Master Password is used !
> [!] 515 most used passwords !!! - We collected +15 passwords, from local wifi,messengers and several other modules **prior to FF module,** they will now be used to BF the FF profile password.
> [!] Master password found: XXXXX - Boom! One of the previously collected WIFI password matched the FF profile pwd...
> ```
> * I noticed that `py2/3` load the modules in different order, and if you choose `all` in `py3`, it starts with `FF` and _skips_ some modules. I say _skip_, because no errors were reported, but also no passwords were dumped, so I assume they were just skipped for some reason.
> * On `py2` , `laZagne` doesn't skip any modules, it starts with the `chats` module and `FF's` only loaded later on the stack.
> * `Creeddump7 `doesn't work  on `py3`. An error on `sk = (key.SubKeyLists[0]/["pointer", ["_CM_KEY_INDEX"]]).value`  in the `subkeys()` function of ` rawreg.py` which I couldn't fix.  It works well on `py2 ` with admin right.

**Comment by AlessandroZ** [comment]
Python 3 can now be used but some tests are still needed. If some can check what works and what not could help me. I have done it, for browsers, or windows DPAPI functions but I couldn't try every tools. 

Wifi should be tested as well. 

But the hard work has already been done.
