### ISSUE TITLE
laZagne 2.4 Dont run on windows

### ISSUE THREAD

**Issue by Sladkiyperec** [AlessandroZ/LaZagne#326]
Hi. I don't know why i cant run laZagne.exe. I have this in my cmd:
Traceback (most recent call last):
  File "laZagne.py", line 234, in <module>
  File "laZagne.py", line 87, in runLaZagne
  File "lazagne\config\run.py", line 197, in run_lazagne
  File "lazagne\config\users.py", line 57, in set_env_variables
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128)
[3848] Failed to execute script laZagne 
HOW I can fix it. I'm not pro in this sfere.
If i run cmd as administrator i have the same problem please HELP MEEEEEEEEEEEEEEEEE))

**Comment by Sladkiyperec** [comment]
Help PLease

**Comment by plonibarploni** [comment]
https://github.com/AlessandroZ/LaZagne/issues/304#issuecomment-427572087

**Comment by Sladkiyperec** [comment]
I installed pyan1 but i stil have error but antother
Traceback (most recent call last):
  File "laZagne.py", line 234, in <module>
    for r in runLaZagne(category_selected=category, subcategories=subcategories, password=args.get('password', None)):
  File "laZagne.py", line 87, in runLaZagne
    for pwd_dic in run_lazagne(category_selected=category_selected, subcategories=subcategories, password=password):
  File "lazagne\config\run.py", line 197, in run_lazagne
    set_env_variables(user=constant.username)
  File "lazagne\config\users.py", line 57, in set_env_variables
    constant.profile[env] = constant.profile[env].format(drive=constant.drive, user=user)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128)
[2300] Failed to execute script laZagne


HOW I CAN INSTALL enum34 ON WINDOWS

**Comment by torerobo** [comment]
The same error in Windows 10 Home.
Installed all the dependencies, but neither .py nor .exe does not work.
Everything is working on windows 7

**Comment by plonibarploni** [comment]
I don't have a Windows machine to compile/test on, so can you try this and let me know if it works? https://github.com/plonibarploni/LaZagne/releases/tag/2.4.1-alpha

Run it by typing `python laZagne.py` after extracting the archive.

**Comment by torerobo** [comment]
> I don't have a Windows machine to compile/test on, so can you try this and let me know if it works? https://github.com/plonibarploni/LaZagne/releases/tag/2.4.1-alpha
> 
> Run it by typing `python laZagne.py` after extracting the archive.

I checked, the patch fixed the error. Now it works on Windows 7 / 10Home. Can you compile all this in .exe? (so as not to carry around python2.7 and dependencies)

**Comment by plonibarploni** [comment]
> Can you compile all this in .exe? (so as not to carry around python2.7 and dependencies)

I would prefer to wait for @AlessandroZ to make a new release (with compiled binaries), but in the meantime here's this.

[laZagne.zip](https://github.com/AlessandroZ/LaZagne/files/2592396/laZagne.zip)

**Comment by Sladkiyperec** [comment]
I have launched exe format (lazagne.exe) found only hash and wifi passwords and at the end have the same trouble line 234........... .  After that i tried py format and i have this problem File "lazagne.py", line 12, in <module>
    import argparse
ImportError: No module named argparse

**Comment by Sladkiyperec** [comment]
And if i want to download your .py 2.4.1 alpha your link said me: This is not web page you are looking for..

**Comment by Sladkiyperec** [comment]
@plonibarploni  do you know how to help me?

**Comment by plonibarploni** [comment]
@Sladkiyperec I removed that link but [this](https://github.com/plonibarploni/LaZagne/archive/patch-1.zip) has the same files. If that doesn't work, try [this one](https://github.com/plonibarploni/LaZagne/archive/patch-3.zip) and let me know if it works.

**Comment by torerobo** [comment]
https://github.com/AlessandroZ/LaZagne/files/2592396/laZagne.zip 
I checked the compiled (.exe). It works on windows7 / 10 and finds all passwords.

**Comment by AlessandroZ** [comment]
@Sladkiyperec

**Comment by pen9un** [comment]
我遇到了同样的问题，并且解决了它，出问题的原因和Windows CMD窗口编码有关系，
我下载了原Python程序，并且执行它，提示和上面类似，我的报错文件是\Windows\lazagne\config\execute_cmd.py文件，打开它并增加以下代码即可：

I encountered the same problem and solved it. The reason for the problem was related to Windows CMD window coding.
I downloaded the original Python program and executed it. The prompt is similar to the above. My error file is \Windows\lazagne\config\execute_cmd.py file.

`
import sys

if sys.getdefaultencoding() != 'gbk': 
    reload(sys) 
    sys.setdefaultencoding('gbk') 
`

**Comment by AlessandroZ** [comment]
@pen9un, have you tried the last python code ? 
Because this [code](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/config/users.py#L55) should solve this issue. If you could test it, it could be great. Thanks

**Comment by eternity-007** [comment]
Hi. I don't know why i can’t run laZagne.py. I have this in my cmd:

C:\Users\Administrator\Desktop\LaZagne-master\Windows>python laZagne.py
Traceback (most recent call last):
  File "laZagne.py", line 19, in <module>
    from lazagne.config.manage_modules import get_categories
  File "C:\Users\Administrator\Desktop\LaZagne-master\Windows\lazagne\config\man
age_modules.py", line 59, in <module>
    from lazagne.softwares.windows.ppypykatz import Pypykatz
  File "C:\Users\Administrator\Desktop\LaZagne-master\Windows\lazagne\softwares\
windows\ppypykatz.py", line 10, in <module>
    from pypykatz.pypykatz import pypykatz
ImportError: No module named pypykatz.pypykatz

Please help me,thank you.

**Comment by pen9un** [comment]
@AlessandroZ This is the result of my confirmation after execution. It can be used.

**Comment by AlessandroZ** [comment]
Thanks
