### ISSUE TITLE
Opera TypeError

### ISSUE THREAD

**Issue by rolandstarke** [AlessandroZ/LaZagne#33]
TypeError: print_debug() takes exactly 2 arguments (1 given)
```python
	print_debug('No passwords stored\nThe database Login Data is not present.')
```
in https://github.com/AlessandroZ/LaZagne/blob/master/Windows/src/LaZagne/softwares/browsers/opera.py#L156

**Comment by AlessandroZ** [comment]
Thanks for your fix ;)
