### ISSUE TITLE
Creeddump7 -  unsupported operand type(s) for /: 'Primitive' and 'list'

### ISSUE THREAD

**Issue by x011** [AlessandroZ/LaZagne#330]
Hi there,

I've corrected most of LaZagne's errors on py3.6, but I couldn't make `Creeddump7` work. 
There's an error on `sk = (key.SubKeyLists[0]/["pointer", ["_CM_KEY_INDEX"]]).value` in the `subkeys()` function of [rawreg.py](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/windows/creddump7/win32/rawreg.py) which I couldn't fix. 

`unsupported operand type(s) for /: 'Primitive' and 'list`

Any idea how to fix this? 
Thank you.

**Comment by AlessandroZ** [comment]
Sorry, but I cannot help you, I don't have this answer. 
If you managed it to work, I would be happy to see your changes to support python3.

**Comment by eranzim** [comment]
It's possible this is a problem in creddump7, I believe it is designed for Python 2. If I were you, I would check if there's a Python3-compatible version that can substitute the current version (possibly also using it as a submodule or download it in pip requirements file).
Good luck :)

**Comment by byehack** [comment]
> It's possible this is a problem in creddump7, I believe it is designed for Python 2. If I were you, I would check if there's a Python3-compatible version that can substitute the current version (possibly also using it as a submodule or download it in pip requirements file).
> Good luck :)

i solve it in `python3 branch` of lazagne project.

**Comment by 0E800** [comment]
@byehack Well done.

I was playing with python-modernize and wasn't having luck. 
Google searching similar error brought up this.

Thank you for your contribution to the internet.

**Comment by AlessandroZ** [comment]
The code has been updated, the patch from @byehack fixed it.
