### ISSUE TITLE
LaZagne.exe is blocked on Chrome/Firefox

### ISSUE THREAD

**Issue by guionardo** [AlessandroZ/LaZagne#331]
The .exe is identified as a threat and blocked.

Well, this is open source software, but... is realy safe?

**Comment by plonibarploni** [comment]
Which anti-virus are you using? If you check on [virustotal](https://www.virustotal.com/#/file/c03ef8106c58c8980b7859e0a8ee2363d70e2b7f1346356127c826faf2c0caa3/detection), you'll see that most of them classify it as a PUA (potentially unwanted application) or a hacktool, which is what it is.

I you're unsure of it's safety, you can read the source code, and if you must have an exe, but don't trust the one provided, you can make your own exe by following the instructions in the [wiki](https://github.com/AlessandroZ/LaZagne/wiki/How-to-compile).

**Comment by dallaskappel** [comment]
i'm just lazy and used a vm to downlad it and told chrome to keep it anyway.

**Comment by 0rion5** [comment]
By the way when you use Github Desktop you could just get it that way and then compile it on your computer but make sure you have Defender or any other third party code eater turned off. or just do it from a linux box.
