### ISSUE TITLE
How to convert the laZagne.py to exe?

### ISSUE THREAD

**Issue by ciberstein** [AlessandroZ/LaZagne#335]
I used pyinstaller but the .exe file not work

**Comment by plonibarploni** [comment]
Did you follow the instructions in the [wiki](https://github.com/AlessandroZ/LaZagne/wiki/How-to-compile)?

**Comment by plonibarploni** [comment]
Follow the [**Windows**](https://github.com/AlessandroZ/LaZagne/wiki/How-to-compile#for-windows-only) instructions.
