### ISSUE TITLE
How to compile my own laZagne.exe script 

### ISSUE THREAD

**Issue by titusikn** [AlessandroZ/LaZagne#337]
Please I have followed the instructions on on wiki but it seems there is something I am not doing right. 
Please can you give me a step by step guide on how to compile my own laZagne script. 
Starting from cloning file repository or if there is any other thing I need to do before cloning file repository. 
Please...

**Comment by AlessandroZ** [comment]
Sorry but try to check older issues to find a way. I cannot help on this subject.
