### ISSUE TITLE
Unsupported 16-bit Application Error When compiling for windows.

### ISSUE THREAD

**Issue by notnavas** [AlessandroZ/LaZagne#338]
Hi,

I tried to compile laZagne in a linux system, i downloaded the last source code and then followed step by step the wiki, installed the requirements, and used the .spec (both, the one in the wiki and the one coming with the source code).
Then i tried the same with the source code of the last stand alone version. 
(When compining it, everything seems to be ok and there is no exceptions in both cases.)

Both exes gave me the same error when i tried to execute them on a 64bit windows machine: "Unsupported 16-bit Application Error, the exe is not compatible with 64 bit windows version."

I suppose something is wrong with my pthon or my pyinstaller, or i am missing some step on the installation, is there any more requirements for compiling it? 

Thanks for your help, and sorry for my english.

**Comment by plonibarploni** [comment]
You can't cross-compile for Windows on Linux.

**Comment by notnavas** [comment]
Thank you for your anwser, so, in order to compile the project into a .exe, i must do it in a windows machine?

**Comment by plonibarploni** [comment]
Yes.
