### ISSUE TITLE
Unncessary function?

### ISSUE THREAD

**Issue by plonibarploni** [AlessandroZ/LaZagne#342]
I'm playing around with python3 support, and while working on `Linux/lazagne/softwares/browsers/mozilla.py`, I noticed the following code, which if removed works just as well on both python2 & 3:
https://github.com/AlessandroZ/LaZagne/blob/4ecef7f4b02f5e3ee442f6504e1993a31778a995/Linux/lazagne/softwares/browsers/mozilla.py#L40-L44
I'm not 100% certain, but I wonder if it has anything to do with [this](https://www.python.org/dev/peps/pep-0237/). Can it be safely removed?

**Comment by AlessandroZ** [comment]
You were right, I have tested it and this function is not necessary so I have removed it: https://github.com/AlessandroZ/LaZagne/commit/c5dddb34ca781ba3f35c1a36877fcf78404f1b0e 

Thanks for your help :)
