### ISSUE TITLE
Incorrect detection of Firefox Master Password

### ISSUE THREAD

**Issue by plonibarploni** [AlessandroZ/LaZagne#343]
Using the Linux version of LaZagne, when running in verbose mode (`-v`), I see the following:
> ```
> [!] Master Password is used !
> [!] 509 most used passwords !!! 
> [!] No password has been found using the default list
> ```
However, I don't have a master password set - there must be an issue with how it determines whether the master password is set.

**Comment by AlessandroZ** [comment]
Hmm this is weird, I cannot reproduce the problem. What version of firefox you use ?

**Comment by plonibarploni** [comment]
The latest, 65.0+build2-0ubuntu0.18.04.1

**Comment by AlessandroZ** [comment]
I cannot reproduce this error as well. If you could try to understand what's the problem it could be great. 
It's not a real problem, if no passwords are stored (even if I agree that the output message is wrong). 
Try to add some passwords in firefox to check if the error message prints again.

**Comment by plonibarploni** [comment]
It outputs the passwords correctly, it's just an odd error in how it detects it.

**Comment by AlessandroZ** [comment]
When the database is empty, the master password is not tested anymore.

**Comment by plonibarploni** [comment]
I still get it. I noticed that when running it with `-vv` it outputs some key as well, but I don't know what that's from:
```
[!] Profile path found: /home/plonibarploni/.mozilla/firefox/kbqre7jv.default
[!] key: '1=\xe0\xe5\xd0pm\x1a\xb5\xc1\xf4\xe6&\x91n\x13\x89\xdc\xb6\x01vz\xf1a\x08\x08\x08\x08\x08\x08\x08\x08'
[!] Master Password is used !
[!] 500 most used passwords !!! 
[!] No password has been found using the default list
[+] Password found !!!
URL: <redacted>
Login: <redacted>
Password: <redacted>

[+] Password found !!!
URL: <redacted>
Login: <redacted>
Password: <redacted>
```
