### ISSUE TITLE
Claws-mail no longer supported

### ISSUE THREAD

**Issue by plonibarploni** [AlessandroZ/LaZagne#347]
Due to changes in the way Claws-mail stores its passwords (as of [v3.14.0](https://www.claws-mail.org/NEWS), released 7 August 2016 - see [here](https://git.claws-mail.org/?p=claws.git;a=blob;f=doc/src/password_encryption.txt;h=50873dc35466ba8e423b82f00c1a168f6954a74f;hb=HEAD) for more technical information), the current module no longer works. Also see b4n/clawsmail-password-decrypter#6.

I would recommend that the module be completely removed, unless something can be done to update it to work with the new version.

**Comment by AlessandroZ** [comment]
I should take some time to check before removing it.

**Comment by AlessandroZ** [comment]
Last version of claws mail is supported now.
