### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by plonibarploni** [AlessandroZ/LaZagne#349]
It's been some time since the last release; perhaps it's time to release a new version?

Considering that many people are having issues trying to use the latest release (#303, #304, #308, #309, #310, #318, #326, #339), I think it would be very helpful (and also we won't get so many issues opened about something which is already fixed).

**Comment by AlessandroZ** [comment]
Done! 

https://github.com/AlessandroZ/LaZagne/releases/tag/v2.4.2
