### ISSUE TITLE
Found info about windows passwords storage locations

### ISSUE THREAD

**Issue by greyhound3** [AlessandroZ/LaZagne#35]
Maybe this link could be interesting http://www.nirsoft.net/articles/saved_password_location.html

**Comment by DaPhexion** [comment]
This... Is a bit outdated.

**Comment by AlessandroZ** [comment]
I have lots of idea as well, but I do not have enough time ;). 
Thank you by the way !!

**Comment by AlessandroZ** [comment]
I will close this issue because it is a bit outdated. Thanks anyway.
