### ISSUE TITLE
I can't compile lazagne.exe

### ISSUE THREAD

**Issue by QuestYouCraft** [AlessandroZ/LaZagne#350]
Hello, users, I'm having trouble compiling an executable for Windows. It compiles, but it does not run through the command line (cmd). I used Python 2.7 (I tried it with Python 3.7.2 and it didn't work either). He fulfilled [these](https://github.com/AlessandroZ/LaZagne/wiki/Requirements) requirements and [these](https://github.com/AlessandroZ/LaZagne/wiki/How-to-compile) instructions. If I do something wrong, make a YouTube video because I read all the other users ' problems, nothing helped. (OS: Windows 10 64-bit, pyinstaller latest version). Thank you in advance.

**Comment by plonibarploni** [comment]
What error did you get? Without information, there's little we can do to help you.

**Comment by QuestYouCraft** [comment]
Nothing, just nothing happens, no command line appears.

**Comment by plonibarploni** [comment]
What were the exact commands you used, and what was the output (if applicable)?

**Comment by QuestYouCraft** [comment]
Proofs [here](https://my-files.ru/Save/yx62ob/Proofs-CMD-laZagne.zip)
SHA-256 (for VT): e74450d353589ed9b849c3c0557028c0a5abedb504604787fb10d7acaccbbafc

**Comment by plonibarploni** [comment]
It appears you didn't follow the [Windows instructions](https://github.com/AlessandroZ/LaZagne/wiki/How-to-compile#for-windows-only).

If that isn't it:
1) What are the warnings printed in `LaZagne-master\Windows\build\lazagne\warn-lazagne.txt`?
2) What happens if you just execute `lazagne.exe` (without any arguments)?

**Comment by QuestYouCraft** [comment]
I didn't follow the "Windows only" instructions because I don't know which specific directory (specify the path to it) to put these files (msvcp100.dll and msvcr100.dll).

**Comment by plonibarploni** [comment]
They should be copied to the directory you're working in, which should be `LaZagne-master\Windows`.

**Comment by QuestYouCraft** [comment]
And in this same directory create file lasagne.spec and paste the code that was written in the instructions? And it needs to be created using Notepad in the usual Windows format?

**Comment by plonibarploni** [comment]
Yes

**Comment by QuestYouCraft** [comment]
And then you need to run the command `pyinstaller --onefile -w lazagne.spec`?

**Comment by plonibarploni** [comment]
Yes (that what it says in the wiki btw).

**Comment by QuestYouCraft** [comment]
The compilation was successful, but the compiled EXE file generates [this](https://i.paste.pics/359ec280c7dedb8c83286be000a91870.png) error. What to do?

**Comment by 0E800** [comment]
locate the file pypybla bla bla that the error says it cant find, and copy it to your modules or build directory and run it again.

in the future, just copy paste the error, it makes it difficult for us single finger typers to have to go back and forth between windows just to type out the error shown in a picture.

**Comment by 0E800** [comment]
pretty sure the last time I checked, the earlier builds of Lazagna do not trip up WIndows Def. and other A/V

**Comment by QuestYouCraft** [comment]
I didn't change the code, I just wanted to compile the release for 32-bit versions of Windows

**Comment by 0E800** [comment]
Are you determined to compile it yourself or do you just want to be able to use it?

**Comment by 0E800** [comment]
This is a personal build I did in 2015. I just tested it. 
https://drive.google.com/file/d/0BzolLN2vKwxjV2ZuNlpVRlF1cWc/view?usp=sharing
Download it somewhere easy like `c:\temp`
Run `CMD` as administrator
`cd \temp`
Type `lazagne all`

**Comment by plonibarploni** [comment]
> This is a personal build I did in 2015. I just tested it.

2015 was a long time ago. [Many commits](https://github.com/AlessandroZ/LaZagne/search?q=author-date%3A%3C2016-01-01&type=Commits) have been made since then.

[Here](https://github.com/AlessandroZ/LaZagne/files/2592396/laZagne.zip)'s a more recent build, from 17 November 2018.

**Comment by QuestYouCraft** [comment]
What is the solution to my error, specifically how to fix it, explain in great detail with directories. Thank you in advance.

**Comment by 0E800** [comment]
In 2015 Lazagne wasnt being Virus-totaled and all of those commits have potentially made it easier for A/V to pick out the indicators of compromise.

Getting someones stored Google Chrome creds is pretty much check mate.
Anyone that makes the decision to store cached credentials usually continues too. 
When you have a column of passwords and all of them are pretty much the same word but altered by a letter or number or special character, its fairly accurate to presume any password will be one of them.

In 2015 there were more x86 computers.. now everything is x64 and your bound to have issues.

I cant hold your hand through this. Your going to have to read the error, and determine what needs to be done. You havent read what I been trying to tell you, and you still havent provided the error in text form.

**Comment by QuestYouCraft** [comment]
What is the solution to my error??

**Comment by QuestYouCraft** [comment]
What is the solution???????

**Comment by QuestYouCraft** [comment]
https://github.com/AlessandroZ/LaZagne/issues/350#issuecomment-463963158
