### ISSUE TITLE
msvcp100.dll and msvcr100.dll is not in C:/Windows/System32

### ISSUE THREAD

**Issue by QuestYouCraft** [AlessandroZ/LaZagne#351]
Hello, users, when compiling, I noticed that msvcp100.dll and msvcr100.dll no in C:/Windows/System32 and I don't know how to compile laZagne.exe anymore. Thank you in advance.

**Comment by QuestYouCraft** [comment]
OS: Windows 7 Ultimate 32-bit; Python 2.7.15

**Comment by plonibarploni** [comment]
Download it from [here](http://www.microsoft.com/en-in/download/details.aspx?id=5555) (for 32-bit), or [here](http://www.microsoft.com/en-us/download/details.aspx?id=14632) (for 64-bit).

**Comment by QuestYouCraft** [comment]
Need to solve this problem in the requirements.
