### ISSUE TITLE
Windows XP. [196] Failed to execute script laZagne.

### ISSUE THREAD

**Issue by gromovoyb** [AlessandroZ/LaZagne#353]
I tried to run lazagne. In directory with .exe I typed `laZagne.exe all -oA`, but there is an error. On Windows 7 everything is ok with the same .exe. windows xp x32*
```
Traceback (most recent call last):
  File "laZagne.py", line 17, in <module>
  File "c:\users\test\appdata\local\temp\pip-build-nwxtpt\pyinstaller\PyInstalle
r\loader\pyimod03_importers.py", line 396, in load_module
  File "lazagne\config\change_privileges.py", line 5, in <module>
  File "c:\users\test\appdata\local\temp\pip-build-nwxtpt\pyinstaller\PyInstalle
r\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\psutil-5.4.4-py2.7-win32.egg\psutil\__init__.py", line 145
, in <module>
  File "c:\users\test\appdata\local\temp\pip-build-nwxtpt\pyinstaller\PyInstalle
r\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\psutil-5.4.4-py2.7-win32.egg\psutil\_pswindows.py", line 3
1, in <module>
RuntimeError: this Windows version is too old (< Windows Vista); psutil 3.4.2 is
 the latest version which supports Windows 2000, XP and 2003 server; it may be p
ossible that psutil will work if compiled from sources though
[396] Failed to execute script laZagne
```
![image](https://user-images.githubusercontent.com/47715835/52913884-21ea4400-32d3-11e9-9180-124a7962eb8d.png)

**Comment by 0E800** [comment]
Try using an older version of Lazagne

**Comment by QuestYouCraft** [comment]
This error indicates that the new (given) version of the psutil package (with which the compilation was done) is not supported on windows xp, windows 2000 and windows 2003 server and because of this the program is launched with an error. There are 2 ways to fix this error:
1st way:
Install the latest version of this package, which is supported on this version of the OS. For this:
1. You need to remove the current package with this command:
`pip uninstall psuti`
2. Now you need to download the latest version of the package, which is supported on Windows XP using this command:
`pip install psutil == 3.4.2`
3. To make recompilation of the EXE file "laZagne".
2nd way:
Download release, which is supported on Windows HP. I can't say which release is suitable, sorry, but you can download them all [here](https://github.com/AlessandroZ/LaZagne/releases).

**Comment by gromovoyb** [comment]
i found 0.9/0.9.1, they works on my xp x32,but:

C:\>lazagne1.exe windows

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

------------------- Windows Secrets passwords -----------------


Error:  Отказано в доступе.

[+] 0 passwords have been found.
For more information launch it again with the -v option

elapsed time = 1.41199994087


error: no permission*
i tried to run it on windows module, but there is an error, i tried to run cmd like administrator but no. and, in chrome lazagne finds only *saved in browser* passwords, for example, i signed up in mail and saved in chrome, lazagne sees it, but if i sign up in (for example) github and don't save it, he doesn't see it.

**Comment by AlessandroZ** [comment]
Try using the last [release](https://github.com/AlessandroZ/LaZagne/releases/tag/v2.4.2), psutil is not used on last versions.

**Comment by gromovoyb** [comment]
> Try using the last [release](https://github.com/AlessandroZ/LaZagne/releases/tag/v2.4.2), psutil is not used on last versions.

Error: this is not Win32 application.

**Comment by AlessandroZ** [comment]
Hmm, your Windows should have an x86 arch and the release has been built for x64. 

Try to build yourself an executable using the source code from the last github version, it should be the easier way to run it on an Windows XP.

**Comment by gromovoyb** [comment]
https://github.com/AlessandroZ/LaZagne/wiki/How-to-compile there? i installed pyinstaller, created exe, but now in lazagne/windows i have 2 new folders: "build" and "dist". what's next? should i create a .spec file, and if yes, where?

**Comment by gromovoyb** [comment]
![image](https://user-images.githubusercontent.com/47715835/53028707-6cf18c00-3478-11e9-9bc4-cfb55b3b01e0.png)
maybe something of this?

**Comment by gromovoyb** [comment]
i installed pyinstaller, created exe, but now in lazagne/windows i have 2 new folders: "build" and "dist". what's next? should i create a .spec file, and if yes, where?

**Comment by AlessandroZ** [comment]
Follow the [wiki](https://github.com/AlessandroZ/LaZagne/wiki/How-to-compile) to understand how things work. This is not an issue from Lazagne but how pyinstaller works. 

- Install all [requirements](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/requirement.txt) needed to run lazagne
- Install pywin32 if needed
- Embed msvcpxxx.dll if needed (if the targeted windows does not have Redistributable package installed)
- Create a custom .spec file (check wiki)
- Run pyinstaller 
- Get the compiled executable on the dist folder. 

I cannot help you more, everything is here.

**Comment by AlessandroZ** [comment]
Here is another [link](https://www.shanetully.com/2013/08/cross-platform-deployment-of-python-applications-with-pyinstaller/) that could help you.

And check how [travis](https://github.com/AlessandroZ/LaZagne/blob/master/.travis.yml) does to build an exe.

**Comment by gromovoyb** [comment]
thx for help!
