### ISSUE TITLE
Masterkey test

### ISSUE THREAD

**Issue by XXH3X** [AlessandroZ/LaZagne#355]
Is there anyway possible to disable the "masterkey test" because now, when I run lazagne in the windows module to get internet explorer passwords, it is takes around 30 minutes in the masterkey test. Any possible way of avoiding this or completly disable it? Thanks in advance

**Comment by AlessandroZ** [comment]
30 minutes ? it's super long ! 
Try to launch only internet explorer module: `lazagne browsers -ie`

**Comment by XXH3X** [comment]
> 30 minutes ? it's super long !
> Try to launch only internet explorer module: `lazagne browsers -ie`

Thanks I'll try it though, I'll let you updated on the current ocurrence

**Comment by XXH3X** [comment]
@AlessandroZ it doesn't work :P

It said to check the vault module, but if I run the vault module it will go back to the masterkey test :s.
Either way here is the output attached, I've type in:

-> lazagne.exe browsers -ie -vv

[output.txt](https://github.com/AlessandroZ/LaZagne/files/2915727/output.txt)

**Comment by AlessandroZ** [comment]
Yes, I forgot that Internet Explorer stored its creds using vault. To decrypt Vault files, you should get the masterkey, so you cannot bypass this test. Without it, no passwords could be decrypted it. 

The problem is that too many passwords are tested or there is lots of files to check. This is why it takes too much time. If you managed to found a working password which decrypt masterkeys, you can pass it to lazagne. 
`lazagne all --password "test"`

You could gain lots of time.

**Comment by XXH3X** [comment]
Is it possible to bypass the decryption of the vault files, only getting the the Internet explorer passwords?
Because if I run the module for all, it also test the other browsers and programs credentials, and none of them are "ok for masterkey". So I guess it couldn't decrypt the vault files. :s

**Comment by AlessandroZ** [comment]
No, one of them should be "ok for masterkey" otherwise, no internet explorer password could be decrypted. 
Redirect all the output to a file (`lazagne all -vv > output.txt`) and check it again. If you don't have any "ok for masterkey..." I don't understand how it does to decrypt :).

**Comment by XXH3X** [comment]
Ok, just tested it a found out that it actually outputed 2 sucessfull masterkey decryptions, I jusrt didn't saw them because they were at the very top of the log and the ones that are not ok are the ones the keep testing and give a "not ok" output, and were those that were caughting my attention, thanks for everything :P
