### ISSUE TITLE
compiling on windows

### ISSUE THREAD

**Issue by greckko** [AlessandroZ/LaZagne#356]
compiling on lazagne windows on python produces lazagne.exe but when I try to run lazagne.exe nothing happens.

![2019-03-01 15_16_45-c__windows_system32_cmd exe](https://user-images.githubusercontent.com/8646228/53643863-75468580-3c35-11e9-9922-3a65611294d3.png)

**Comment by AlessandroZ** [comment]
Install [pywin32](https://pypi.org/project/pywin32/#files). Check how I did it with [travis](https://github.com/AlessandroZ/LaZagne/blob/master/.travis.yml#L15L17).
