### ISSUE TITLE
Is there a way to bypass antivirus programs like windows's anti virus?

### ISSUE THREAD

**Issue by DjarDjar** [AlessandroZ/LaZagne#357]
Just read the title lul

**Comment by goldgoose617** [comment]
There is, but you need to do the work.

**Comment by DjarDjar** [comment]
So what do I have to do in order to make this happen. I am not very
familiar with the way antivirus programs work. I am a beginner in
cybersecurity. Thanks 😀.

**Comment by DjarDjar** [comment]
But I know python.

**Comment by AlessandroZ** [comment]
Yes you have lots of ways to do it but you will have to learn by yourself ;)

**Comment by DjarDjar** [comment]
Okay, fair enough :)

**Comment by usama7628674** [comment]
@DjarDjar Bypass all antivirus.See results here https://antiscan.me/scan/new/result?id=eqTaPhIGSR93
