### ISSUE TITLE
Yandex and Brave

### ISSUE THREAD

**Issue by DjarDjar** [AlessandroZ/LaZagne#359]
I think it doesn't work for Yandex Browser and brave

**Comment by Miroqil** [comment]
In YandexBrowser password not in BLOB data format. There stored password in JSON format like: {"c":"","e":"","p":"H3q2bAn/jYAThTc7R98qL3SG8GSX7RZQLAF3DoWQ5btIRODcGo8=","t":[]}

how to solve this?

**Comment by AlessandroZ** [comment]
I have fixed the problem for Brave browser, for Yandex is a little bit more complicated. I have tried to fix it but I do not have lots of time, so if you want to do it, I will be happy to accept your PR. 

You should have lots of information checking my first steps to retreive it (https://github.com/AlessandroZ/LaZagne/blob/1440c94ce8ed97e0cc0121506597141799c355b9/Windows/lazagne/softwares/browsers/chromium_based.py#L66-L101). It fails at the end, so something should be changed.

**Comment by DjarDjar** [comment]
I will be happy to help. I will first look at the code. Because yandex has a different way of encrypting the passwords I guess it won't be that easy decrypting it. Will see. Thanks for asking for my help m8.
