### ISSUE TITLE
Dictionary attack

### ISSUE THREAD

**Issue by luigino** [AlessandroZ/LaZagne#36]
It's not explained how to pass an external dictionary file and in which format it should be (wordlist? rainbow table with hashes?) and when the shadow file is not accessible due to insufficient privileges perhaps the user should be told.

BTW, also a couple of typos: "dictionnary" and "environnement".

**Comment by AlessandroZ** [comment]
Hi, 
I changed the README to explain how to use it. You could see it in the "Usage" section. I changed all dictionnary in dictionary and environment as well. 

For the shadow file, if you do not have enough privileges to see the shadow file, you have a warning only if you launch it using the verbose mode
ex: LaZagne all -v
