### ISSUE TITLE
Thunderbird error

### ISSUE THREAD

**Issue by NicoHood** [AlessandroZ/LaZagne#37]
Hi, I am using Ubuntu 64 bit and tried the compiled source from the Release 0.9.

I used `./LaZagne-64bits all -v` to start the analyzing and after it tried to read Thunderbird I get the following error. The program aborts afterwards.

```
------------------- Thunderbird passwords -----------------

Profile path found: /home/linuxuser/.thunderbird/removed.removeda

Profile path found: /home/linuxuser/.thunderbird/removed.removedb

Traceback (most recent call last):
  File "<string>", line 191, in <module>
  File "<string>", line 117, in runAllModules
  File "<string>", line 75, in launch_module
  File "/home/joe/Desktop/build/LaZagne/out00-PYZ.pyz/softwares.browsers.mozilla", line 492, in run
  File "/home/joe/Desktop/build/LaZagne/out00-PYZ.pyz/softwares.browsers.mozilla", line 53, in __iter__
IOError: [Errno 2] No such file or directory: '/home/linuxuser/.thunderbird/removed.removedb/logins.json'
```

It doesnt matter if Thunderbird is running or not. No password (should) be saved in my profile, that might be the problem?

**Comment by AlessandroZ** [comment]
Could you try the version 0.9.1 please. I fix it.

**Comment by NicoHood** [comment]
Now working fine! Thanks. It even found my IRC password.

It could only find my WLAN SSID, not the password. Thats good, not sure if its intended.

So overall the thing found 1 password for me. (IRC)

**Comment by AlessandroZ** [comment]
For wifi password, you need to be root to find it. 

For more passwords, you could try it using the source code, it doesn't manage the system wallet (ex: gnome keyring, Kwallet) with the binary. I don't know why.
