### ISSUE TITLE
Found passwords but login/password they are blank

### ISSUE THREAD

**Issue by tatuzex1** [AlessandroZ/LaZagne#370]
![Screenshot_1](https://user-images.githubusercontent.com/30058817/54646669-9ead4100-4a7e-11e9-8863-dc755852fcc2.png)

**Comment by 0E800** [comment]
Probably because the user opted to not save the creds to cache or because
methods of preventing that info from being stored I'm the same spot have
changed.

This is open source software, it would be stupid for any website or
antivirus to not use resources to prevent the goto skid app.

**Comment by plonibarploni** [comment]
Can you give more detailed system information?

**Comment by AlessandroZ** [comment]
I think, this is related to https://github.com/AlessandroZ/LaZagneForensic/issues/14

You should check the database manually if `blacklisted_by_user` is not set to 1. 
I will add a check to avoid to prompt empty passwords.

**Comment by AlessandroZ** [comment]
Should be fixed now. Nothing will be printed when passwords are empty.
