### ISSUE TITLE
lazagne.exe won't work

### ISSUE THREAD

**Issue by kazoo123** [AlessandroZ/LaZagne#372]
I'm trying to compile LaZagne but i'm having problem. I'm running a Python 2.7 version..

It works fine if i run the LaZagne.py with python (i.e: python lazagne.py all) but it won't display anything after compiling to exe and lunch it.. I attach a screenshot.. 

i would be glad if someone could help me explain better.

Thanks in advance.

![nothing](https://user-images.githubusercontent.com/47143069/54873873-76647000-4df9-11e9-9109-c9060eeb00e6.PNG)

![py](https://user-images.githubusercontent.com/47143069/54873874-7ebcab00-4df9-11e9-94cf-fdc205dd204a.PNG)

**Comment by 0E800** [comment]
You messed up on your build .

Try lazagne.exe all > pass.txt

**Comment by kazoo123** [comment]
Do you have an ideal what might be wrong? I would like to make the executable work properly.

Thanks

**Comment by kazoo123** [comment]
I tried the above command "lazagne.exe all > pass.txt" it runs and created a file but when i open the txt file it's empty. Any suggestions?

**Comment by 0E800** [comment]
I'll try to create a workflow and provide the steps.

Most likely its permission issue .
Reminds me of a printer that prints blank pages because user neglected to
remove tape from cartridge before installing. .

Took me a hour to realise you can't assume the obvious

**Comment by kazoo123** [comment]
Smiles..

Thanks

**Comment by AlessandroZ** [comment]
Check this https://github.com/AlessandroZ/LaZagne/issues/356

**Comment by kazoo123** [comment]
Thanks for that. It did help
