### ISSUE TITLE
Travis CI: Would it be useful build on 'os: windows' instead of linux-->wine?

### ISSUE THREAD

**Issue by cclauss** [AlessandroZ/LaZagne#380]
Something like https://github.com/rootm0s/WinPwnage/blob/master/.travis.yml ?

**Comment by AlessandroZ** [comment]
When I did it, I didn't know it was possible to do it with windows. 

But now that it worked, I don't know if it changes something to do it on Windows. At least, using linux, it would also be possible to create a linux release if I want. I don't want to spend time on it but maybe I miss something.

**Comment by cclauss** [comment]
Closing...  Tried and abandoned in #383.
