### ISSUE TITLE
Rewrite Supported software

### ISSUE THREAD

**Issue by torerobo** [AlessandroZ/LaZagne#391]
Rewrite Supported software, reason: there are too many things stated that do not work in fact, for example, Skype, Keepass ...
Support for these programs is stated, but it’s not fair, it’s better to be honest and remove half of the unsupported programs.

**Comment by AlessandroZ** [comment]
My english is not perfect but saying "it’s not fair, it’s better to be honest" it's quite aggressive. 
Keepass still works but you need to understand how it works to be able to run it, so this is not my fault and Skype still works before Windows 10, so it should be improved, but does not need to be removed. 

So thinking, it's not "honest" to keep it, it's a little bit exaggerated !
