### ISSUE TITLE
.exe error 

### ISSUE THREAD

**Issue by VtmSK** [AlessandroZ/LaZagne#393]
I get this error when i run the .exe and then i get an empty password file. I saw that there was a similar issue but i didn't understand the solution  
![python](https://user-images.githubusercontent.com/16341670/56440967-fa741f80-62f3-11e9-80ca-7aaaa9c465b2.jpg)

Ty and sorry for your time :)

**Comment by byehack** [comment]
https://github.com/AlessandroZ/LaZagne#installation

**Comment by VtmSK** [comment]
Just did it, same error :( ...

**Comment by VtmSK** [comment]
Deleted it and got a new clone, tried to compile, now getting this error :)
![error 2](https://user-images.githubusercontent.com/16341670/56474980-89b33b80-648a-11e9-95d5-fc200d0730be.png)

**Comment by byehack** [comment]
use python 2.7 to compile this.
it works best on 2.7

**Comment by VtmSK** [comment]
WIth 2.7 it comes blank, i run it the exact same way and i get a blank response.. When i run "lazagne.exe all > text.txt" the text file comes back blank.. Ran the requirements, put the ddl's in the folder ..

**Comment by AlessandroZ** [comment]
Check the [wiki](https://github.com/AlessandroZ/LaZagne/wiki/How-to-compile) and the [travis file](https://github.com/AlessandroZ/LaZagne/blob/master/.travis.yml), I think you have missed to install [pywin32](https://github.com/AlessandroZ/LaZagne/blob/master/.travis.yml#L39).
