### ISSUE TITLE
-v option does not work

### ISSUE THREAD

**Issue by markus80** [AlessandroZ/LaZagne#40]
> laZagne.exe wifi

[+] 0 passwords have been found.
For more information launch it again with the -v option

elapsed time = 0.00100016593933

> laZagne.exe -v wifi

error: unrecognized arguments: -v

OS: Windows 7 SP1 (x64, german)
laZagne: version 0.9.1

**Comment by Moter8** [comment]
You have to use `laZagne.exe wifi -v` :)

**Comment by markus80** [comment]
ok, ty, it works. so you can close / delete this issue.

hmmm, but i wonder what wlan this should be? never heard...
authentication: WPA2PSK
protected: true
ssid: Funkt

**Comment by Moter8** [comment]
@markus80 you can close the issue yourself. Just click on the Close button under this post. :beer:

**Comment by markus80** [comment]
but perhaps the -v option should be mentioned in the usage.
i could not find that the positon of -v should be at the end.

**Comment by AlessandroZ** [comment]
I cannot put the -v option on the main help menu. Because it would not be right. If you want to find main options you have to do: "Lazagne -h". 
And for optional arguments, you could do "Lazagne <menu> -h" for example: "lazagne chats -h"
You will see that the -v option is written.

**Comment by markus80** [comment]
ty for the information and sorry.
