### ISSUE TITLE
The exported TXT file is basically empty

### ISSUE THREAD

**Issue by guanayan** [AlessandroZ/LaZagne#400]
I have found all passwords by using the command "lazagne.exe all".
But The exported TXT file is basically empty by using “laZagne.exe all -oA -output C:\Users\test\Desktop” or "laZagne.exe all -oN"，Directory has been replaced.
I don't know what went wrong.The exported information is shown below.
`
|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

- Date: 2019-05-20 03:46:18
- Username: Administrator
- Hostname:PC201802120789`

**Comment by guanayan** [comment]
The software I use is the latest version.

**Comment by AlessandroZ** [comment]
This error has been corrected on the python code. Run it from source, it will work.
