### ISSUE TITLE
not getting passwords for Chrome,Opera

### ISSUE THREAD

**Issue by usama7628674** [AlessandroZ/LaZagne#401]
New version 2.4.2 isn't showing any password from chrome and opera.Only 2.3.1 version is working properly.

**Comment by AlessandroZ** [comment]
Hi, I need more information about this error. It works for me so I cannot reproduce it. Try the python version if you can. Run it with debug mode (`-vvv`) and print the output. Without information, I cannot debug it.

**Comment by usama7628674** [comment]
@AlessandroZ Okay so I used the python version and it works fine but when I run executable (.exe) with `lazagne.exe all -vvv` I received traceback 

`------------------- Google chrome passwords -----------------

[!] Database found: C:\Users\android-c02f5055f3c\AppData\Local\Google\Chrome\User Data\Default\Login Data
[!] Temporary db copied: c:\users\androi~1\appdata\local\temp\kphdfwpdp
[!] Traceback (most recent call last):
  File "lazagne\softwares\browsers\chromium_based.py", line 74, in _export_credentials
  File "lazagne\config\winstructure.py", line 542, in Win32CryptUnprotectData
  File "lazagne\config\winstructure.py", line 499, in getData
WindowsError: exception: access violation reading 0x000003C8995482C0`

**Comment by usama7628674** [comment]
@AlessandroZ So now I clone the tool with all latest commits and used python 3.7.2 to compile it to`.exe`
and now I get all passwords including chrome but there is still a traceback which delay the execution of code so it took around 2 minutes 38 seconds to complete.

```
[!] Traceback (most recent call last):
  File "C:\Users\android-78ffc50f1c\Downloads\Compressed\rats & crypters\LaZagne-master\LaZagne-master\Windows\lazagne\softwares\browsers\chromium_based.py", line 116, in _export_credentials
    user_dpapi=constant.user_dpapi)
  File "C:\Users\android-78ffc50f1c\Downloads\Compressed\rats & crypters\LaZagne-master\LaZagne-master\Windows\lazagne\config\winstructure.py", line 600, in Win32CryptUnprotectData
    raise ValueError('MasterKeys not found')
ValueError: MasterKeys not found
```

**Comment by Papotito123** [comment]
Hello to usama7628674:
Sorry to ask ,but:
You are using Windows 10 64 bit?
 You are compiling lazagne.py in python x64 or x86?

Thanks in advanced.

**Comment by usama7628674** [comment]
@Papotito123  I've compiled source code with pytho 3.7 and obfuscated some code to bypass AV.

**Comment by Papotito123** [comment]
Hello:
Thanks for responding.

**Comment by byehack** [comment]
> @Papotito123 I've compiled source code with pytho 3.7 and obfuscated some code to bypass AV.

hello!
what's your:
os name and version?
python 32/64 bit?
use https://github.com/MrByehack/LaZagne and give me the feeadback. Thanks!

**Comment by AlessandroZ** [comment]
The issue `WindowsError: exception: access violation reading...` had been fixed. Next release won't have this problem.
