### ISSUE TITLE
Cannot retrieve Chrome passwords on MacOS

### ISSUE THREAD

**Issue by Aniruddh-J** [AlessandroZ/LaZagne#408]
Hello,

I can't seem to make script work on MacOS. Following the output:

```
|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

[!] Python 2.7.16 on Darwin x86_64: i386

 ------------------- Chrome passwords -----------------

[-] Chrome safe storage key has not been retrieved, cannot decrypt passwords
[!] No passwords found

[+] 0 passwords have been found.

elapsed time = 0.000288009643555
```

**Comment by kanna27** [comment]
Sorry dood some bug we will fix it soon Thank you

**Comment by AlessandroZ** [comment]
Chrome stores not in clearext passwords in its database. All these passwords are encrypted using a master password called "Chrome safe storage key" and stored on your keychain. If the keychain is not decrypted, no passwords are decrypted. 

Check the [Readme](https://github.com/AlessandroZ/LaZagne/blob/master/README.md#mac-os) to understand how mac works.

**Comment by Aniruddh-J** [comment]
It doesn't work even if you enter correct keychain password.

**Comment by AlessandroZ** [comment]
Could you give me more information about what does not work. 

- What's Mac OS version do you have ? 
- Does the keychains is successfully decrypted ? (you retrieve information stored on it ?)
    - If not, does your keychain is decrypted using https://github.com/n0fate/chainbreaker/ ? 
    - If it does, is chrome safe password present on your keychain ?  

Thanks
