### ISSUE TITLE
Supporting Luigi's password recovery scripts

### ISSUE THREAD

**Issue by maaaaz** [AlessandroZ/LaZagne#41]
Hello,

It would be cool is LaZagne would integrate all password recovery scripts developped by Luigi Auriemma `http://aluigi.altervista.org/pwdrec.htm`

Cheers.

**Comment by AlessandroZ** [comment]
I will do it when I will have more time. Thanks for the sharing.

**Comment by tautology0** [comment]
I've started putting some decryptors and notes for passwords and hashes I've found on my github repo:

https://github.com/tautology0/password-decryptors

They're under the MIT licence so you can mangle them however you want.
