### ISSUE TITLE
Outlook not working

### ISSUE THREAD

**Issue by gflybird** [AlessandroZ/LaZagne#410]
Decrypting outlook passwords not found, neither are skype passwords.

**Comment by kanna27** [comment]
Sorry dood some bug on script now we will retrieve shortly you can find WiFi pass only now

**Comment by AlessandroZ** [comment]
Skype installed as default in a newer windows version as a desktop application is not supported. However, skype installed by yourself (downloaded from skype website) is still supported (at least you retrieve an hash to bruteforce). 

For outlook, if it's an exchange passwords, the password will not be shown from outlook module but using credentials file (so you will need the user passwords to decrypt these files).
