### ISSUE TITLE
Not getting all passwords when local admin (Windows)

### ISSUE THREAD

**Issue by cervoise** [AlessandroZ/LaZagne#412]
Hi,

LaZagne is not crawling all users repository when launched with local admin privileges on Windows.

I can work on this feature, but I am not sure on the best way to do so. A dirty way will be to check if the module runs with local admin privilege and do the stuff. This will need to change all modules using %USER% folder.

Do you any ideas?

**Comment by AlessandroZ** [comment]
Hi, 

This is weird, it should work. If you can try to take a look to debug the problem it should be great. 

If you have admin rights, [set_env_variables](https://github.com/AlessandroZ/LaZagne/blob/ce1b46b9d0c9e9cc600a9b2bd457a1ea69de5ec3/Windows/lazagne/config/run.py#L195) is called. This function defines a [variable](https://github.com/AlessandroZ/LaZagne/blob/ce1b46b9d0c9e9cc600a9b2bd457a1ea69de5ec3/Windows/lazagne/config/users.py#L39) containing all path needed.  Depending on the user, the path is modified using the good [username](https://github.com/AlessandroZ/LaZagne/blob/ce1b46b9d0c9e9cc600a9b2bd457a1ea69de5ec3/Windows/lazagne/config/users.py#L61). 

If it does not work, something went wrong on this process. 

Thanks for your help.

**Comment by cervoise** [comment]
Hi,

I rebuild my Windows 10 target and setup a Windows 7 target, this is working fine. LaZagne running with admin privileges will find password from other users.

I still have an issue with Wi-Fi PSK that I have to retry. My test targets does not have Wi-Fi interface.
