### ISSUE TITLE
lazagne compiled .exe doesn't recover Chrome

### ISSUE THREAD

**Issue by Papotito123** [AlessandroZ/LaZagne#418]
Hello;
I'm just playing with your tool.
I managed to run laZagneForensic.

But also compiled a lazagne.exe .It runs.
It doesn't retrieve Chrome user/password.

[Papotito123_compiled.txt](https://github.com/AlessandroZ/LaZagne/files/3586273/Papotito123_compiled.txt)
[Papotito123_compiled.json.txt](https://github.com/AlessandroZ/LaZagne/files/3586274/Papotito123_compiled.json.txt)

Thanks again.

**Comment by AlessandroZ** [comment]
Without verbose mode I cannot understand the problem but I'm pretty sure, it's because your not using the last version :).

**Comment by Papotito123** [comment]
Hello:
I'm the same guy,Papotito123 from #416.

I compiled this new lazagne.py 2.4.2.2 to .exe

Here is the raw cmd output.

[Papotito123_lazagne 2.4.2.2_compiled_raw cmd.txt](https://github.com/AlessandroZ/LaZagne/files/3593443/Papotito123_lazagne.2.4.2.2_compiled_raw.cmd.txt)

With lazagne.py 2.4.2.2 Chrome user/password can be retrieved.

Thanks and sorry for this other post.

**Comment by Papotito123** [comment]
Hello:
At this time,I will let you be the one that take decision to Close.

Thank you.
