### ISSUE TITLE
not working on win8

### ISSUE THREAD

**Issue by YacineBnl** [AlessandroZ/LaZagne#42]
it doesnot work on all windows i tried it in my win7 it works fine when i tried this last version V09.1 in windows 8 pc didnt work i keep getting an error messege in cmd and i also tried it with admin  and the same error

**Comment by AlessandroZ** [comment]
Could you try the version 1.0 please. I have changed my way to compile the binary, I hope it will work.

**Comment by vdeunzue** [comment]
Hey, I tried it and it works in W8

**Comment by AlessandroZ** [comment]
Thanks for the feedback, I close the issue
