### ISSUE TITLE
Minor Python3 issue

### ISSUE THREAD

**Issue by plonibarploni** [AlessandroZ/LaZagne#421]
Mimipy finds the login info from `/usr/bin/gnome-keyring-daemon`, but outputs the password as `Password: b'mysecretpassword'`. Python2 outputs the password normally `Password: mysecretpassword`.

**Comment by byehack** [comment]
this isn't problem.
in py 3 we should use bytes instead strings.

**Comment by plonibarploni** [comment]
> this isn't problem.
> in py 3 we should use bytes instead strings.

The output should still be the same. It should be *displayed* as a string.

**Comment by byehack** [comment]
> The output should still be the same. It should be _displayed_ as a string.

use https://github.com/MrByehack/LaZagne . may fix your problem
