### ISSUE TITLE
Issue with chrome password on Linux

### ISSUE THREAD

**Issue by trossets** [AlessandroZ/LaZagne#429]
Hi,
As I have a problem on Linux where chrome doesn't show any saved password I tried LaZagne. Unfortunately it didn't work: decrypted passwords don't make sense. After investigation I think chrome might have changed the way it stores encrypted passwords in the file 'Login Data' because when I try manually to call openssl:
echo base64_encrypted_password | openssl enc -base64 -d -aes-128-cbc -iv 20202020202020202020202020202020 -K encoding_key
I get the following error:
digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:evp_enc.c:529
As I have a 'Chromium Safe Storage' both in kwallet and in gnome keyring, I tried with both but always got the same error.
Any thoughts ?

**Comment by plonibarploni** [comment]
If Chrome doesn't show saved passwords, it's likely a problem with your file, not with Chrome or LaZagne.

I just tested LaZagne on my computer and it works (after getting Chromium Safe Storage from Libsecret).

**Comment by trossets** [comment]
Thank you for your answer. It's reassuring to know that LaZagne does work. I think I will dig deeper when I have time.

**Comment by AlessandroZ** [comment]
:+1:
