### ISSUE TITLE
cant decrypt vaults.

### ISSUE THREAD

**Issue by byehack** [AlessandroZ/LaZagne#438]
win10-64bit - py2.7-64bit. also not work in py36-32bit.
i think the problems are [here](https://github.com/AlessandroZ/LaZagne/blob/8fa1cc4a890a96cc977813946dd1b5975906d546/Windows/lazagne/config/winstructure.py#L146) and [here](https://github.com/AlessandroZ/LaZagne/blob/8fa1cc4a890a96cc977813946dd1b5975906d546/Windows/lazagne/config/winstructure.py#L183) on commented lines.
please look at mimikatz: [this function](https://github.com/gentilkiwi/mimikatz/blob/6436bbe7bc9712fdacc99ca0ca6b0fcfcb853187/mimikatz/modules/kuhl_m_vault.h#L124)

**Comment by byehack** [comment]
for test:

connect to a rdp-vps server with `mstsc.exe` in windows and fill the `remember password and user` box when you want connect to server. so now the ip,user and password will save in vault of windows. try `lazagne` in admin mode to decrypt them. try `NetworkPasswordDecryptor64.exe` to decrypt them.

**Comment by byehack** [comment]
fixed in https://github.com/byehack/LaZagne

**Comment by AlessandroZ** [comment]
Hi @byehack, 

What was the fix for this problem please ?

**Comment by byehack** [comment]
i could recover my vaults with `credfiles`.
but now the main issue is about decrypting vaults and it still exists here: https://github.com/AlessandroZ/LaZagne/issues/458
you can continue this thread on there.
