### ISSUE TITLE
Gather passwords from mounted disk image?

### ISSUE THREAD

**Issue by davispuh** [AlessandroZ/LaZagne#442]
Basically I have raw Windows `disk.img` that I mounted on Linux so I can access all files and now I want to gather all passwords from there, but I don't see any way to specify path?

Basically something like this `./laZagne.py all /mnt/WindowsC/`

**Comment by AlessandroZ** [comment]
This is what you need: https://github.com/AlessandroZ/LaZagneForensic
The problem is that the project is not up to date :(
