### ISSUE TITLE
Huge size of EXE

### ISSUE THREAD

**Issue by badbob** [AlessandroZ/LaZagne#45]
Is there some way to make EXE smaller? 
At this time target EXE has more then 15 MB size.

**Comment by AlessandroZ** [comment]
I know, that's a problem. 
The size is because the tool is done in python. It could be compressed using UPX but it is often detected by antivirus. So I do not want to package it. 
However, even the project will grow, I don't think the size will increase a lot.

**Comment by badbob** [comment]
I tried to pack it by UPX, and the compression rate about 2%. So, this EXE is not compressible at all. 

Did you try py2exe instead of Pyinstaller?

**Comment by AlessandroZ** [comment]
No I only tried with Pyinstaller. 
I will try with py2exe when I have some free time. Now it is quite difficult to work on it.

**Comment by ypid** [comment]
Somewhat related to this. @AlessandroZ: Please don’t add those binary files to git. Git is not designed for this. If you want to put the builds under version control you can use git-annex to keep everything in one repository without the need to donwload the binary files on `git clone`. The current repository size is 244.80 MiB which is ridicules … You might want to rewrite history.
Note that you can also attach binary files to a release on GitHub. "Edit" → "Attach binaries by dropping them here or …".

BTW: Nice program. It saved my day trying to recover a Outlook 2007 POP3 password :+1:

**Comment by AlessandroZ** [comment]
I removed Binaries from the src code. I put it on the release repository only.
