### ISSUE TITLE
does it work for windows poython3?

### ISSUE THREAD

**Issue by nigacat423** [AlessandroZ/LaZagne#450]
![图片](https://user-images.githubusercontent.com/49108901/71243602-a9696f00-234b-11ea-8908-f9223e2add91.png)

**Comment by byehack** [comment]
use this for python3 support: https://github.com/MrByehack/LaZagne

**Comment by Papotito123** [comment]
Hello:
I had to install Python 3.7 x64 and MrByehack lazagne's works good.
Recovered WIFI/Chrome which I had issue when compiling using Python 2.7 x86.

**Comment by byehack** [comment]
fixed in the last commit. you can close this issue!

**Comment by nigacat423** [comment]
Thanks I I have solved this problem!

发送自 Windows 10 版邮件应用

发件人: byehack
发送时间: 2019年12月20日 22:19
收件人: AlessandroZ/LaZagne
抄送: nigacat423; Author
主题: Re: [AlessandroZ/LaZagne] does it work for windows poython3? (#450)

use this for python3 support: https://github.com/MrByehack/LaZagne
