### ISSUE TITLE
Change return type of function Win32CryptUnprotectData to bytes

### ISSUE THREAD

**Issue by MyLoginOnGitHub** [AlessandroZ/LaZagne#456]
I suggest not to decode result in function Win32CryptUnprotectData to string and do in on client side. Client should to determine exact encoding to decode data to string. I faced it on collecting outlook passwords: Win32CryptUnprotectData decodes data as UTF-8, but real data encoding for outlooks' imap passwords is UTF-16 (WIN-7, Outlook 2016).

**Comment by MyLoginOnGitHub** [comment]
I also want to mention that in my case result as bytes was <PASSWORD IN UTF-16>\x00\x00, i.e. there was a pair of null-bytes trailing. Probably, this is string terminator used by Outlook.

**Comment by MyLoginOnGitHub** [comment]
I could do this, I just want to ask @AlessandroZ if it is the right approach?

**Comment by AlessandroZ** [comment]
Maybe it could be nice to find which kind of encoding it is to decode it properly. I don't know if it's easy or not but I image siomething here: https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/config/winstructure.py#L615

Does a string encoding with utf-8 fails when it's encoded as utf16 ? In that case a simple try/except will work. Otherwise, maybe checking if all characters in that string are separated by a \x00 ? 

Because if you do not decode it, some password are really difficult to read. And if we do not have any other solution, we could print without decode it.

**Comment by AlessandroZ** [comment]
Maybe I didn't understand well what you suggested when you talked about decoding on the client side.

**Comment by MyLoginOnGitHub** [comment]
> Does a string encoding with utf-8 fails when it's encoded as utf16 ?

No, it's not fails, but the result is not properly.
For example (python3, Windows (On Ubuntu another result, I do not understand why...)):

`x = b'P\x00A\x00S\x00S\x00W\x00O\x00R\x00D\x00\x00\x00'`
`res_utf_8 = x.decode("utf-8")`
`print("%s: %s" % ("PASSWORD", res_utf_8))`
Result is: "PASSWORD: P A S S W O R D   "

`x = b'P\x00A\x00S\x00S\x00W\x00O\x00R\x00D\x00\x00\x00'`
`res_utf_16 = x.decode("utf-16")`
`print("%s: %s" % ("PASSWORD", res_utf_16))`
Result is: "PASSWORD: PASSWORD "
This is example for decoding outlook IMAP passwords from bytes to string.

> Maybe it could be nice to find which kind of encoding it is to decode it properly.
> Maybe I didn't understand well what you suggested when you talked about decoding on the client side.

I suggest to return **bytes** from function _Win32CryptUnprotectData_. And try to decode it in method, which called Win32CryptUnprotectData. I mean to remove `.decode("utf-8")` from both https://github.com/AlessandroZ/LaZagne/blob/6b0f98751979c1a50b6c895b3767e7d8c4ce6e3b/Windows/lazagne/config/winstructure.py#L615 and https://github.com/AlessandroZ/LaZagne/blob/6b0f98751979c1a50b6c895b3767e7d8c4ce6e3b/Windows/lazagne/config/winstructure.py#L619 and change all ussages of Win32CryptUnprotectData to convert bytes to string properly.
For example for _outlook_ the line https://github.com/AlessandroZ/LaZagne/blob/8c8d14d929301f12796073e5987a049fe7491965/Windows/lazagne/softwares/mails/outlook.py#L56 should change to `                    values[k[0]] = password.decode("utf-16")`
For all others decode to utf-8. But if it ever needs to decode by some other way - it could be done easely without changing code of function _Win32CryptUnprotectData_.
I hope so it became clearer :-)

**Comment by AlessandroZ** [comment]
Ah yes, I understood now. Yes sure, that's a good idea. Thanks for your help ! :+1:

**Comment by MyLoginOnGitHub** [comment]
Not at all :-) I am really interested in this project!
