### ISSUE TITLE
generate credentials3

### ISSUE THREAD

**Issue by vinnitu** [AlessandroZ/LaZagne#46]
Hi.

I have login and password to skype account.
I need generate credentials without skype app. Is it possible?
I known about md5(login+"\nskyper\n"+password) but it is only 32 symbols (in hex) and
full <credentials3> tag value is 1216 bytes about.

**Comment by AlessandroZ** [comment]
Hi, 
I don't understand your request. What do you mean saying that you need to "generate" credentials for skype ? 

Skype passwords is stored as a hash in configuration file. It's not in cleartext, so to decipher it you will need to bruteforce it following the template "login+"\nskyper\n"+password". 
Btw, the md5 hash is also encrypted (that is maybe you question), so you have to decrypt it before to bruteforce and to do that you need to find the salt (stored on registry). 
If you want to find the login and password offline (so from another computer), you have to be sure to have the good hash. Not the hash stored on the configuration file.

**Comment by vinnitu** [comment]
I need programmicaly encode credentials (without skype). I have login and password.
First 32 symbols in xml file <credetential> tag is md5(login+"\nskyper\n"+password), but what is rest of token? As I see http://recon.cx/en/f/vskype-part2.pdf (page 67) it is manipulation with RSA private key but how?

PS: I need credentials value to automate login to skype (without user interaction)
