### ISSUE TITLE
laZagne crashed on decrypt `Vault passwords`

### ISSUE THREAD

**Issue by byehack** [AlessandroZ/LaZagne#460]
i used the latest commit from github. in __win10-64it__ and __python 3.8-64bit__ with __admin mode__ and use the __-password__ parameter:

```
C:\Python38\LaZagne-master\Windows>c:/python38/python.exe lazagne.py all -password XXX -vvv

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

[!] Python 3.8.0 on Windows AMD64: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

[+] System masterkey decrypted for 1e39a3df-b0c2-474e-86a4-955211277910
[+] System masterkey decrypted for a4de2ba3-7cc0-444d-9933-5fc7466449a2
[+] System masterkey decrypted for dba70110-e026-4db9-977b-24ef54715bd5
[+] System masterkey decrypted for e59b7284-0184-41a5-a4ca-af5695091c86

########## User: SYSTEM ##########

 ------------------- Ftpnavigator passwords -----------------

[!] No passwords found

 ------------------- Unattended passwords -----------------

[!] No passwords found

 ------------------- Pypykatz passwords -----------------

None
[+] Shahash found !!!
Shahash: 8ca350a606385033e67e9d308746711f3c96d739
Nthash: a5174048165b243fb0f74bb063077a8d
Login: Tester

[+] Shahash found !!!
Shahash: e18db28dd5cb56dfaed12a2efbbddd1ce5e8006b
Nthash: c22b315c040ae6e0efee3518d830362b
Login: new

 ------------------- Mscache passwords -----------------

[!] No passwords found

 ------------------- Hashdump passwords -----------------

Administrator:500:aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0:::
Guest:501:aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0:::
DefaultAccount:503:aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0:::
WDAGUtilityAccount:504:aad3b435b51404eeaad3b435b51404ee:3b701e6efe903754ae4887642ced93c5:::
Tester:1001:aad3b435b51404eeaad3b435b51404ee:a5174048165b243fb0f74bb063077a8d:::
new:1003:aad3b435b51404eeaad3b435b51404ee:c22b315c040ae6e0efee3518d830362b:::

 ------------------- Lsa_secrets passwords -----------------

DPAPI_SYSTEM
0000   01 00 00 00 9A 70 14 44 9F 07 A5 53 C8 D1 8A A6    .....p.D...S....
0010   F4 9B FC DA A4 4C ED AE F0 1F 5A 03 96 8E DF B4    .....L....Z.....
0020   F2 82 CA 3E 16 D4 91 4D 7F FA 70 47                ...>...M..pG

L$_SQSA_S-1-5-21-1846087244-4292759693-1040491465-1001
0000   0A 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
0010   7B 00 22 00 76 00 65 00 72 00 73 00 69 00 6F 00    {.".v.e.r.s.i.o.
0020   6E 00 22 00 3A 00 31 00 2C 00 22 00 71 00 75 00    n.".:.1.,.".q.u.
0030   65 00 73 00 74 00 69 00 6F 00 6E 00 73 00 22 00    e.s.t.i.o.n.s.".
0040   3A 00 5B 00 7B 00 22 00 71 00 75 00 65 00 73 00    :.[.{.".q.u.e.s.
0050   74 00 69 00 6F 00 6E 00 22 00 3A 00 22 00 57 00    t.i.o.n.".:.".W.
0060   68 00 61 00 74 00 19 20 73 00 20 00 74 00 68 00    h.a.t.. s. .t.h.
0070   65 00 20 00 6E 00 61 00 6D 00 65 00 20 00 6F 00    e. .n.a.m.e. .o.
0080   66 00 20 00 74 00 68 00 65 00 20 00 63 00 69 00    f. .t.h.e. .c.i.
0090   74 00 79 00 20 00 77 00 68 00 65 00 72 00 65 00    t.y. .w.h.e.r.e.
00A0   20 00 79 00 6F 00 75 00 20 00 77 00 65 00 72 00     .y.o.u. .w.e.r.
00B0   65 00 20 00 62 00 6F 00 72 00 6E 00 3F 00 22 00    e. .b.o.r.n.?.".
00C0   2C 00 22 00 61 00 6E 00 73 00 77 00 65 00 72 00    ,.".a.n.s.w.e.r.
00D0   22 00 3A 00 22 00 71 00 61 00 65 00 6D 00 73 00    ".:.".q.a.e.m.s.
00E0   68 00 61 00 68 00 72 00 22 00 7D 00 2C 00 7B 00    h.a.h.r.".}.,.{.
00F0   22 00 71 00 75 00 65 00 73 00 74 00 69 00 6F 00    ".q.u.e.s.t.i.o.
0100   6E 00 22 00 3A 00 22 00 57 00 68 00 61 00 74 00    n.".:.".W.h.a.t.
0110   19 20 73 00 20 00 74 00 68 00 65 00 20 00 66 00    . s. .t.h.e. .f.
0120   69 00 72 00 73 00 74 00 20 00 6E 00 61 00 6D 00    i.r.s.t. .n.a.m.
0130   65 00 20 00 6F 00 66 00 20 00 79 00 6F 00 75 00    e. .o.f. .y.o.u.
0140   72 00 20 00 6F 00 6C 00 64 00 65 00 73 00 74 00    r. .o.l.d.e.s.t.
0150   20 00 63 00 6F 00 75 00 73 00 69 00 6E 00 3F 00     .c.o.u.s.i.n.?.
0160   22 00 2C 00 22 00 61 00 6E 00 73 00 77 00 65 00    ".,.".a.n.s.w.e.
0170   72 00 22 00 3A 00 22 00 69 00 6E 00 63 00 6F 00    r.".:.".i.n.c.o.
0180   72 00 72 00 65 00 63 00 74 00 22 00 7D 00 2C 00    r.r.e.c.t.".}.,.
0190   7B 00 22 00 71 00 75 00 65 00 73 00 74 00 69 00    {.".q.u.e.s.t.i.
01A0   6F 00 6E 00 22 00 3A 00 22 00 57 00 68 00 61 00    o.n.".:.".W.h.a.
01B0   74 00 20 00 77 00 61 00 73 00 20 00 79 00 6F 00    t. .w.a.s. .y.o.
01C0   75 00 72 00 20 00 66 00 69 00 72 00 73 00 74 00    u.r. .f.i.r.s.t.
01D0   20 00 70 00 65 00 74 00 19 20 73 00 20 00 6E 00     .p.e.t.. s. .n.
01E0   61 00 6D 00 65 00 3F 00 22 00 2C 00 22 00 61 00    a.m.e.?.".,.".a.
01F0   6E 00 73 00 77 00 65 00 72 00 22 00 3A 00 22 00    n.s.w.e.r.".:.".
0200   69 00 6E 00 63 00 6F 00 72 00 72 00 65 00 63 00    i.n.c.o.r.r.e.c.
0210   74 00 22 00 7D 00 5D 00 7D 00 00 00 00 00 00 00    t.".}.].}.......

NL$KM
0000   40 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    @...............
0010   28 75 33 8D F2 1F 8F 37 4B 78 AA 22 9E BD 93 B4    (u3....7Kx."....
0020   29 46 27 AF 4E B1 9E FA DA 59 CE E8 56 AB 67 91    )F'.N....Y..V.g.
0030   16 A1 D8 29 02 8D 69 A2 89 65 42 D2 51 47 7C A2    ...)..i..eB.QG|.
0040   50 95 37 73 76 D0 50 63 45 94 21 27 18 21 2A 26    P.7sv.PcE.!'.!*&
0050   29 D1 79 AD DB 1B 1F B1 FB FB 89 DD 3B 70 4F 8B    ).y.........;pO.


[!] Temp sam removed: C:\Users\Tester\AppData\Local\Temp\sfvtxbolkl
[!] Temp security removed: C:\Users\Tester\AppData\Local\Temp\iqgyhe
[!] Temp system removed: C:\Users\Tester\AppData\Local\Temp\umgwlm

########## User: Tester ##########

 ------------------- Firefox passwords -----------------

[!] Profile path found: C:\Users\Tester\AppData\Roaming\Mozilla\Firefox\Profiles\rmgucj77.default
[!] Database empty
[!] Profile path found: C:\Users\Tester\AppData\Roaming\Mozilla\Firefox\Profiles\jsfgs651.default-release
[!] Database empty
[!] No passwords found

 ------------------- Blackhawk passwords -----------------

[!] No passwords found

 ------------------- Cyberfox passwords -----------------

[!] No passwords found

 ------------------- Comodo icedragon passwords -----------------

[!] No passwords found

 ------------------- K-meleon passwords -----------------

[!] No passwords found

 ------------------- Icecat passwords -----------------

[!] No passwords found

 ------------------- Pidgin passwords -----------------

[!] No passwords found

 ------------------- Psi-im passwords -----------------

[!] No passwords found

 ------------------- Dbvis passwords -----------------

[!] No passwords found

 ------------------- Squirrel passwords -----------------

[!] No passwords found

 ------------------- Sqldeveloper passwords -----------------

[!] No passwords found

 ------------------- Robomongo passwords -----------------

[!] No passwords found

 ------------------- Postgresql passwords -----------------

[!] No passwords found

 ------------------- Kalypsomedia passwords -----------------

[!] No passwords found

 ------------------- Galconfusion passwords -----------------

[!] No passwords found

 ------------------- Roguestale passwords -----------------

[!] No passwords found

 ------------------- Turba passwords -----------------

[!] Turba doesn't appear to be installed.
[!] No passwords found

 ------------------- Gitforwindows passwords -----------------

[!] No passwords found

 ------------------- Thunderbird passwords -----------------

[!] No passwords found

 ------------------- Mavenrepositories passwords -----------------

[!] No passwords found

 ------------------- Memory_dump passwords -----------------

[!] No passwords found

 ------------------- Keepass passwords -----------------

[!] No passwords found

 ------------------- Eyecon passwords -----------------

[!] No passwords found

 ------------------- Composer passwords -----------------

[!] No passwords found

 ------------------- Apachedirectorystudio passwords -----------------

[!] No passwords found

 ------------------- Coreftp passwords -----------------

[!] [WinError 2] The system cannot find the file specified
[!] No passwords found

 ------------------- Filezilla passwords -----------------

[!] No passwords found

 ------------------- Filezillaserver passwords -----------------

[!] No passwords found

 ------------------- Keepassconfig passwords -----------------

[!] No passwords found

 ------------------- Puttycm passwords -----------------

[!] No passwords found

 ------------------- Opensshforwindows passwords -----------------

[!] No passwords found

 ------------------- Winscp passwords -----------------

[!] [WinError 2] The system cannot find the file specified
[!] No passwords found

 ------------------- Vnc passwords -----------------

[!] Problems with file: C:\Program Files (x86)\uvnc bvba\UltraVNC\ultravnc.ini
[!] Problems with file: C:\Program Files (x86)\uvnc bvba\UltraVNC\ultravnc.ini
[!] Problems with file: C:\Program Files\uvnc bvba\UltraVNC\ultravnc.ini
[!] Problems with file: C:\Program Files\uvnc bvba\UltraVNC\ultravnc.ini
[!] Problems with file: C:\Program Files\UltraVNC\ultravnc.ini
[!] Problems with file: C:\Program Files\UltraVNC\ultravnc.ini
[!] Problems with file: C:\Program Files (x86)\UltraVNC\ultravnc.ini
[!] Problems with file: C:\Program Files (x86)\UltraVNC\ultravnc.ini
[!] Problems with key:: HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\RealVNC\WinVNC4
[!] Problems with key:: HKEY_LOCAL_MACHINE\SOFTWARE\RealVNC\vncserver
[!] Problems with key:: HKEY_LOCAL_MACHINE\SOFTWARE\RealVNC\WinVNC4
[!] Problems with key:: HKEY_CURRENT_USER\SOFTWARE\RealVNC\WinVNC4
[!] Problems with key:: HKEY_CURRENT_USER\Software\ORL\WinVNC3
[!] Problems with key:: HKEY_CURRENT_USER\Software\TightVNC\Server
[!] Problems with key:: HKEY_CURRENT_USER\Software\TightVNC\Server
[!] Problems with key:: HKEY_LOCAL_MACHINE\Software\TightVNC\Server
[!] Problems with key:: HKEY_LOCAL_MACHINE\Software\TightVNC\Server
[!] Problems with key:: HKEY_LOCAL_MACHINE\Software\TightVNC\Server
[!] Problems with key:: HKEY_LOCAL_MACHINE\Software\TigerVNC\Server
[!] Problems with key:: HKEY_CURRENT_USER\Software\TigerVNC\Server
[!] No passwords found

 ------------------- Wsl passwords -----------------

[!] No passwords found

 ------------------- Credman passwords -----------------

[+] Password found !!!
URL: TERMSRV/179.154.XXX.XXX
Login: Administrador
Password: XXX

[+] Password found !!!
URL: TERMSRV/61.178.XXX.XXX
Login: localhost
Password: XXX

 ------------------- Vault passwords -----------------


C:\Python38\LaZagne-master\Windows>

**Comment by Papotito123** [comment]
hello:
I see you managed to retrieve Hashdumps in python 3.

I ran Edge and saved an outlook account.

Then,I ran latest lazagne code adding this mod(Fix 459 #461 suggested  by MyLoginOnGitHub to resolve lazagne crash) and this what I got
C:\Windows\system32>cd C:\Users\TESTACCOUNT\Desktop\Python37

C:\Users\TESTACCOUNT\Desktop\Python37>python "C:\lazena\Windows\laZagne.py" all -password qqqqqqqqq -vvv

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

[!] Python 3.7.6 on Windows AMD64: Intel64 Family 6 Model 30 Stepping 5, GenuineIntel

[+] System masterkey decrypted for 08be8fec-13ca-4ae0-8341-36b907e33d19
[+] System masterkey decrypted for 15e43b11-4cee-437f-928e-082807c02474
[+] System masterkey decrypted for 1e8bc276-41f3-493f-8fb4-32496443bb79
[+] System masterkey decrypted for 4e79d188-0323-4c0b-9796-0d9ffc89f045
[+] System masterkey decrypted for 55aa46c8-2bc6-496a-8888-482c24891036

########## User: SYSTEM ##########
  ,and so on ,

########## User: TESTACCOUNT ##########
 ------------------- Firefox passwords -----------------
  ,and so on,
------------------- Wsl passwords -----------------

[!] No passwords found

 ------------------- Credman passwords -----------------

[!] No passwords found

 ------------------- Vault passwords -----------------

[+] Password found !!!
URL: https://login.live.com/
Login: wwwwwwwwww
Name: Internet Explorer
Password: tttttttttttttt

 ------------------- Windows passwords -----------------
  ,and ,so on,

  ------------------- Credfiles passwords -----------------

[!] No passwords found

 ------------------- Vaultfiles passwords -----------------

[!] Traceback (most recent call last):
  File "C:\lazena\Windows\lazagne\config\run.py", line 45, in run_module
    pwd_found = module.run()  # run the module
  File "C:\lazena\Windows\lazagne\softwares\windows\vaultfiles.py", line 19, in run
    cred = constant.user_dpapi.decrypt_vault(os.path.join(main_vault_directory, vault_directory))
  File "C:\lazena\Windows\lazagne\config\dpapi_structure.py", line 124, in decrypt_vault
    ok, msg = v.decrypt(mkp=self.umkp)
  File "C:\lazena\Windows\lazagne\config\DPAPI\vault.py", line 447, in decrypt
    vcrd = VaultVcrd(fin.read())
  File "C:\lazena\Windows\lazagne\config\DPAPI\vault.py", line 193, in __init__
    DataStruct.__init__(self, raw)
  File "C:\lazena\Windows\lazagne\config\DPAPI\eater.py", line 124, in __init__
    self.parse(Eater(raw, endianness="<"))
  File "C:\lazena\Windows\lazagne\config\DPAPI\vault.py", line 205, in parse
    for i in range(self.attributes_num):
TypeError: 'float' object cannot be interpreted as an integer

########## User: Administrator ##########
  ,and so on,
[+] 11 passwords have been found.

elapsed time = 14.363672733306885

Then I ran , lazagne with ; python "C:\lazena\Windows\laZagne.py" all -vvv
and results are the very same.

I'm just adding this info to the issue,if of any help.

Thanks.

**Comment by MyLoginOnGitHub** [comment]
@Papotito123, yes. it would helps. Thanks!!
Could you please run the following code: #462 and reply if the exception in _Vaultfiles passwords_ is still occurres?

**Comment by byehack** [comment]
> @Papotito123, yes. it would helps. Thanks!!
> Could you please run the following code: #462 and reply if the exception in _Vaultfiles passwords_ is still occurres?

this error is from `winstructures.py`. fixed in https://github.com/byehack/LaZagne .@MyLoginOnGitHub  if you want you can use changed code to send a new PR.

**Comment by AlessandroZ** [comment]
I have added your commit (https://github.com/byehack/LaZagne/commit/fa1ddaef180dd5c677d7cf9bd66154b358c6b733#diff-0a62f4ada3e9aa7303755c12ec20e3e8) to the code and fix some bug. Now, Vaulfiles are well decrypted when you have the user password.

Tested on python2 and python 3 on Win10

Thanks

**Comment by byehack** [comment]
> Tested on python2 and python 3 on Win10

still not worked and crashed again with your last commit and py3.8-64bit in win10-64bit with `-password` prameter and in cmd admin:
[lazagne_output.txt](https://github.com/AlessandroZ/LaZagne/files/4014655/lazagne_output.txt)

**Comment by byehack** [comment]
problem is from `winstructures.py`. see my changed codes in my fork, you should change some `Structures` classes /: my fork not crash on getting `Vault passwords`.

**Comment by AlessandroZ** [comment]
Ok, I just added your changes from winstructure. It should not crash. 

The thing is we are not talking about the same module. I didn't see the crash because I didn't find a stacktrace but I suppose, you got a pop up saying that the program crashed which is worst. This module use the Windows API so no need to use `-password`. However, we are not able to recover domain passwords, etc. 

This can be done using de `vaultfiles` module which check for vaultfiles. This work only if you have the user password or if it find a way to recover it from another module. And this one works for me on python 2 and python 3 now. 

I didn't had rdp files stored so I didn't do this check. However, other passwords stored had been recovered well.

**Comment by byehack** [comment]
i have a hard debugging on your project and my problem was the lazagne crashed on py3 at `Vault passwords`. on py2 i don't have this problem. but still in the py2 doesn't recover passwords.
when i changed the `winstructures.py`, i tested it on py2 and py3.
on py2 it can now recover the `RC4` password just.
but on py3 it cannot recover `RC4` but it recovers some other like `sychic` passwords.

when i was debugging `cbVaults.value` was `2`:
https://github.com/AlessandroZ/LaZagne/blob/82193b2f20ed9f54dd10de75598f472ee568dd42/Windows/lazagne/softwares/windows/vault.py#L31

so i think because we have 2 different credintials: 
## 1. web creds:
![image](https://user-images.githubusercontent.com/26390254/71647936-a048ac80-2d12-11ea-86ea-e1fdb0b03c31.png)
## 2. windows creds:
![image](https://user-images.githubusercontent.com/26390254/71647952-1220f600-2d13-11ea-8295-961cd4ac1eae.png)

with change the `winstructures.py` i could get `web creds`. but `windows creds` not!
thanks! i hope you know now!

**Comment by AlessandroZ** [comment]
I think, you should find these creds decrypting creds file. Check this doing
```
lazagne.py windows -credfiles -password <pwd>
```
I don't know if this is a problem, or a normal behavior from the API. But I think, the APi does not return all passwords in cleartext like so, it depends on the category if I remember well.

**Comment by byehack** [comment]
> lazagne.py windows -credfiles -password <pwd>

i know, but i want the some rdp passwords and i know i can't get them in` windows -credfiles`.

**Comment by AlessandroZ** [comment]
For me, rdp passwords are stored inside an rdp config file as a ciphered blob. The file could be stored anywhere on the disk. 

Maybe this is no more like that. I do not have an rdp activated to do that test right now, so I cannot help you on this point. :(

**Comment by Papotito123** [comment]
hello:
I run latest lazagne(Merge branch 'master' of https://github.com/AlessandroZ/LaZagne) with laZagne.py windows -credfiles -password mypassword:

C:\Users\TESTACCOUNT\Desktop\Python37>"C:\lazy\Windows\laZagne.py" windows -credfiles -password mypassword

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

[+] System masterkey decrypted for 08be8fec-13ca-4ae0-8341-36b907e33d19
[+] System masterkey decrypted for 15e43b11-4cee-437f-928e-082807c02474
[+] System masterkey decrypted for 1e8bc276-41f3-493f-8fb4-32496443bb79
[+] System masterkey decrypted for 4e79d188-0323-4c0b-9796-0d9ffc89f045
[+] System masterkey decrypted for 55aa46c8-2bc6-496a-8888-482c24891036
[+] mypassword ok for masterkey 30b657d4-fe73-47c0-af94-7b2291f61463
[+] mypassword ok for masterkey 3fdc4908-7639-4245-848e-b87fdd7b1cc9
[+] mypassword ok for masterkey 6d9a5591-8966-4c86-a354-a44c33a272db
[+] mypassword ok for masterkey 7a404da4-b4d0-4d96-973e-5bad1b705b01
[+] mypassword ok for masterkey bcec4086-ba45-4130-9165-23b6ba696cef

########## User: TESTACCOUNT ##########

------------------- Credfiles passwords -----------------

[+] Password found !!!
File: C:\Users\TESTACCOUNT\AppData\Roaming\Microsoft\Credentials\A6F8B67F4EE2434D447B1CE77E590E6A
Domain: Domain:target=DESKTOP-WINVIRT
Username: testuser
Password: @ccountf0rtesT


[+] 1 passwords have been found.
For more information launch it again with the -v option

elapsed time = 13.781094312667847

C:\Users\TESTACCOUNT\Desktop\Python37>
 
This account is for vbox Windoows 10 1809 x64 VM.
Is showing below Credential Manager > Windows Credentials > Windows Credentials > Internet or Network Address 
The Password is showing as dots.I assume is encrypted.
But this latest lazagne recoverd well.Also tested with NetworkPasswordDecryptor.

Just to add info to the discussion.

Thanks.

**Comment by byehack** [comment]
> I run latest lazagne(Merge branch 'master' of https://github.com/AlessandroZ/LaZagne) with laZagne.py windows -credfiles -password mypassword:

vaultfiles also working?

test `laZagne.py all -password mypassword -vvv` in cmd admin with py3-64bit see is still working??
