### ISSUE TITLE
webhook

### ISSUE THREAD

**Issue by nongiach** [AlessandroZ/LaZagne#465]
Hi,

Nice tool.
It would be interesting to grep all webhook with something like "http.*webhook"
It would grab for example discord webhooks.

Happy New Year.

**Comment by AlessandroZ** [comment]
Hi, 

Sorry for my late answer. Right now I don't have time to work on new modules but if you want to add it, you can :)

Have a nice day.

**Comment by 0xspade** [comment]
@nongiach,

Did you ever had a chance to implement this one?
