### ISSUE TITLE
This app can't run on your PC

### ISSUE THREAD

**Issue by abyssals** [AlessandroZ/LaZagne#467]
I apologize for what I assume is an incredibly newbie question.
I've downloaded the latest exe for LaZagne and have also successfully installed everything in the requirements.txt. I am running Python 2.7.16.
Every time I attempt to run the exe file, my computer gives me a message that reads:

"This app can't run on your PC
To find a version for your PC, check with the software publisher."
(It only gives me a button to close.)

How do I fix this? I've even toggled off my Firewall and other virus protection and still receive the same message.

**Comment by byehack** [comment]
is your pc is a 32bit pc?

try to install python & pyinstaller and get latest lazagne source code from github and try to convert it to exe file.

**Comment by abyssals** [comment]
Both of my PCs are 64bit.

I did what you recommended and successfully made an executable file, but now I'm running into an issue where if I attempt to use the exe it opens up the command window briefly, no text shows up, before if immediately closes on its own and nothing happens.

**Comment by byehack** [comment]
> no text shows up, before if immediately closes on its own and nothing happens.

u should run the lazagne in cmd
create a cmd and goto lazagne.exe directory and enter:`lazagne -h`

**Comment by byehack** [comment]
this is not a problem and you can close this issue!
