### ISSUE TITLE
export to csv

### ISSUE THREAD

**Issue by atao** [AlessandroZ/LaZagne#47]
Is it possible to add the export in csv file?

**Comment by AlessandroZ** [comment]
At this moment, it is not possible. 
However, maybe I will do it, but right now, I don't really see the utility. I let the issue as open to do it when I will have more time.

**Comment by 0E800** [comment]
lazagna all > creds.txt

Usse Excel magic
Data -> From Text

I tried separating by tab and space but im sure with a little editing or
someone with better experience in Excel could do it better than I.

On Sun, Oct 4, 2015 at 4:02 AM, AlessandroZ <notifications@github.com>
wrote:

> At this moment, it is not possible.
> However, maybe I will do it, but right now, I don't really see the
> utility. I let the issue as open to do it when I will have more time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AlessandroZ/LaZagne/issues/47#issuecomment-145336770>.
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>

**Comment by AlessandroZ** [comment]
I have done a json output on the new version (1.3). 
`LaZagne.exe all -oJ `

It is not to read via excel but it is easy to realize a parser for Json files.
