### ISSUE TITLE
WindowsError: exception: access violation reading

### ISSUE THREAD

**Issue by scouteh** [AlessandroZ/LaZagne#473]
Hey, I ran lazagne using all -vvv and got the error (WindowsError: exception: access violation reading) for chrome.

**Comment by byehack** [comment]
are you using the github latest update?

**Comment by scouteh** [comment]
Yes I am.

**Comment by byehack** [comment]
try to make a one-app with pyinstaller with this source: https://github.com/AlessandroZ/LaZagne/archive/master.zip

then try! because as i remember this error fixed.

**Comment by scouteh** [comment]
ValueError: MasterKeys not found?

**Comment by scouteh** [comment]
Thanks! It fixed it!

**Comment by scouteh** [comment]
Hmm.... It's taking a lot of time even tho I'm running only browsers, it's been like 5 minutes and nothing has appeared.

**Comment by scouteh** [comment]
It's now working! Thanks :)
