### ISSUE TITLE
Doesnt work on Chrome Version 80.0.3987.100

### ISSUE THREAD

**Issue by TheMagicSkY** [AlessandroZ/LaZagne#475]
Hi, doesnt work on Google Chrome Version 80.0.3987.100, it doesnt get the stored credentials, thanks!

**Comment by byehack** [comment]
send me result of this command:
`lazagne browsers -vvv`

**Comment by Papotito123** [comment]
Hello:
TheMagicSkY , For me is doing good.

Google Chrome is up to date
Version 80.0.3987.116 (Official Build) (64-bit)

C:\python37>"C:\lazagne\Windows\laZagne.py" -version
Version 2.4.3

C:\python37>"C:\lazagne\Windows\laZagne.py" all -vvv
|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

[!] Python 3.7.6 on Windows AMD64: Intel64 Family 6 Model 30 Stepping 5, GenuineIntel

     ``````````   and so on  `````````

 ------------------- Epic privacy browser passwords -----------------

[!] No passwords found

 ------------------- Google chrome passwords -----------------

[!] Database found: C:\Users\TESTACCOUNT\AppData\Local\Google\Chrome\User Data\Default\Login Data
[!] Temporary db copied: C:\Users\TESTAC~1\AppData\Local\Temp\pbuwaiqib
[+] Password found !!!
URL: https://login.live.com/ppsecure/post.srf
Login: zzzzzzzzz@outlook.com
Password: xxxxxxxxx

[+] Password found !!!
URL: https://login.live.com/ppsecure/post.srf
Login: zzzzzzzz@hotmail.com
Password: xxxxxxx

[+] Password found !!!
URL: https://login.live.com/ppsecure/post.srf
Login: zzzzzzzz@hotmail.com
Password: xxxxxxxxx

[+] Password found !!!
URL: https://login.live.com/ppsecure/post.srf
Login: zzzzzzzzz@hotmail.com
Password: xxxxxxxxxx

 ------------------- Kometa passwords -----------------

[!] No passwords found

Thanks.

**Comment by eranzim** [comment]
Chrome v80 changed the way new passwords are stored. As I understand it, old stored passwords aren't re-encrypted with the new method.
See [here](https://github.com/agentzex/chrome_v80_password_grabber).

**Comment by Papotito123** [comment]
Hello:
@eranzim,Chrome 80 and up has a second key(AES) for Login Data info protection.
I updated Chrome to the very latest version and Chrome logins are recovered well.
Also tested with other password recovering tools.
Having Defender as only antivirus is a real pain because even with Real-Time OFF is still playing hard with other modules making password recovery sometimes uh unstable/erratic process.

All my Chrome passwords are pre-existent ,and I suspected that already-saved logins are affected so I will make test with Saving new passwords and will post.

**Comment by Banaanhangwagen** [comment]
Mimikatz got updated for that reason three weeks ago.
See : https://github.com/gentilkiwi/mimikatz/releases/tag/2.2.0-20200208

new things are:
- extra encrypted key in `Local State` file
- bcrypt with aes-256

**Comment by Papotito123** [comment]
Hello:
@Banaanhangwagen , I know mimikatz updated dpapi in latest versions..
That's why it got 2 Materkeys GUID names.
But,I have issues recovering other users Chrome logins.
As of lazagne , I will do tests and will post log.

**Comment by Papotito123** [comment]
Hello:
@AlessandroZ , @byehack  , and all other people.

I ran laZagne.py latest git ,and Chrome got this:
PC Win 10 1809 x64 , laZagne.py latest git

Google Chrome is up to date
Version 80.0.3987.122 (Official Build) (64-bit)
Chrome passwords: 1 pre-existent + 2 new Saved accounts(just before running laZagne.py)

1.  Running laZagne.py latest git with requirements.txt pypykatz(default),Chrome will throw errors as this:

 ------------------- Google chrome passwords -----------------

[!] Database found: C:\Users\TESTACCOUNT\AppData\Local\Google\Chrome\User Data\Default\Login Data
[!] Temporary db copied: C:\Users\TESTAC~1\AppData\Local\Temp\skruzfbab
[-] TESTACCOUNT not ok for masterkey 30b657d4-fe73-47c0-af94-7b2291f61463
[-] TESTACCOUNT not ok for masterkey 3fdc4908-7639-4245-848e-b87fdd7b1cc9
[-] TESTACCOUNT not ok for masterkey 6d9a5591-8966-4c86-a354-a44c33a272db
[-] TESTACCOUNT not ok for masterkey 7a404da4-b4d0-4d96-973e-5bad1b705b01
[-] TESTACCOUNT not ok for masterkey bcec4086-ba45-4130-9165-23b6ba696cef
[-] TESTACCOUNT not ok for masterkey c4a0a02c-95b1-4de5-98e2-35f681af0d34
[-] TESTACCOUNT not ok for masterkey cc11d09e-e1c7-48a9-964b-6fafd4b67917
[-] TESTACCOUNT not ok for masterkey fe6826cc-98e5-4748-82c2-399234faaefc
[-] xxxxxxx not ok for masterkey 30b657d4-fe73-47c0-af94-7b2291f61463
[-] xxxxxxx not ok for masterkey 3fdc4908-7639-4245-848e-b87fdd7b1cc9
[-] xxxxxxx not ok for masterkey 6d9a5591-8966-4c86-a354-a44c33a272db
[-] xxxxxxx not ok for masterkey 7a404da4-b4d0-4d96-973e-5bad1b705b01
[-] xxxxxxx not ok for masterkey bcec4086-ba45-4130-9165-23b6ba696cef
[-] xxxxxxx not ok for masterkey c4a0a02c-95b1-4de5-98e2-35f681af0d34
[-] xxxxxxx not ok for masterkey cc11d09e-e1c7-48a9-964b-6fafd4b67917
[-] xxxxxxx not ok for masterkey fe6826cc-98e5-4748-82c2-399234faaefc
[-] xxxxxxx not ok for masterkey 30b657d4-fe73-47c0-af94-7b2291f61463
[-] xxxxxxx not ok for masterkey 3fdc4908-7639-4245-848e-b87fdd7b1cc9
[-] xxxxxxx not ok for masterkey 6d9a5591-8966-4c86-a354-a44c33a272db
[-] xxxxxxx not ok for masterkey 7a404da4-b4d0-4d96-973e-5bad1b705b01
[-] xxxxxxx not ok for masterkey bcec4086-ba45-4130-9165-23b6ba696cef
[-] xxxxxxx not ok for masterkey c4a0a02c-95b1-4de5-98e2-35f681af0d34
[-] xxxxxxx not ok for masterkey cc11d09e-e1c7-48a9-964b-6fafd4b67917
[-] xxxxxxx not ok for masterkey fe6826cc-98e5-4748-82c2-399234faaefc
[-] xxxxxxx  not ok for masterkey 30b657d4-fe73-47c0-af94-7b2291f61463
[-] xxxxxxx  not ok for masterkey 3fdc4908-7639-4245-848e-b87fdd7b1cc9
[-] xxxxxxx  not ok for masterkey 6d9a5591-8966-4c86-a354-a44c33a272db
[-] xxxxxxx  not ok for masterkey 7a404da4-b4d0-4d96-973e-5bad1b705b01
[-] xxxxxxx  not ok for masterkey bcec4086-ba45-4130-9165-23b6ba696cef
[-] xxxxxxx  not ok for masterkey c4a0a02c-95b1-4de5-98e2-35f681af0d34
[-] xxxxxxx  not ok for masterkey cc11d09e-e1c7-48a9-964b-6fafd4b67917
[-] xxxxxxx  not ok for masterkey fe6826cc-98e5-4748-82c2-399234faaefc
[!] Traceback (most recent call last):
  File "C:\laza\Windows\lazagne\softwares\browsers\chromium_based.py", line 116, in _export_credentials
    user_dpapi=constant.user_dpapi)
  File "C:\laza\Windows\lazagne\config\winstructure.py", line 629, in Win32CryptUnprotectData
    raise ValueError('MasterKeys not found')
ValueError: MasterKeys not found

[-] TESTACCOUNT not ok for masterkey 30b657d4-fe73-47c0-af94-7b2291f61463
[-] TESTACCOUNT not ok for masterkey 3fdc4908-7639-4245-848e-b87fdd7b1cc9
[-] TESTACCOUNT not ok for masterkey 6d9a5591-8966-4c86-a354-a44c33a272db
[-] TESTACCOUNT not ok for masterkey 7a404da4-b4d0-4d96-973e-5bad1b705b01
[-] TESTACCOUNT not ok for masterkey bcec4086-ba45-4130-9165-23b6ba696cef
[-] TESTACCOUNT not ok for masterkey c4a0a02c-95b1-4de5-98e2-35f681af0d34
[-] TESTACCOUNT not ok for masterkey cc11d09e-e1c7-48a9-964b-6fafd4b67917
[-] TESTACCOUNT not ok for masterkey fe6826cc-98e5-4748-82c2-399234faaefc
[-] xxxxxxx not ok for masterkey 30b657d4-fe73-47c0-af94-7b2291f61463
[-] xxxxxxx not ok for masterkey 3fdc4908-7639-4245-848e-b87fdd7b1cc9
[-] xxxxxxx not ok for masterkey 6d9a5591-8966-4c86-a354-a44c33a272db
[-] xxxxxxx not ok for masterkey 7a404da4-b4d0-4d96-973e-5bad1b705b01
[-] xxxxxxx not ok for masterkey bcec4086-ba45-4130-9165-23b6ba696cef
[-] xxxxxxx not ok for masterkey c4a0a02c-95b1-4de5-98e2-35f681af0d34
[-] xxxxxxx not ok for masterkey cc11d09e-e1c7-48a9-964b-6fafd4b67917
[-] xxxxxxx not ok for masterkey fe6826cc-98e5-4748-82c2-399234faaefc
[-] xxxxxxx not ok for masterkey 30b657d4-fe73-47c0-af94-7b2291f61463
[-] xxxxxxx not ok for masterkey 3fdc4908-7639-4245-848e-b87fdd7b1cc9
[-] xxxxxxx not ok for masterkey 6d9a5591-8966-4c86-a354-a44c33a272db
[-] xxxxxxx not ok for masterkey 7a404da4-b4d0-4d96-973e-5bad1b705b01
[-] xxxxxxx not ok for masterkey bcec4086-ba45-4130-9165-23b6ba696cef
[-] xxxxxxx not ok for masterkey c4a0a02c-95b1-4de5-98e2-35f681af0d34
[-] xxxxxxx not ok for masterkey cc11d09e-e1c7-48a9-964b-6fafd4b67917
[-] xxxxxxx not ok for masterkey fe6826cc-98e5-4748-82c2-399234faaefc
[-] xxxxxxx  not ok for masterkey 30b657d4-fe73-47c0-af94-7b2291f61463
[-] xxxxxxx  not ok for masterkey 3fdc4908-7639-4245-848e-b87fdd7b1cc9
[-] xxxxxxx  not ok for masterkey 6d9a5591-8966-4c86-a354-a44c33a272db
[-] xxxxxxx  not ok for masterkey 7a404da4-b4d0-4d96-973e-5bad1b705b01
[-] xxxxxxx  not ok for masterkey bcec4086-ba45-4130-9165-23b6ba696cef
[-] xxxxxxx  not ok for masterkey c4a0a02c-95b1-4de5-98e2-35f681af0d34
[-] xxxxxxx  not ok for masterkey cc11d09e-e1c7-48a9-964b-6fafd4b67917
[-] xxxxxxx  not ok for masterkey fe6826cc-98e5-4748-82c2-399234faaefc
[!] Traceback (most recent call last):
  File "C:\laza\Windows\lazagne\softwares\browsers\chromium_based.py", line 116, in _export_credentials
    user_dpapi=constant.user_dpapi)
  File "C:\laza\Windows\lazagne\config\winstructure.py", line 629, in Win32CryptUnprotectData
    raise ValueError('MasterKeys not found')
ValueError: MasterKeys not found

[-] TESTACCOUNT not ok for masterkey 30b657d4-fe73-47c0-af94-7b2291f61463
[-] TESTACCOUNT not ok for masterkey 3fdc4908-7639-4245-848e-b87fdd7b1cc9
[-] TESTACCOUNT not ok for masterkey 6d9a5591-8966-4c86-a354-a44c33a272db
[-] TESTACCOUNT not ok for masterkey 7a404da4-b4d0-4d96-973e-5bad1b705b01
[-] TESTACCOUNT not ok for masterkey bcec4086-ba45-4130-9165-23b6ba696cef
[-] TESTACCOUNT not ok for masterkey c4a0a02c-95b1-4de5-98e2-35f681af0d34
[-] TESTACCOUNT not ok for masterkey cc11d09e-e1c7-48a9-964b-6fafd4b67917
[-] TESTACCOUNT not ok for masterkey fe6826cc-98e5-4748-82c2-399234faaefc
[-] xxxxxxx not ok for masterkey 30b657d4-fe73-47c0-af94-7b2291f61463
[-] xxxxxxx not ok for masterkey 3fdc4908-7639-4245-848e-b87fdd7b1cc9
[-] xxxxxxx not ok for masterkey 6d9a5591-8966-4c86-a354-a44c33a272db
[-] xxxxxxx not ok for masterkey 7a404da4-b4d0-4d96-973e-5bad1b705b01
[-] xxxxxxx not ok for masterkey bcec4086-ba45-4130-9165-23b6ba696cef
[-] xxxxxxx not ok for masterkey c4a0a02c-95b1-4de5-98e2-35f681af0d34
[-] xxxxxxx not ok for masterkey cc11d09e-e1c7-48a9-964b-6fafd4b67917
[-] xxxxxxx not ok for masterkey fe6826cc-98e5-4748-82c2-399234faaefc
[-] xxxxxxx not ok for masterkey 30b657d4-fe73-47c0-af94-7b2291f61463
[-] xxxxxxx not ok for masterkey 3fdc4908-7639-4245-848e-b87fdd7b1cc9
[-] xxxxxxx not ok for masterkey 6d9a5591-8966-4c86-a354-a44c33a272db
[-] xxxxxxx not ok for masterkey 7a404da4-b4d0-4d96-973e-5bad1b705b01
[-] xxxxxxx not ok for masterkey bcec4086-ba45-4130-9165-23b6ba696cef
[-] xxxxxxx not ok for masterkey c4a0a02c-95b1-4de5-98e2-35f681af0d34
[-] xxxxxxx not ok for masterkey cc11d09e-e1c7-48a9-964b-6fafd4b67917
[-] xxxxxxx not ok for masterkey fe6826cc-98e5-4748-82c2-399234faaefc
[-] xxxxxxx  not ok for masterkey 30b657d4-fe73-47c0-af94-7b2291f61463
[-] xxxxxxx  not ok for masterkey 3fdc4908-7639-4245-848e-b87fdd7b1cc9
[-] xxxxxxx  not ok for masterkey 6d9a5591-8966-4c86-a354-a44c33a272db
[-] xxxxxxx  not ok for masterkey 7a404da4-b4d0-4d96-973e-5bad1b705b01
[-] xxxxxxx  not ok for masterkey bcec4086-ba45-4130-9165-23b6ba696cef
[-] xxxxxxx  not ok for masterkey c4a0a02c-95b1-4de5-98e2-35f681af0d34
[-] xxxxxxx  not ok for masterkey cc11d09e-e1c7-48a9-964b-6fafd4b67917
[-] xxxxxxx  not ok for masterkey fe6826cc-98e5-4748-82c2-399234faaefc
[!] Traceback (most recent call last):
  File "C:\laza\Windows\lazagne\softwares\browsers\chromium_based.py", line 116, in _export_credentials
    user_dpapi=constant.user_dpapi)
  File "C:\laza\Windows\lazagne\config\winstructure.py", line 629, in Win32CryptUnprotectData
    raise ValueError('MasterKeys not found')
ValueError: MasterKeys not found

2. Running laZagne.py latest git with pypykatz 0.3.5(latest code),Chrome will throw errors as this:

 ------------------- Google chrome passwords -----------------

[!] Database found: C:\Users\TESTACCOUNT\AppData\Local\Google\Chrome\User Data\Default\Login Data
[!] Temporary db copied: C:\Users\TESTAC~1\AppData\Local\Temp\alryqclll
[+] myuserpassword ok for masterkey 30b657d4-fe73-47c0-af94-7b2291f61463
[+] myuserpassword ok for masterkey 3fdc4908-7639-4245-848e-b87fdd7b1cc9
[+] myuserpassword ok for masterkey 6d9a5591-8966-4c86-a354-a44c33a272db
[+] myuserpassword ok for masterkey 7a404da4-b4d0-4d96-973e-5bad1b705b01
[+] myuserpassword ok for masterkey bcec4086-ba45-4130-9165-23b6ba696cef
[+] myuserpassword ok for masterkey c4a0a02c-95b1-4de5-98e2-35f681af0d34
[-] myuserpassword not ok for masterkey cc11d09e-e1c7-48a9-964b-6fafd4b67917
[-] myuserpassword not ok for masterkey fe6826cc-98e5-4748-82c2-399234faaefc
[!] Traceback (most recent call last):
  File "C:\laza\Windows\lazagne\softwares\browsers\chromium_based.py", line 116, in _export_credentials
    user_dpapi=constant.user_dpapi)
  File "C:\laza\Windows\lazagne\config\winstructure.py", line 625, in Win32CryptUnprotectData
    decrypted = user_dpapi.decrypt_encrypted_blob(cipherText)
AttributeError: 'NoneType' object has no attribute 'decrypt_encrypted_blob'

[!] Traceback (most recent call last):
  File "C:\laza\Windows\lazagne\softwares\browsers\chromium_based.py", line 116, in _export_credentials
    user_dpapi=constant.user_dpapi)
  File "C:\laza\Windows\lazagne\config\winstructure.py", line 625, in Win32CryptUnprotectData
    decrypted = user_dpapi.decrypt_encrypted_blob(cipherText)
  File "C:\laza\Windows\lazagne\config\dpapi_structure.py", line 132, in decrypt_encrypted_blob
    blob = DPAPIBlob(ciphered)
  File "C:\laza\Windows\lazagne\config\DPAPI\blob.py", line 49, in __init__
    DataStruct.__init__(self, raw)
  File "C:\laza\Windows\lazagne\config\DPAPI\eater.py", line 124, in __init__
    self.parse(Eater(raw, endianness="<"))
  File "C:\laza\Windows\lazagne\config\DPAPI\blob.py", line 66, in parse
    self.mkguid = b"%08x-%04x-%04x-%02x%02x-%02x%02x%02x%02x%02x%02x" % data.eat("L2H8B")
  File "C:\laza\Windows\lazagne\config\DPAPI\eater.py", line 66, in eat
    v = struct.unpack_from(fmt, self.raw, self.ofs)
struct.error: unpack_from requires a buffer of at least 16 bytes

[!] Traceback (most recent call last):
  File "C:\laza\Windows\lazagne\softwares\browsers\chromium_based.py", line 116, in _export_credentials
    user_dpapi=constant.user_dpapi)
  File "C:\laza\Windows\lazagne\config\winstructure.py", line 625, in Win32CryptUnprotectData
    decrypted = user_dpapi.decrypt_encrypted_blob(cipherText)
  File "C:\laza\Windows\lazagne\config\dpapi_structure.py", line 132, in decrypt_encrypted_blob
    blob = DPAPIBlob(ciphered)
  File "C:\laza\Windows\lazagne\config\DPAPI\blob.py", line 49, in __init__
    DataStruct.__init__(self, raw)
  File "C:\laza\Windows\lazagne\config\DPAPI\eater.py", line 124, in __init__
    self.parse(Eater(raw, endianness="<"))
  File "C:\laza\Windows\lazagne\config\DPAPI\blob.py", line 67, in parse
    self.flags = data.eat("L")
  File "C:\laza\Windows\lazagne\config\DPAPI\eater.py", line 66, in eat
    v = struct.unpack_from(fmt, self.raw, self.ofs)
struct.error: unpack_from requires a buffer of at least 4 bytes

Then I ran mimikatz and recovered all well.

Just info for the troubleshoot.

Thanks.

**Comment by byehack** [comment]
@Papotito123 can u send me results of testing : https://github.com/agentzex/chrome_v80_password_grabber

**Comment by Papotito123** [comment]
Hello:
@byehack , this tools grabs Chrome 80 well.

Google Chrome is up to date
Version 80.0.3987.122 (Official Build) (64-bit)
Chrome passwords: 1 pre-existent + 2 new Saved accounts

Microsoft Windows [Version 10.0.17763.1039]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Windows\system32>cd "C:\python37"

C:\python37>python "C:\Users\TESTACCOUNT\Downloads\Chrome v80_password_grabber\chrome_v80_password_grabber-master\chrome_v80_password_grabber-master\chrome_v80_password_grabber.py"
URL: https://login.live.com/ppsecure/post.srf
User Name: zzzzzzzzzz@hotmail.com
Password: xxxxxxxxx
**************************************************

URL: https://login.live.com/ppsecure/post.srf
User Name: zzzzzzzz@hotmail.com
Password: xxxxxxxxx
**************************************************

URL: https://login.live.com/ppsecure/post.srf
User Name: zzzzzzzzz@outlook.com
Password: xxxxxxxx
**************************************************

I don't know how to run in debug mode.

**Comment by byehack** [comment]
hello i tested [this script](https://github.com/agentzex/chrome_v80_password_grabber) too.
this script cannot dump "chrome version < 80". 
but in your log all three passwords are dumped. i think you added all of your passwords in chrome >80.
so can you try get chrome passwords with my latest repo ?
because i will add the changes in my repo, i want to know my repo error to fix it.

**Comment by byehack** [comment]
i tested with my repo you dont need to test. i will fix it soon...

**Comment by Papotito123** [comment]
Hello:
nirsoft do well also , https://www.nirsoft.net/utils/chromepass.html

**Comment by byehack** [comment]
it seems we should include "Crypto" module for "AES-256-GCM" decrypt.

**Comment by byehack** [comment]
hello again.
@Papotito123 i updated my repo with https://github.com/byehack/LaZagne/commit/e148aab265ed19c9709b8052b80a1ac4dca7e58a
can u test with my repo ang give me the logs?
<for use my repo you should have ("cryptography" or "pycrypto" or "pycryptodome" or "pycryptodomex"). these are support `AES` well.>

**Comment by Banaanhangwagen** [comment]
@byehack 
your update works as expected; good job!
(tested with +v80 saved pwd)

```
laZagne.py browsers

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

[+] System masterkey decrypted for 6521fdaf-e1c6-4c3e-b96b-xxx
[+] System masterkey decrypted for 29fd8c86-f1c8-4729-bcbe-xxx
[+] System masterkey decrypted for 4be7419a-61fe-4148-b674-xxx
[+] System masterkey decrypted for be39a61f-e3ba-41d9-b531-xxx
[+] System masterkey decrypted for 7a06d166-8926-442a-9b75-xxx
[+] System masterkey decrypted for 0b9bec7e-9b18-48be-9411-xxx
[+] System masterkey decrypted for edccf7dd-17d0-45d1-a792-xxx

########## User: xxx ##########
------------------- Google chrome passwords -----------------

[+] Password found !!!
URL: https://login.live.com/ppsecure/post.srf
Login: xxx@hotmail.com
Password: xxxxxx


[+] 1 password have been found.
For more information launch it again with the -v option

elapsed time = 4.28999996185
```

**Comment by byehack** [comment]
i think you can close this issue now
