### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by AlessandroZ** [AlessandroZ/LaZagne#477]
This issue is for @byehack. 

I have merge almost all your changes but I don't understand some modification you have done: 
- https://github.com/byehack/LaZagne/commit/dbe48b825e2830711cbc5324fd40bd97d2171e72: 
Have you encountered a credential type equal to 2 ? It does not create an error once parsed ? 

- Both condition are identical, so maybe you meant to write another thing :) ? https://github.com/byehack/LaZagne/commit/a085f03e89cd9a200dd81a682236fadd25bedc7d#diff-6b46e850fbe7277e952cba66808e3533

- Do you had some problem with this try/except ? https://github.com/byehack/LaZagne/commit/a085f03e89cd9a200dd81a682236fadd25bedc7d#diff-5e017bc5029b5f4e4c52eaf49e9b85ce

- Does it work ?https://github.com/byehack/LaZagne/blob/ed7089f0edd27687ca12f5f41007512f87387889/Windows/lazagne/softwares/windows/credfiles.py#L17. Because to decrypt system creds, you could not do it using a classic user masterkey, it should be done from the system user, so it should be a system module (as lsa secrets: https://github.com/byehack/LaZagne/blob/ed7089f0edd27687ca12f5f41007512f87387889/Windows/lazagne/softwares/windows/lsa_secrets.py#L12). 

Thanks for all your work, I appreciate a lot.

**Comment by byehack** [comment]
hello @AlessandroZ.
when i was editing these codes, only god and i know what are they doing!
now only god knows.

i think is better to trust me!

Thanks.
