### ISSUE TITLE
browsers passwords don't showing

### ISSUE THREAD

**Issue by 11236** [AlessandroZ/LaZagne#480]
laZagne 2.4.3.exe (in windows) that only shows wifi passwords, though i used *all command no browsers or system pass founds, help me out!

**Comment by Papotito123** [comment]
Hello:
If you didn't Saved passwords with Saved button in browser ,there's nothing to rerieved.
So be sure that you have saved passwords.
User passwords are not saved in plain-text from Windows 8.1.

lazagne 2.4.3.exe(september) has some issues that are fixed and made to the python code.
Chrome saved passwords are bot recovered in this 2.4.3 version.

Latest code are working really good.
If you know to compile laZagne.py to .exe  ,you can have latest good working version.

I have to learn a lot.
But is can be make.

**Comment by 11236** [comment]
yap thanks :-)

**Comment by AlessandroZ** [comment]
A new release will be uploaded soon.
