### ISSUE TITLE
no passwords on Ubuntu

### ISSUE THREAD

**Issue by sh1va73** [AlessandroZ/LaZagne#485]
I been testing LaZagne on different devices. On Windows 10, I just the standalone and it works perfect. But on Ubuntu 18.04 no passwords are found. I tried saving passwords with Firefox and Chrome. But no results on Ubuntu.

**Comment by AlessandroZ** [comment]
I have checked right now on the same linux and works for me. 

We have some problems with the latest firefox version (https://github.com/AlessandroZ/LaZagne/issues/491) and for chrome (https://github.com/AlessandroZ/LaZagne/issues/489), as explained here should work using `python laZagne.py all`
