### ISSUE TITLE
Chrome v80 passwords on Linux

### ISSUE THREAD

**Issue by plonibarploni** [AlessandroZ/LaZagne#489]
Using the latest LaZagne on Linux, passwords saved with v80 of Chrome are not recovered. It appears that the encryption method has changed.

**Comment by AlessandroZ** [comment]
To get chrome passwords on a linux, the "Chromium Safe Storage" key should be retrieved first. It's present on your system wallet. Check on your "Libsecret" module if this key has been found first. 

You should not see your chrome passwords using the browsers module only (eg `python laZagne.py browsers`), but it should appears when you launch all modules (`python laZagne.py all`)

Check again using `python laZagne.py all` 

I have just done the test right now and it works for me.

**Comment by dodatdi** [comment]
Can you help me? #488

**Comment by plonibarploni** [comment]
I ran `laZagne.py all` and got no results. I should add that this is a fresh install of Chrome, upgrades from older versions may not be affected.

**Comment by plonibarploni** [comment]
> To get chrome passwords on a linux, the "Chromium Safe Storage" key should be retrieved first. It's present on your system wallet. Check on your "Libsecret" module if this key has been found first.

The reason it's not being found is because it's called "**Chrome** Safe Storage".
