### ISSUE TITLE
Extract user interface password hashes for antivirus software

### ISSUE THREAD

**Issue by tautology0** [AlessandroZ/LaZagne#49]
A couple of the AV products store their user interface passwords in the registry with either no, or a static salt:

Kaspersky is stored in HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\KasperskyLab\protected\KSOS13\settings\OPEP as a static, unsalted MD5 hash. (see http://seclists.org/bugtraq/2015/Oct/6)

McAfee is stored in HKLM\SOFTWARE\McAfee\DesktopProtection\UIPEx as a base64'd unicode MD5 hash with a static salt. (see https://www.pentestpartners.com/blog/grab-the-ui-lock-password-from-mcafee-av-kill-the-service-send-in-the-malware/)

Both of these hashes can then be extract, passed through to hashcat and then used to disable the AV.

**Comment by AlessandroZ** [comment]
It could be interesting. I will do it when I will have more time. Thanks for sharing the information.
