### ISSUE TITLE
Error Lazagne "Failed to execute script Lazagne"

### ISSUE THREAD

**Issue by UserLanser** [AlessandroZ/LaZagne#492]
C:\Users\Влад>F:\laZagne.exe browsers  

Traceback (most recent call last):  
File "laZagne.py", line 423, in <module>   
File "laZagne.py", line 267, in runLaZagne   
File "laZagne.py", line 226, in set_env_variables 
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128) [105656] Failed to execute script laZagne

(Im on Windows and Linux)

**Comment by Papotito123** [comment]
Hello:
Win 10 1809 x64.
Python 3.7.16 x64.

I compiled latest git and worked well,also for latest Firefox.

I faced this error in past.So I moved to py3 x64.
And as now,I let requirements.txt download what it needs.
And download pyinstaller for compiling.

**Comment by AlessandroZ** [comment]
Yeah the last release it's very old and not represent the last version. The git version should be always used.
