### ISSUE TITLE
Get passwords stored by Avira Free Antivirus

### ISSUE THREAD

**Issue by eranzim** [AlessandroZ/LaZagne#495]
Apparently Avira Free Antivirus has a component that collects browser passwords. Could be worth to take a look and see if they do anything interesting there that can be integrated into LaZagne. Alternatively, if it is installed on the computer, it's possible to run it and see if it finds passwords that LaZagne didn't (make a union of the two sets).

This seems like an optional low priority enhancement, but thought it was worth noting here.

Source: https://medium.com/@knikolenko/avira-free-antivirus-password-collector-83452fa7f943

**Comment by AlessandroZ** [comment]
Hi, thanks for your request. I'm not planned to add other modules except if someone wants to to do it and wants to do a pull request. 
However, your link does not work anymore. If you have another one, it could be cool. Thanks.

**Comment by Papotito123** [comment]
Hello:
I saw the article.But later when get back to make a copy, was gone.
What is to worry is the way this passwords can be kept in this AV.
Can be used for not-so-etical purposes.

**Comment by Papotito123** [comment]
Hello:
https://knikolenko.blogspot.com/2020/05/avira-free-antivirus-password-collector.html?m=1

**Comment by AlessandroZ** [comment]
I have read the article and it does not talk about how Avira store its own password but how it collects all browsers passwords. 
So nothing to implement here. I close the issue.
