### ISSUE TITLE
MsEdge based on Chromium

### ISSUE THREAD

**Issue by Lion0823** [AlessandroZ/LaZagne#498]
Hi,

Thanks for the great job!

Could you pls add MsEdge support (Microsoft browser based on Chromium).

Thanks!

**Comment by AlessandroZ** [comment]
If it's chromium based the path could be added to this tab: https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/browsers/chromium_based.py#L223

If someone wants to add it, feel free. Right now I don't have time to test it. Sorry

**Comment by hxr404** [comment]
@Lion0823 The issue can be closed. Its now implemented.
