### ISSUE TITLE
Lazagne do not sent any mail.

### ISSUE THREAD

**Issue by Abhranil-Manna** [AlessandroZ/LaZagne#499]
Lazagne do not sent any mail to my email address after it executes on windows.Please help how to solve this issue.

**Comment by MyLoginOnGitHub** [comment]
Well, it shouldn't

**Comment by Abhranil-Manna** [comment]
Now what shall I do now to fix this error??Please help me to fix this issue

**Comment by MuzTank** [comment]
Well, if this sends email, I won't use it

**Comment by AlessandroZ** [comment]
The tool doesn't send any email. The output is only printed on the screen.
