### ISSUE TITLE
Can't get any passwords from browser etc.

### ISSUE THREAD

**Issue by Kolobochek** [AlessandroZ/LaZagne#502]
Hey! There are no passwords from chrome or anything.
I type python laZagne.py all, and get only my Unity Token.
I need help!

**Comment by Kolobochek** [comment]
Just checked. The same problem with exe version of the program. By the way, she can find the password for Wi-Fi, unlike the py version

**Comment by Papotito123** [comment]
Hello:
Latest binary (Sept2019) is not updated for Firefox 75 nor Chrome 80 and new.

I tested latest git and laZagne.py works well and is updated for Firefox 75 and Chrome 80 and new versions.
Also I compiled to .exe and works well.

**Comment by wooyin** [comment]
> Hello:
> Latest binary (Sept2019) is not updated for Firefox 75 nor Chrome 80 and new.
> 
> I tested latest git and laZagne.py works well and is updated for Firefox 75 and Chrome 80 and new versions.
> Also I compiled to .exe and works well.

I use Python3.7 to build the program, and it can't get any passwords from browser etc.

**Comment by wooyin** [comment]
I compiled to .exe with command 'pyinstaller -F laZagne.py', pyinstaller's version is 3.6. 
it can't get any passwords from Chrome base, but it works well with Firefox moudles.

**Comment by Kolobochek** [comment]
> Hello:
> Latest binary (Sept2019) is not updated for Firefox 75 nor Chrome 80 and new.
> 
> I tested latest git and laZagne.py works well and is updated for Firefox 75 and Chrome 80 and new versions.
> Also I compiled to .exe and works well.

There are no passwords from opera too

**Comment by Kolobochek** [comment]
Hello again! Today py version works for some reasons! MANY THANKS

**Comment by wooyin** [comment]
> Hello again! Today py version works for some reasons! MANY THANKS

Hello bro, please help me out.
