### ISSUE TITLE
Elapsed Time to Extract the Passwords is 128.46 seconds 

### ISSUE THREAD

**Issue by CyberdyneSM101** [AlessandroZ/LaZagne#505]
The Tool Works Just fine  , but the only problem is that it extracts the passwords after long amount of time more than 2 minutes is that normal because it didn't take all that time the last time i used it , Am i the only one having such issue 
Tested on : Windows 10 - Version 1909 build 18363
Runned on Cmd: python lazagne.py all
and the Compiled Version: lazagne.exe all 
both extracted the Passwords after 2 mins

**Comment by AlessandroZ** [comment]
Hi, 

You should use the last python code (not the last release). It should go much faster.
