### ISSUE TITLE
Retrive Passwords from certain location

### ISSUE THREAD

**Issue by stefanoPrimo** [AlessandroZ/LaZagne#506]
Hi, 
I've found old MacOS time machine saved on an HDD. I've found another Github project to transform it into a readable one. 
My question is: the readable SO is on my Kali machine, could I specify the path to the backup in order to retrieve some pwds? 
Thanks

**Comment by AlessandroZ** [comment]
Hi @stefanoPrimo, 

You will not be able to use the tool without modify the code. I had done a project to respond to this kind of problem but it's not up to date anymore: https://github.com/AlessandroZ/LaZagneForensic
