### ISSUE TITLE
How do you install them?

### ISSUE THREAD

**Issue by Raffer807** [AlessandroZ/LaZagne#507]
Hi, sorry to bother you AlessandroZ but I have no experience in Python and all my attempts to install these components have failed, I did ask for help from specialized people but it didn't work either...

So if you don't mind, I'd like to know clearly how I do it, because I really need the LaZagne project to retrieve a password, thanks in advance ;-)

**Comment by Papotito123** [comment]
Hello:
First.Uninstall any python and dependencies related.Delete any python Environment Variable being set .
Restart computer 
Install python 3(dont need to install latest version,v 3.7 is suffice) but same architecture as you're OS.
Important when installing python, don't use default path,instead set install directory to C:\ root.
After installation,for your benefit, set Python installation folder , Scripts folder and Libs folder in Environment Variables.
Should install Visual Studio (I installed version 2017) .This will take big time and some Gigs.After VS  installed, don't update or install any Runtime C++ other than the ones during VS installation(be connected to internet).
Restart computer.
You should see a folder some like Python37 ( the number should be according the version you installed).

To check if installation was successful,open cmd(Run as as Admin( and type : python –V 
 The output should display your installed version of Python.
So, then do :  cd "  "  , and paste python installation path between quotes.
Then do:  python install -upgrade pip. , to update pip.

If you want to compile laZagne.py to lazagne.exe you need some things.
Then do :  
pip install pyinstaller
pip install pywin32
pip install ctypes
Download and extract latest lazagne git(don't use any from Downloads link).
So now do :  python "  "  and paste the full path of lazagne' s  requirements.txt  
Is very important to install this and don't manually update/upgrade any of the components listed in this.txt.Let be do always thru requirements.txt

**Comment by AlessandroZ** [comment]
Thanks @Papotito123, for your help. 

If you do not manage to follow @Papotito123 steps, follow a tutorial with screenshots such as this one: https://matthewhorne.me/how-to-install-python-and-pip-on-windows-10/

Easiest way to install requirements is using the requirements.txt file:
```
$ pip install -r requirements.txt
```
Check wiki if needed: https://github.com/AlessandroZ/LaZagne/wiki/How-to-compile

Good luck :)

**Comment by Raffer807** [comment]
@Papotito123 @AlessandroZ  Sorry for the late reply, thanks a lot for the help guys! :-)

**Comment by Raffer807** [comment]
@Papotito123 So I followed the beginning of your instructions but unfortunately, I have two problems: First, when Python installed itself on my C drive, all the subfolders have been copied directly to the main directory rather than to a Python37 file :
![image](https://user-images.githubusercontent.com/66703713/84434281-06295080-ac30-11ea-90fe-efac68e8c5b2.png)
However, as it didn't seem to cause too much trouble I decided to continue as you wrote...except that:
![image](https://user-images.githubusercontent.com/66703713/84434404-41c41a80-ac30-11ea-8fe2-f91708182800.png)
That's what happens when I enter pip in the cmd, as I said in my first post, I don't know anything about Python so I don't really know what to do...

So should I go to the solution that AlessandroZ wrote in his post or do you have a way to fix it? Thanks in advance^^ (And thanks again for helping me in general, I'm sorry to bother you for that, but I don't have much choice in view of my knowledge...)

**Comment by Raffer807** [comment]
Well, I deleted my other comment because I finally managed to solve the problems I mentioned, but I still can't move on to LaZagne:
![image](https://user-images.githubusercontent.com/66703713/84554346-b8881300-ad17-11ea-9170-9b43a0cf7335.png)
I'm currently searching for a fix...

**Comment by Vedant-Bhalgama** [comment]
Hello! I compiled the file successfully using your instructions! But now If i execute the EXE with this command in CMD 
laZagne.exe -h nothing happens it waits for 2-3 seconds and then nothing happens, No errors display or nothing happen!

**Comment by Vedant-Bhalgama** [comment]
I tried to run that file on Kali Linux using wine and it ran, no errors were there everything was working good and i was getting output of the results. Why is it not showing on windows?
