### ISSUE TITLE
Brave based on chromium

### ISSUE THREAD

**Issue by netsys-it** [AlessandroZ/LaZagne#509]
Hello, it is possible to add support for Brave browser based on chromium?
https://brave.com/

Brave is based on the same open-source Chromium code as a number of other browsers.
Thank you.

**Comment by plonibarploni** [comment]
Brave is listed as supported on Windows. Which platform are you using?

**Comment by netsys-it** [comment]
Windows 10

**Comment by plonibarploni** [comment]
What command are you trying? What happens when you try to run it?

**Comment by netsys-it** [comment]
Your second comment was the answer, thank you.
