### ISSUE TITLE
Tag trails behind the actual code

### ISSUE THREAD

**Issue by luigino** [AlessandroZ/LaZagne#51]
As you can see here https://github.com/AlessandroZ/LaZagne/compare/1.0...master .

The git tag precedes the 1.0 changes that are only in master.

**Comment by AlessandroZ** [comment]
Hi, 
I don't understand your request ? Could you be more explicit please.

**Comment by luigino** [comment]
I mean that if one downloads the 1.0 package (https://github.com/AlessandroZ/LaZagne/archive/1.0.zip), instead of the 1.0 release they get 0.9.1 or something inbetween.

In my understanding this means that the changes were committed after tagging the 1.0 release.

**Comment by AlessandroZ** [comment]
I don't understand why this archive is still available. Because, I removed binaries from source code so now it is only available from the release repository: https://github.com/AlessandroZ/LaZagne/releases

So I don't know why but your archive, is not up to date.

**Comment by luigino** [comment]
As you can see https://github.com/AlessandroZ/LaZagne/blob/1.0/CHANGELOG the problem is also in the source tree itself.

The archive is generated on the fly and short of undoing git changes, it will always be available.

P.S: 1.1 seems ok though.
