### ISSUE TITLE
Python3 output to file

### ISSUE THREAD

**Issue by plonibarploni** [AlessandroZ/LaZagne#512]
I don't usually output to a file so I didn't notice this before or even test for it, but when outputting to a file (e.g. `sudo python3 laZagne.py all -oN`) all values are output as bytes instead of strings.

So, while the terminal displays:
```
URL: www.example.com
Login: email@example.com
Password: SuperSecretPassword
```
the file contains:
```
URL: b'www.example.com'
Login: b'email@example.com'
Password: b'SuperSecretPassword'
```

**Comment by plonibarploni** [comment]
https://github.com/AlessandroZ/LaZagne/blob/105a79467985e59ee993719c32262faf373e3de8/Linux/lazagne/config/write_output.py#L267

If we remove `.encode('utf-8')` it will output properly on Python3, however I cannot test Python2 because I'm using Ubuntu 20.04, which removed Python2's `pip`.

This should probably be a separate discussion, but should we drop Python2 support, being as the Python Software Foundation has [officially sunset Python2](https://www.python.org/doc/sunset-python-2/)?

**Comment by AlessandroZ** [comment]
Hi @plonibarploni, 

I want to keep the support for python 2.7 on main functionalities to be still be able to be compatible with [Pupy](https://github.com/n1nj4sec/pupy). This project will upgrade to python 3 one day, so the support to 2.7 will be removed at that time. 

However, writing the output to a file is not used by pupy and not affect the main the core project. So if you want to remove it, do not hesitate, I will accept your PR. 

Thanks again for all your help.
