### ISSUE TITLE
License (in)compatibility

### ISSUE THREAD

**Issue by plonibarploni** [AlessandroZ/LaZagne#518]
Currently, this project is licensed under the LGPL-3.0 License. However, there are some files included which are specifically licensed under incompatible licenses.

I haven't done a complete review, but I became aware of this while reviewing the KeePass module for Windows. The `libkeepass` project is licensed under the [GPL-2+ license](https://github.com/libkeepass/libkeepass/blob/master/LICENSE.txt).

**Comment by AlessandroZ** [comment]
I'm really bad in project license. Do you think I should change mine to GPL-2.0 as well ?

**Comment by plonibarploni** [comment]
I don't know much about licenses to know whether that would be OK.

**Comment by plonibarploni** [comment]
Memorpy is also licensed under the [GPL-3+ license](https://github.com/n1nj4sec/memorpy/blob/master/LICENSE).

**Comment by plonibarploni** [comment]
According to [FSF](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility), these licenses are compatible with LGPLv3 code.
