### ISSUE TITLE
Not able to compile, PLEASE HELP!

### ISSUE THREAD

**Issue by ayashgupta** [AlessandroZ/LaZagne#523]
Hello everyone, 
Can anyone please let me know that how can I compile? 
I compiled it myself from the tutorial, however, the output generated is not compatible with the windows version. It is asking for 64 bit. I don't know how to import 64bit or 34bit files. 
Also, it is mentioned to copy 2 files in the windows, where in the project file? Is it the place where lazagne.py and spec are available?
Please help me!

**Comment by Papotito123** [comment]
Hello:
Read this.
https://github.com/AlessandroZ/LaZagne/issues/507#issuecomment-641658983

**Comment by ayashgupta** [comment]
Thanks Papotito, and what about the compatibility with both 32 and 62bit? 
Where should I copy the 2 files?

**Comment by Papotito123** [comment]
Hello:
If you have Windows 32 bit,you have to install Pyrhon 32 bit.If you have Windows 64 bit,you have to install Pyrhon 64 bit.

About some guy writes about copy 2 files inside lazagne \ Windows folder,AFAIK now there's no need to copy.

Remember to turn OFF any antivirus while running lazagne(..py and .exe) and when compiling to .exe  with pyinstaller .

I doesn't have Windows 32 bit ,so I can't confirm if lazagne compiled in 64 env will run in Windows 32 bit.But I think it should.

So I asking to @AlessandroZ:
 lazagne compiled in 64 env will run in Windows 32 bit ?

Expect the answer.

**Comment by AlessandroZ** [comment]
A binary compiled in a 32 bit environment will work on a 32 and 64 bits arch OS. However, a binary compiled on a x64 bit env won't work on a 32 bit OS. 

However, some modules needs to be arch compatible to work well. Pypykatz won't work well from a 32 bits binary on a 64 bits OS. So I recommend using same arch on both (binary and OS). 

Refer to old issues to found a solution, lots of issues concerning compilation have already been opened. Have a nice day.
