### ISSUE TITLE
Hello bro

### ISSUE THREAD

**Issue by rewizdox** [AlessandroZ/LaZagne#524]
Hi, were you able to decrypt your Yandex browser passwords?

**Comment by Papotito123** [comment]
Hello:
I'm not  developer.Just enthusiastic user.
I installed Yandex and share some info just for the benefit of someone who takes the lead in decrypting.

**Comment by rewizdox** [comment]
Do you have any information about the transcript?

**Comment by Papotito123** [comment]
Hello:
Yandex Decrypt #483

**Comment by Giawa86** [comment]
Stack over flow . And i fix any problems

Pada tanggal Sab, 15 Agt 2020 05.47, Papotito123 <notifications@github.com>
menulis:

**Comment by AlessandroZ** [comment]
Hi, 

I close this issue because another one for Yandex is still open. 
Have a nice day.
