### ISSUE TITLE
WIFI Password Not Found

### ISSUE THREAD

**Issue by WrongProgram1** [AlessandroZ/LaZagne#527]
INFO: [!] Password not found.

^ I just got that... Well I know using "netsh > wlan show profile" is easy... But could you please tell me why it shows Password not found... Thank You

**Comment by WrongProgram1** [comment]
I tried using the old versions and it's working just fine.

**Comment by Papotito123** [comment]
Hello:
I tested latest lazagne (compiled) in Win 10 2004H1 and retrieved WIFI well.

**Comment by AlessandroZ** [comment]
Wifi password is retrieved using 2 different ways depending if it's running as an administrator or a simple user. 
Should work better if it's running as an administrator (try to see if it works). 

If not, it will run netsh and try to parse the output depending on the language. Which language do you have on your system ? 
So maybe it fails when parsing. Try to run: 
```
netsh.exe wlan show profil <WIFI SSID> key=clear
```
And see if you have one of these words: 
* https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/wifi/wifi.py#L40
