### ISSUE TITLE
Custom directory as parameter

### ISSUE THREAD

**Issue by lucamanga** [AlessandroZ/LaZagne#536]
Hello, is it possible to pass a folder to scan for password? i.e. for a custom firefox profile

**Comment by Papotito123** [comment]
Hello:
Can be cool.

Chrome based browsers so Firefox will need a decrypted masterkey encrypted with the user password.
So the user password and the "masterkey" file are needed.

It can be cool.

**Comment by lucamanga** [comment]
I noticed that the original component that decrypts the firefox password has a "-d" switch to pass the directory you want.

**Comment by Papotito123** [comment]
Hello:
Could be for Firefox when having a Masterkey.

The developer did lazagneforensic where you can control some things .
The project is really outdated.But promising.

I compiled it but the retieved info is of not much use (at least for me).

**Comment by AlessandroZ** [comment]
I did this options once but then with so much tools, it was difficult to maintain, so I decided to removed it. I let this issue open if one day, I (or someone) do it: https://github.com/AlessandroZ/LaZagne/issues/403

Right now, I don't plan to add it. Sorry about it.
