### ISSUE TITLE
Google Chrome: not ok for masterkay

### ISSUE THREAD

**Issue by InfoSecMalang** [AlessandroZ/LaZagne#537]
Not dumping password for Google Chrome! i have tried on win7 and win10 (64bit).
Using the release executable.

``` bash
[-] user not ok for masterkey 8ba36b12-6c61-456f-9790-cff561abc4af
[-] user not ok for masterkey d2767cc2-5a62-432f-97d7-9d18abcfcbbc
[-] user not ok for masterkey acde9c67-0834-44b9-9002-6b7abc6e2e13
[!] No passwords found
```

**Comment by Papotito123** [comment]
Hello:
I had compiled latest lazagne code and tested in Win 1809 x64 and Win 2004H1 x64 and retrieve chrome logins well.

Maybe what you are looking is for the other user accounts for which logged user mkey can't be used to decrypt.

**Comment by InfoSecMalang** [comment]
Hey there! Thanks for the replay.

Nope, i am using the same account that i used to saved logins in chrome. 
Also, I was able to retrieve the passwords in 5 secs with both Mimikatz and nirsoft's WebBrowserPassView v2.07.

**Comment by Papotito123** [comment]
Hello:
I used also this tools.
Curious about not decrypting the mk pertaining to chrome logins.

If you are using the latest binary release(sept2019)  this doesn't works for chrome 80 and new.
The lazagne code were modified in March-April in this year.
You have to compile latest code to .exe
Look in Closed posts and there some explanations about how to do it.

**Comment by InfoSecMalang** [comment]
Hi, 

Got it! yes, i am using the old release (sep2019). i will compile it from code and give it a try.

Thanks for help!
