### ISSUE TITLE
Support stored BitLocker passwords

### ISSUE THREAD

**Issue by Danghor** [AlessandroZ/LaZagne#54]
When encrypting an external flash or hard drive using BitLocker (Microsoft), the user can enable automatic decryption. In this case, the drive is automatically unlocked when the user connects it to his machine. On all other machines, the drive can only be unlocked by typing in the selected password (and provide the SmartCard used, if any). When automatic decryption is activated, is it possible to extract the password stored on the computer somehow?

**Comment by AlessandroZ** [comment]
I think it could be possible, the password has to be stored somewhere. Right now, I do not have time to improve it, but it could be an idea.

**Comment by AlessandroZ** [comment]
I close this issue because I have to create a good environment to test this feature and it's not my priority right now. If you want to do a pull request to add this feature, feel free to do it.
