### ISSUE TITLE
LaZagne-2.4.3 exe - unable to fetch any browser passwords on Windows

### ISSUE THREAD

**Issue by dhull007** [AlessandroZ/LaZagne#546]
>lazagne.exe browsers
[+] System masterkey decrypted for 421474d0-5624-4f11-ba87-<xxxxxxxxxxxxx>
<.........etc etc - more lines like that>
[+] 0 passwords have been found.
For more information launch it again with the -v option
elapsed time = 817.49000001

>lazagne.exe browsers -v
[+] System masterkey decrypted for 421474d0-5624-4f11-ba87-<xxxxxxxxxxxxx>
<.........etc etc - more lines like that>
 ------------------- Firefox passwords -----------------
[!] No passwords found
 ------------------- Google chrome passwords -----------------
[-] <UseriD> not ok for masterkey 21e1570b-b88f-4578-8d7e-<xxxxxxxxxxxxx>
<.........etc etc - more lines like that>
[!] No passwords found
elapsed time = 752.773000002

Added <> - for providing more clarity or obscuring text

Machine Specs:
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.18363 N/A Build 18363
System Manufacturer:       HP
System Model:              HP Pavilion Laptop 15-cc6xx
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 10 GenuineIntel ~1792 Mhz
BIOS Version:              Insyde F.32, 5/10/2019

**Comment by Papotito123** [comment]
Hello:
If you are using the lazagne 2.4 3 standalone then this is not updated for the new chrome and Firefox codes.
You have to use Python(at least v.3.5) to run and compile the lazagne code.
With pyinstaller you can compile to lazagne exe.
This works well.

**Comment by dhull007** [comment]
Thanks @Papotito123 

FYI ( installed as below) in case its helpful for others:

Install Python to C:\Python38
C:\WINDOWS\system32>python -V
Python 3.8.7
C:\WINDOWS\system32>cd C:\Python38
C:\Python38>pip install pyinstaller
C:\Python38>python.exe -m pip install --upgrade pip
C:\Python38>pip install pywin32
C:\Python38>pip install pyasn1 psutil
Download the code files, unzip and place them in C:\Python38\LaZagne-master
C:\Python38>cd C:\Python38\LaZagne-master
C:\Python38\LaZagne-master>pip install -r requirements.txt
C:\Python38\LaZagne-master>cd Windows
C:\Python38\LaZagne-master\Windows>pyinstaller --onefile -w lazagne.spec
C:\Python38\LaZagne-master\Windows>cd dist
C:\Python38\LaZagne-master\Windows\dist>laZagne.exe -version
Version 2.4.4

**Comment by dhull007** [comment]
Worked like a charm!! Thanks Team!!

**Comment by Papotito123** [comment]
Hello:
Cool.
