### ISSUE TITLE
Generic question

### ISSUE THREAD

**Issue by dhull007** [AlessandroZ/LaZagne#547]
Hi team
Have below questions, appreciate your insights:
1. How to put some tracing/breakpoints to see the flow
2. Is there a place to know the internals of the code better e.g which place to look for chrome passwords and how do you figure it out - via tracing dll calls or any references for the same
I know these are like broad topics but looking for some workflow or let's say a new tool gets introduced how do you proceed with baby steps or design the high level algorithm n where do you go n fetch technical details to extract stuff

**Comment by AlessandroZ** [comment]
Hi @dhull007, 

Each sofware modules are managed on a separate file, so you could see the code of your interested sofware directly looking for it: https://github.com/AlessandroZ/LaZagne/tree/master/Windows/lazagne/softwares

If you want to follow the flow check this file here: https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/config/run.py#L39

**Comment by dhull007** [comment]
Thank you, appreciate the response!!
