### ISSUE TITLE
Adding Claws-Mail support?

### ISSUE THREAD

**Issue by liar666** [AlessandroZ/LaZagne#56]
Hi,

I just discovered:
https://github.com/b4n/clawsmail-password-decrypter

Would be great to fork this code in order to add support for decrypting ClawsMail passaords in LaZagne... (even if it did not work on my FreeBSD box, I assume it works on Linux...)

**Comment by AlessandroZ** [comment]
Clawmails support have been added. I didn't create the standalone yet, I will compile it soon (I want to do it using old libc version to a better compatibility so I need to create VM, it could take a while). 
However, this support is visible on the source code. 

Thank you !
