### ISSUE TITLE
Travis configuration file - Help needed

### ISSUE THREAD

**Issue by AlessandroZ** [AlessandroZ/LaZagne#566]
Hello everyone

@cclauss, I know you are good with the Travis configuration [file](https://github.com/AlessandroZ/LaZagne/blob/master/.travis.yml).  
Mine is broken since a while ([example](https://travis-ci.com/github/AlessandroZ/LaZagne/jobs/510710697)), if you or someone could take a look, it will help me, I don't have lots of time right now. 

I cannot upload any new releases using travis anymore and I don't find the way to correct it fast. 

Thank you.

**Comment by cclauss** [comment]
Would you be willing to upgrade from Travis to GitHub Actions or do you want to stick with Travis.

I will try to spend some time this weekend knocking thinks back into shape.

**Comment by AlessandroZ** [comment]
Never used github actions but it could be interesting. 
What I liked with travis was to be able to compile a windows binary with pyinstaller to push a new release. If it's simpler with github actions I don't mind to upgrade to it.
