### ISSUE TITLE
Error with the module "[-] Module IE is not used due to unresolved dependence: No module named 'lazagne.softwares.browsers.ie'"

### ISSUE THREAD

**Issue by ghost** [AlessandroZ/LaZagne#568]
Hello i have compile with python today the script, but when i lunch the .exe have an error with the module, i dont know why, someone know why ?

C:\Users\Me\AppData\Local\Programs\Python\Python39\Scripts\dist>lazagne.exe all -v

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

[+] System masterkey decrypted for 1fed3bc1-f337-4a0b-b2ed-2afcedd6f163
[+] System masterkey decrypted for 2412fd88-8b72-41ca-b6a1-49e99912008f

########## User: SYSTEM ##########

 ------------------- Lsa_secrets passwords -----------------

DefaultPassword
0000   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
0010   EE 10 75 0B 07 B8 AB 79 90 48 9E 94 48 7D 7A CE    ..u....y.H..H}z.

DPAPI_SYSTEM
0000   01 00 00 00 AF 96 AE 7E 73 E7 02 4F D5 1D D6 A5    .......~s..O....
0010   D5 F8 9F 8D 79 BD CC FC 4C E7 0C 48 9C 4F 0A FC    ....y...L..H.O..
0020   DF 05 BC 69 3C EF 1E 55 59 DC 71 A8                ...i<..UY.q.

NL$KM
0000   40 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    @...............
0010   40 88 25 EE E1 4E 5B 36 60 0D A9 59 2C C7 61 DB    @.%..N[6`..Y,.a.
0020   C5 00 4C 14 F7 EC 52 FA A7 13 A4 A0 4C 6D D3 0F    ..L...R.....Lm..
0030   8D 57 BC 4F 1D E8 EB A9 10 29 28 6E 4C B3 BE ED    .W.O.....)(nL...
0040   E2 8B 74 A4 EE D6 A8 9B 43 61 EB 3D 33 8F BA 4E    ..t.....Ca.=3..N
0050   E3 C3 37 2A C9 FA 66 B9 FE 86 64 0A 6F E0 62 17    ..7*..f...d.o.b.

########## User: Bren ##########

 ------------------- Ie passwords -----------------

[-] Module IE is not used due to unresolved dependence:
No module named 'lazagne.softwares.browsers.ie'
[!] No passwords found

 ------------------- Ucbrowser passwords -----------------

[-] Module UCBrowser is not used due to unresolved dependence:
No module named 'lazagne.softwares.browsers.ucbrowser'
[!] No passwords found

 ------------------- Pidgin passwords -----------------

[-] Module Pidgin is not used due to unresolved dependence:
No module named 'lazagne.softwares.chats'
[!] No passwords found

 ------------------- Psi passwords -----------------

[-] Module PSI is not used due to unresolved dependence:
No module named 'lazagne.softwares.chats'
[!] No passwords found

 ------------------- Skype passwords -----------------

[-] Module Skype is not used due to unresolved dependence:
No module named 'lazagne.softwares.chats'
[!] No passwords found

 ------------------- Dbvisualizer passwords -----------------

[-] Module Dbvisualizer is not used due to unresolved dependence:
No module named 'lazagne.softwares.databases'
[!] No passwords found

 ------------------- Postgresql passwords -----------------

[-] Module PostgreSQL is not used due to unresolved dependence:
No module named 'lazagne.softwares.databases'
[!] No passwords found

 ------------------- Robomongo passwords -----------------

[-] Module Robomongo is not used due to unresolved dependence:
No module named 'lazagne.softwares.databases'
[!] No passwords found

 ------------------- Sqldeveloper passwords -----------------

[-] Module SQLDeveloper is not used due to unresolved dependence:
No module named 'lazagne.softwares.databases'
[!] No passwords found

 ------------------- Squirrel passwords -----------------

[-] Module Squirrel is not used due to unresolved dependence:
No module named 'lazagne.softwares.databases'
[!] No passwords found

 ------------------- Galconfusion passwords -----------------

[-] Module GalconFusion is not used due to unresolved dependence:
No module named 'lazagne.softwares.games'
[!] No passwords found

 ------------------- Kalypsomedia passwords -----------------

[-] Module KalypsoMedia is not used due to unresolved dependence:
No module named 'lazagne.softwares.games'
[!] No passwords found

 ------------------- Roguestale passwords -----------------

[-] Module RoguesTale is not used due to unresolved dependence:
No module named 'lazagne.softwares.games'
[!] No passwords found

 ------------------- Turba passwords -----------------

[-] Module Turba is not used due to unresolved dependence:
No module named 'lazagne.softwares.games'
[!] No passwords found

 ------------------- Gitforwindows passwords -----------------

[-] Module GitForWindows is not used due to unresolved dependence:
No module named 'lazagne.softwares.git'
[!] No passwords found

 ------------------- Outlook passwords -----------------

[-] Module Outlook is not used due to unresolved dependence:
No module named 'lazagne.softwares.mails'
[!] No passwords found

 ------------------- Thunderbird passwords -----------------

[-] Module Thunderbird is not used due to unresolved dependence:
No module named 'lazagne.softwares.mails'
[!] No passwords found

 ------------------- Mavenrepositories passwords -----------------

[-] Module MavenRepositories is not used due to unresolved dependence:
No module named 'lazagne.softwares.maven'
[!] No passwords found

 ------------------- Keepass passwords -----------------

[-] Module Keepass is not used due to unresolved dependence:
No module named 'lazagne.softwares.memory'
[!] No passwords found

 ------------------- Memorydump passwords -----------------

[-] Module MemoryDump is not used due to unresolved dependence:
No module named 'lazagne.softwares.memory'
[!] No passwords found

 ------------------- Onepassword passwords -----------------

[-] Module OnePassword is not used due to unresolved dependence:
No module named 'lazagne.softwares.memory'
[!] No passwords found

 ------------------- Eyecon passwords -----------------

[-] Module EyeCON is not used due to unresolved dependence:
No module named 'lazagne.softwares.multimedia'
[!] No passwords found

 ------------------- Composer passwords -----------------

[-] Module Composer is not used due to unresolved dependence:
No module named 'lazagne.softwares.php'
[!] No passwords found

 ------------------- Tortoise passwords -----------------

[-] Module Tortoise is not used due to unresolved dependence:
No module named 'lazagne.softwares.svn'
[!] No passwords found

 ------------------- Apachedirectorystudio passwords -----------------

[-] Module ApacheDirectoryStudio is not used due to unresolved dependence:
No module named 'lazagne.softwares.sysadmin'
[!] No passwords found

 ------------------- Coreftp passwords -----------------

[-] Module CoreFTP is not used due to unresolved dependence:
No module named 'lazagne.softwares.sysadmin'
[!] No passwords found

 ------------------- Cyberduck passwords -----------------

[-] Module Cyberduck is not used due to unresolved dependence:
No module named 'lazagne.softwares.sysadmin'
[!] No passwords found

 ------------------- Filezilla passwords -----------------

[-] Module Filezilla is not used due to unresolved dependence:
No module named 'lazagne.softwares.sysadmin'
[!] No passwords found

 ------------------- Filezillaserver passwords -----------------

[-] Module FilezillaServer is not used due to unresolved dependence:
No module named 'lazagne.softwares.sysadmin'
[!] No passwords found

 ------------------- Ftpnavigator passwords -----------------

[-] Module FtpNavigator is not used due to unresolved dependence:
No module named 'lazagne.softwares.sysadmin'
[!] No passwords found

 ------------------- Opensshforwindows passwords -----------------

[-] Module OpenSSHForWindows is not used due to unresolved dependence:
No module named 'lazagne.softwares.sysadmin'
[!] No passwords found

 ------------------- Openvpn passwords -----------------

[-] Module OpenVPN is not used due to unresolved dependence:
No module named 'lazagne.softwares.sysadmin'
[!] No passwords found

 ------------------- Iiscentralcertp passwords -----------------

[-] Module IISCentralCertP is not used due to unresolved dependence:
No module named 'lazagne.softwares.sysadmin'
[!] No passwords found

 ------------------- Keepassconfig passwords -----------------

[-] Module KeePassConfig is not used due to unresolved dependence:
No module named 'lazagne.softwares.sysadmin'
[!] No passwords found

 ------------------- Iisapppool passwords -----------------

[-] Module IISAppPool is not used due to unresolved dependence:
No module named 'lazagne.softwares.sysadmin'
[!] No passwords found

 ------------------- Puttycm passwords -----------------

[-] Module Puttycm is not used due to unresolved dependence:
No module named 'lazagne.softwares.sysadmin'
[!] No passwords found

 ------------------- Rdpmanager passwords -----------------

[-] Module RDPManager is not used due to unresolved dependence:
No module named 'lazagne.softwares.sysadmin'
[!] No passwords found

 ------------------- Unattended passwords -----------------

[-] Module Unattended is not used due to unresolved dependence:
No module named 'lazagne.softwares.sysadmin'
[!] No passwords found

 ------------------- Vnc passwords -----------------

[-] Module Vnc is not used due to unresolved dependence:
No module named 'lazagne.softwares.sysadmin'
[!] No passwords found

 ------------------- Winscp passwords -----------------

[-] Module WinSCP is not used due to unresolved dependence:
No module named 'lazagne.softwares.sysadmin'
[!] No passwords found

 ------------------- Wsl passwords -----------------

[-] Module Wsl is not used due to unresolved dependence:
No module named 'lazagne.softwares.sysadmin'
[!] No passwords found

 ------------------- Wifi passwords -----------------

[-] Module Wifi is not used due to unresolved dependence:
No module named 'lazagne.softwares.wifi'
[!] No passwords found

 ------------------- Autologon passwords -----------------

[-] Module Autologon is not used due to unresolved dependence:
No module named 'lazagne.softwares.windows.autologon'
[!] No passwords found

 ------------------- Cachedump passwords -----------------

[-] Module Cachedump is not used due to unresolved dependence:
No module named 'lazagne.softwares.windows.cachedump'
[!] No passwords found

 ------------------- Credman passwords -----------------

[-] Module Credman is not used due to unresolved dependence:
No module named 'lazagne.softwares.windows.credman'
[!] No passwords found

 ------------------- Credfiles passwords -----------------

[-] Module CredFiles is not used due to unresolved dependence:
No module named 'lazagne.softwares.windows.credfiles'
[!] No passwords found

 ------------------- Hashdump passwords -----------------

[-] Module Hashdump is not used due to unresolved dependence:
No module named 'lazagne.softwares.windows.hashdump'
[!] No passwords found

 ------------------- Pypykatz passwords -----------------

[-] Module Pypykatz is not used due to unresolved dependence:
No module named 'lazagne.softwares.windows.ppypykatz'
[!] No passwords found

 ------------------- Vault passwords -----------------

[-] Module Vault is not used due to unresolved dependence:
No module named 'lazagne.softwares.windows.vault'
[!] No passwords found

 ------------------- Vaultfiles passwords -----------------

[-] Module VaultFiles is not used due to unresolved dependence:
No module named 'lazagne.softwares.windows.vaultfiles'
[!] No passwords found

 ------------------- Windowspassword passwords -----------------

[-] Module WindowsPassword is not used due to unresolved dependence:
No module named 'lazagne.softwares.windows.windows'
[!] No passwords found

 ------------------- Chromiumbased passwords -----------------

[-] Module ChromiumBased is not used due to unresolved dependence:
No module named 'lazagne.softwares.browsers.chromium_based'
[!] No passwords found

 ------------------- Mozilla passwords -----------------

[-] Module Mozilla is not used due to unresolved dependence:
No module named 'lazagne.softwares.browsers.mozilla'
[!] No passwords found

[+] 0 passwords have been found.

elapsed time = 0.6801979541778564

**Comment by MyLoginOnGitHub** [comment]
Hello. Now LaZagne should be compiled using **lazagne.spec** file.  
`pyinstaller --onefile lazagne.spec`

Please, reply if this solved issue

**Comment by Dirt4193** [comment]
Yes it's work thank you !
