### ISSUE TITLE
couldn't work in xp

### ISSUE THREAD

**Issue by owengod** [AlessandroZ/LaZagne#57]
i download lazagne1.1 windows,when i execute in xp,the following result shows below.
![Uploading 1.png…]()

so i build by py2exe tool,but error occur again.In win7 it works fine.
![Uploading 2.png…]()

**Comment by owengod** [comment]
![Uploading 1.png…]()
![Uploading 2.png…]()

**Comment by owengod** [comment]
![1](https://cloud.githubusercontent.com/assets/17715112/13590254/3df269f8-e519-11e5-8627-5b36c61b5f36.png)
![2](https://cloud.githubusercontent.com/assets/17715112/13590255/3df711f6-e519-11e5-88e1-e691b0008751.png)

**Comment by owengod** [comment]
![2](https://cloud.githubusercontent.com/assets/17715112/13590277/657db338-e519-11e5-8690-0713b499fef1.png)

**Comment by owengod** [comment]
i install vs2008 in xp,and configer all env.build by pyinstaller.And then success!

**Comment by AlessandroZ** [comment]
Hi, 

Sorry for my late answer. I'm glad you could use lazagne on your XP. I had some problems doing the executable file to be portable on all arch (32 / 64 bits) and OS (XP, win7, etc). 
I have created a clean XP virtual machine and it worked right away whereas I have tried on other XP machines without success. So it's hard to debug a program without having the same error. 

If you manage to build it installing vs2008 in XP, could you give the exact step to compile it with pyinstaller (commands and file modification). And if you have the opportunity, could you try the executable file on another XP machine which has not vs2008 installed to see if the binary is really portable. I could help me for later release. 

Thanks a lot. Have a good day.
