### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decrypt_with_key'

### ISSUE THREAD

**Issue by triple7inc** [AlessandroZ/LaZagne#571]
PS C:\Users\thefu\Desktop\LaZagne> py laZagne.py browsers -v

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

[+] System masterkey decrypted for 0aa278c8-27b5-471a-839e-731d087b2adb
[+] System masterkey decrypted for c17c1e08-168e-41ed-ae49-0cfad0be43c2
Traceback (most recent call last):
  File "C:\Users\thefu\Desktop\LaZagne\laZagne.py", line 233, in <module>
    for r in runLaZagne(category_selected=category, subcategories=subcategories, password=args.get('password', None)):
  File "C:\Users\thefu\Desktop\LaZagne\laZagne.py", line 87, in runLaZagne
    for pwd_dic in run_lazagne(category_selected=category_selected, subcategories=subcategories, password=password):
  File "C:\Users\thefu\Desktop\LaZagne\lazagne\config\run.py", line 169, in run_lazagne
    constant.system_dpapi = SystemDpapi()
  File "C:\Users\thefu\Desktop\LaZagne\lazagne\config\dpapi_structure.py", line 172, in __init__
    for ok, r in self.smkp.try_system_credential():
  File "C:\Users\thefu\Desktop\LaZagne\lazagne\config\DPAPI\masterkey.py", line 449, in try_system_credential
    mk.decrypt_with_key(self.system.user)
AttributeError: 'NoneType' object has no attribute 'decrypt_with_key'

**Comment by TheMMC** [comment]
I'm getting the same error using the latest code.
I tried different versions of python (3.91, 3.96, 3.97, 3.10) but nothing worked. Even the pre-built exe has the same error ( exe from here: https://github.com/AlessandroZ/LaZagne/actions/runs/1368437552).
BUT I was able to compile the exact same code some time ago without errors. The only thing I changed was upgrading to win11 and updating all vc++ and .NET installations to the latest versions.
Microsoft must have done something that breaks decrypt_with_key at some place...

**Comment by Nefast0** [comment]
> /edit After fiddling around with some VMs I found this: Lazagne doesnt work on Win11, Win10 with latest updates works fine.

On Win11 it is possible to enable the compatibility mode for Windows 7. I got that working with that!

**Comment by hitokiri8x** [comment]
> > /edit After fiddling around with some VMs I found this: Lazagne doesnt work on Win11, Win10 with latest updates works fine.
> 
> On Win11 it is possible to enable the compatibility mode for Windows 7. I got that working with that!

Are you saying that you right clicked the builded .exe and setted compatibility mode for win 7?   Because I can't get to work with it..
Anyway running directly code with pyton works, it's just the builded exe!

**Comment by AlessandroZ** [comment]
Should be fixed now: https://github.com/AlessandroZ/LaZagne/pull/603
