### ISSUE TITLE
pyinstaller .spec file not working

### ISSUE THREAD

**Issue by triple7inc** [AlessandroZ/LaZagne#572]
PS C:\Users\thefu\Desktop\LaZagne>  pyinstaller --onefile lazagne.spec
139 INFO: PyInstaller: 4.5.1
139 INFO: Python: 3.9.6
155 INFO: Platform: Windows-10-10.0.21996-SP0
155 INFO: UPX is not available.
186 INFO: Extending PYTHONPATH with paths
['C:\\Users\\thefu\\Desktop\\LaZagne', 'C:\\Users\\thefu\\Desktop\\LaZagne']
377 INFO: checking Analysis
377 INFO: Building Analysis because Analysis-00.toc is non existent
377 INFO: Initializing module dependency graph...
377 INFO: Caching module graph hooks...
405 INFO: Analyzing base_library.zip ...
2563 INFO: Processing pre-find module path hook distutils from 'c:\\users\\thefu\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
2563 INFO: distutils: retargeting to non-venv dir 'c:\\users\\thefu\\appdata\\local\\programs\\python\\python39\\lib'
6265 INFO: Caching module dependency graph...
6470 INFO: running Analysis Analysis-00.toc
6485 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\thefu\appdata\local\programs\python\python39\python.exe
6516 WARNING: lib not found: api-ms-win-core-path-l1-1-0.dll dependency of c:\users\thefu\appdata\local\programs\python\python39\python39.dll
6531 INFO: Analyzing laZagne.py
6828 INFO: Analyzing hidden import 'lazagne.softwares.browsers.ie'
6842 INFO: Analyzing hidden import 'lazagne.softwares.browsers.ucbrowser'
6859 INFO: Analyzing hidden import 'lazagne.softwares.chats.pidgin'
6859 INFO: Analyzing hidden import 'lazagne.softwares.chats.psi'
6875 INFO: Analyzing hidden import 'lazagne.softwares.chats.skype'
6875 INFO: Analyzing hidden import 'lazagne.softwares.databases.dbvis'
6890 INFO: Analyzing hidden import 'lazagne.softwares.databases.postgresql'
6890 INFO: Analyzing hidden import 'lazagne.softwares.databases.robomongo'
6890 INFO: Analyzing hidden import 'lazagne.softwares.databases.sqldeveloper'
6890 INFO: Analyzing hidden import 'lazagne.softwares.databases.squirrel'
6906 INFO: Analyzing hidden import 'lazagne.softwares.games.galconfusion'
6906 INFO: Analyzing hidden import 'lazagne.softwares.games.kalypsomedia'
6906 INFO: Analyzing hidden import 'lazagne.softwares.games.roguestale'
6906 INFO: Analyzing hidden import 'lazagne.softwares.games.turba'
6906 INFO: Analyzing hidden import 'lazagne.softwares.git.gitforwindows'
6921 INFO: Analyzing hidden import 'lazagne.softwares.mails.outlook'
6937 INFO: Analyzing hidden import 'lazagne.softwares.mails.thunderbird'
6953 INFO: Analyzing hidden import 'lazagne.softwares.maven.mavenrepositories'
6953 INFO: Analyzing hidden import 'lazagne.softwares.memory.keepass'
7000 INFO: Analyzing hidden import 'lazagne.softwares.memory.memorydump'
7078 INFO: Analyzing hidden import 'lazagne.softwares.memory.onepassword'
7078 INFO: Analyzing hidden import 'lazagne.softwares.multimedia.eyecon'
7078 INFO: Analyzing hidden import 'lazagne.softwares.php.composer'
7094 INFO: Analyzing hidden import 'lazagne.softwares.svn.tortoise'
7094 INFO: Analyzing hidden import 'lazagne.softwares.sysadmin.apachedirectorystudio'
7108 INFO: Analyzing hidden import 'lazagne.softwares.sysadmin.coreftp'
7108 INFO: Analyzing hidden import 'lazagne.softwares.sysadmin.cyberduck'
7108 INFO: Analyzing hidden import 'lazagne.softwares.sysadmin.filezilla'
7108 INFO: Analyzing hidden import 'lazagne.softwares.sysadmin.filezillaserver'
7123 INFO: Analyzing hidden import 'lazagne.softwares.sysadmin.ftpnavigator'
7123 INFO: Analyzing hidden import 'lazagne.softwares.sysadmin.opensshforwindows'
7123 INFO: Analyzing hidden import 'lazagne.softwares.sysadmin.openvpn'
7123 INFO: Analyzing hidden import 'lazagne.softwares.sysadmin.iiscentralcertp'
7297 INFO: Analyzing hidden import 'lazagne.softwares.sysadmin.keepassconfig'
7313 INFO: Analyzing hidden import 'lazagne.softwares.sysadmin.iisapppool'
7313 INFO: Analyzing hidden import 'lazagne.softwares.sysadmin.puttycm'
7313 INFO: Analyzing hidden import 'lazagne.softwares.sysadmin.rdpmanager'
7313 INFO: Analyzing hidden import 'lazagne.softwares.sysadmin.unattended'
7327 INFO: Analyzing hidden import 'lazagne.softwares.sysadmin.vnc'
7343 INFO: Analyzing hidden import 'lazagne.softwares.sysadmin.winscp'
7343 INFO: Analyzing hidden import 'lazagne.softwares.sysadmin.wsl'
7343 INFO: Analyzing hidden import 'lazagne.softwares.wifi.wifi'
7359 INFO: Analyzing hidden import 'lazagne.softwares.windows.autologon'
7359 INFO: Analyzing hidden import 'lazagne.softwares.windows.cachedump'
7359 INFO: Analyzing hidden import 'lazagne.softwares.windows.credfiles'
7359 INFO: Analyzing hidden import 'lazagne.softwares.windows.hashdump'
7359 INFO: Analyzing hidden import 'lazagne.softwares.windows.ppypykatz'
7359 INFO: Analyzing hidden import 'lazagne.softwares.windows.vault'
7374 INFO: Analyzing hidden import 'lazagne.softwares.windows.vaultfiles'
7374 INFO: Analyzing hidden import 'lazagne.softwares.windows.windows'
7374 INFO: Processing module hooks...
7374 INFO: Loading module hook 'hook-difflib.py' from 'c:\\users\\thefu\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
7374 INFO: Loading module hook 'hook-distutils.py' from 'c:\\users\\thefu\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
7374 INFO: Loading module hook 'hook-distutils.util.py' from 'c:\\users\\thefu\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
7374 INFO: Loading module hook 'hook-encodings.py' from 'c:\\users\\thefu\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
7468 INFO: Loading module hook 'hook-heapq.py' from 'c:\\users\\thefu\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
7483 INFO: Loading module hook 'hook-lib2to3.py' from 'c:\\users\\thefu\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
7517 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'c:\\users\\thefu\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
7517 INFO: Loading module hook 'hook-pickle.py' from 'c:\\users\\thefu\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
7517 INFO: Loading module hook 'hook-sqlite3.py' from 'c:\\users\\thefu\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
7594 INFO: Loading module hook 'hook-sysconfig.py' from 'c:\\users\\thefu\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
7594 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'c:\\users\\thefu\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
7608 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'c:\\users\\thefu\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
7608 INFO: Loading module hook 'hook-xml.py' from 'c:\\users\\thefu\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
7608 INFO: Loading module hook 'hook-_tkinter.py' from 'c:\\users\\thefu\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
7782 INFO: checking Tree
7782 INFO: Building Tree because Tree-00.toc is non existent
7782 INFO: Building Tree Tree-00.toc
7844 INFO: checking Tree
7844 INFO: Building Tree because Tree-01.toc is non existent
7844 INFO: Building Tree Tree-01.toc
7905 INFO: checking Tree
7905 INFO: Building Tree because Tree-02.toc is non existent
7920 INFO: Building Tree Tree-02.toc
7952 INFO: Looking for ctypes DLLs
7983 INFO: Analyzing run-time hooks ...
7983 INFO: Including run-time hook 'c:\\users\\thefu\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
7999 INFO: Including run-time hook 'c:\\users\\thefu\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
7999 INFO: Including run-time hook 'c:\\users\\thefu\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
7999 INFO: Looking for dynamic libraries
8202 INFO: Looking for eggs
8202 INFO: Using Python library c:\users\thefu\appdata\local\programs\python\python39\python39.dll
8202 INFO: Found binding redirects:
[]
8202 INFO: Warnings written to C:\Users\thefu\Desktop\LaZagne\build\lazagne\warn-lazagne.txt
8283 INFO: Graph cross-reference written to C:\Users\thefu\Desktop\LaZagne\build\lazagne\xref-lazagne.html
8297 INFO: checking PYZ
8314 INFO: Building PYZ because PYZ-00.toc is non existent
8314 INFO: Building PYZ (ZlibArchive) C:\Users\thefu\Desktop\LaZagne\build\lazagne\PYZ-00.pyz
9014 INFO: Building PYZ (ZlibArchive) C:\Users\thefu\Desktop\LaZagne\build\lazagne\PYZ-00.pyz completed successfully.
9048 INFO: checking PKG
9048 INFO: Building PKG because PKG-00.toc is non existent
9048 INFO: Building PKG (CArchive) PKG-00.pkg
Traceback (most recent call last):
  File "c:\users\thefu\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\thefu\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\thefu\AppData\Local\Programs\Python\Python39\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\users\thefu\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\__main__.py", line 126, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\thefu\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\thefu\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\build_main.py", line 815, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\thefu\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\build_main.py", line 762, in build
    exec(code, spec_namespace)
  File "lazagne.spec", line 24, in <module>
    exe = EXE(
  File "c:\users\thefu\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\api.py", line 509, in __init__
    self.pkg = PKG(self.toc, cdict=kwargs.get('cdict', None),
  File "c:\users\thefu\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\api.py", line 208, in __init__
    self.__postinit__()
  File "c:\users\thefu\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\datastruct.py", line 159, in __postinit__
    self.assemble()
  File "c:\users\thefu\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\api.py", line 274, in assemble
    fnm = checkCache(fnm, strip=self.strip_binaries,
  File "c:\users\thefu\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\utils.py", line 239, in checkCache
    digest = cacheDigest(fnm, redirects)
  File "c:\users\thefu\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\building\utils.py", line 397, in cacheDigest
    with open(fnm, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Windows\\System32\\msvcp100.dll'

**Comment by MyLoginOnGitHub** [comment]
Try to compile with PyInstaller something like HelloWorld. I think something wrong with installation of PyInstaller.

**Comment by ashlar7** [comment]
Do you have MS Visual C++ installed? 
https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by triple7inc** [comment]
I do have Microsoft Visual C++ installed 2013, 2015, 2017 and 2019.

**Comment by Papotito123** [comment]
Hello;
Check If you have installed this file that is from Visual C++.:

C:\Windows\System32\msvcp100.dll

If you have 64 bit then you should also have:

C:\Windows\SysWOW64
