### ISSUE TITLE
Fails to dump chrome passwords. 

### ISSUE THREAD

**Issue by RootInit** [AlessandroZ/LaZagne#573]
Running on windows 10 host. Database is found and copied to a temp folder but raises an error line 90, in chromium_based.py, _export_credentials, OperationalError: no such table: logins.
This is followed by a ValueError: Master keys not found.

**Comment by Texesh** [comment]
> Hello,
> 
> You should use the last python code from the repo and not the last release which is not up to date. It should work.

Hi, that did not work for me. Is there any other possible solution?
