### ISSUE TITLE
Password Issue

### ISSUE THREAD

**Issue by MDMEHEDIHASA** [AlessandroZ/LaZagne#580]
[](url)At first in Standalones I download  LaZagne - Windows version 2.3.1 version. Then I extarct the windows.zip file. Then I run the command in windows (laZagne.exe browsers ) but what I got only the username in the password is set the the password as password false. Everytime I run a command in windows it show me that the password is false. What is the problem exactly? Instead of false how can I see the exact password. Can anyone help me with this please. something like this
![5](https://user-images.githubusercontent.com/48857205/135743556-1725e3f5-8de4-4fd5-b3c7-2b697ee048fc.PNG)

**Comment by AlessandroZ** [comment]
Hello, 

The last release is not up to date, if you could take the last code source and compile it, I cannot say it will work but lots of bugs have been corrected. I will try to release a new one once I fixed my travis error. 

Have a nice day.

**Comment by SeregaBess** [comment]
> Привет,
> 
> Последний выпуск устарел, если бы вы могли взять последний исходный код и скомпилировать его, я не могу сказать, что он будет работать, но исправлено множество ошибок. Я постараюсь выпустить новый, как только исправлю ошибку Travis.
> 
> Хорошего дня.

То есть проект ещё будет жить?

**Comment by MDMEHEDIHASA** [comment]
I am already using the latest one. By using the latest one I get some correct password value on the Otherhand I also get some password value is false. Please fix it.
