### ISSUE TITLE
No Browsers Passwd

### ISSUE THREAD

**Issue by PhilSutter** [AlessandroZ/LaZagne#584]
Hi guys, 

first i want to thanks you for your incredible work :) 

I face an issue. After compiling the last files, and lauching `lazagne.exe all`, i get some passwords  on my machine (creds, wifi ...) but not the browsers. Do you know why ? or have a clue ? 

Thanks for your help ! 

EDIT :  I jsut forgot the diffenrent modules during the compilation :) I'm dumb ! Working perfectly ! Thanks !

**Comment by AlessandroZ** [comment]
Hi PhilSutter, thank you for your feedback. So in your "EDIT", I understand that it works, or did I miss something ?

**Comment by PhilSutter** [comment]
Hi AlessandroZ, 
Yes everything is working as a charm :) 

Thanks again for you work !

**Comment by AlessandroZ** [comment]
Cool ;)
