### ISSUE TITLE
Dependancy Issue: Module ChromiumBased is not used due to unresolved dependence: No module named 'Crypto'

### ISSUE THREAD

**Issue by Texesh** [AlessandroZ/LaZagne#587]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/76835709/147458395-e47c4ad4-089d-4068-bf07-04730fc607ad.png">

------------------- Iiscentralcertp passwords -----------------

[-] Module IISCentralCertP is not used due to unresolved dependence:
No module named 'rsa'
[!] No passwords found

 ------------------- Pypykatz passwords -----------------

[-] Module Pypykatz is not used due to unresolved dependence:
No module named 'pypykatz'
[!] No passwords found

 ------------------- Chromiumbased passwords -----------------

[-] Module ChromiumBased is not used due to unresolved dependence:
No module named 'Crypto'
[!] No passwords found

 ------------------- Mozilla passwords -----------------

[-] Module Mozilla is not used due to unresolved dependence:
No module named 'pyasn1'
[!] No passwords found

ETC (some still work)

**Comment by MyLoginOnGitHub** [comment]
You have no some python modules required to run full functional. So, laZagne run all modules that it could.  
You could install this module by `cd <path_to_laZagne>; pip3 install requirements.txt`

**Comment by mubb** [comment]
I am also facing the same issue, despite running the project from Python and updating the requirements. 
Dear Alessandro, this is a fantastic project, could I request you to review and kindly provide an official one file .exe release. 
Thank you.

**Comment by HGStyle** [comment]
> I am also facing the same issue, despite running the project from Python and updating the requirements. Dear Alessandro, this is a fantastic project, could I request you to review and kindly provide an official one file .exe release. Thank you.

https://github.com/AlessandroZ/LaZagne/releases/download/2.4.3/lazagne.exe
Compiled version of LaZagne for Windows

**Comment by AlessandroZ** [comment]
It's a requirement problem, requirements.txt should be installed or use the last release.
