### ISSUE TITLE
No longer working , Virus detected !

### ISSUE THREAD

**Issue by Abhijeetbyte** [AlessandroZ/LaZagne#592]
Firstly chrome can't allow to downloaded .exe or even zip file, same with edge browser.
after disabling the smart screen monitoring and block download  options in windows.
It says the virus detected ! 

Same with python script, it can't allow windows shell to run script ,even if all possible security features were disabled.

I think  you really have to pull it in different way, cause it no longer working.

![image](https://user-images.githubusercontent.com/80936610/153765471-f617367a-079c-42d9-96db-f80a9ebe108a.png)

**Comment by AlessandroZ** [comment]
Hi, for all AV bypass I cannot help you but you should manage to do something.

**Comment by Abhijeetbyte** [comment]
it's ok
