### ISSUE TITLE
Some Suggestions on Browser Credential Acquisition !!!

### ISSUE THREAD

**Issue by Inetgeek** [AlessandroZ/LaZagne#599]
This is an excellent project, but the downside is the lack of support for Chrome Edge, resulting in missing URLs and passwords in encrypted data. Just now I tested the project of a developer from China. His project can fully obtain all the credentials saved by Chrome Edge. I would like to suggest you to refer to:
https://www.jb51.net/article/247537.htm
thanks!

**Comment by AlessandroZ** [comment]
Hi, sorry for my late answer. However, it should works for Chrome, the path from your china project and mine is the same: https://github.com/AlessandroZ/LaZagne/blob/78d7c23a608e0db8ba844514327769f81e0cb6ba/Windows/lazagne/softwares/browsers/chromium_browsers.py#L22

If it does not work, something should have failed.
