### ISSUE TITLE
compiling questions

### ISSUE THREAD

**Issue by mana131278** [AlessandroZ/LaZagne#602]
hello, if i convert python to exe with this way: https://github.com/AlessandroZ/LaZagne/wiki/How-to-compile#for-windows-only

will it work on all windows versions or only same windows version with mine ? which windows versions it will work on ?

**Comment by HGStyle** [comment]
i think (but im not sure) it will work with every windows versions

**Comment by AlessandroZ** [comment]
Check the travis file or Windows action do see how to do cross compilation.
