### ISSUE TITLE
LaZagne 2.4 appears to work with Palemoon 31.2, but not Chrome 105

### ISSUE THREAD

**Issue by RanTalbott** [AlessandroZ/LaZagne#606]
I just recently upgraded my main PC to Ubuntu 20.04 (I value being heavily field tested over the latest features...), which came with Palemoon 31.2.

LaZagne didn't work with my old Palemoon 27.5 install. There was a major, and not compatible, change to password storage between those two versions. Even the new Palemoon didn't like the old file. I had to go through a "migration" procedure described in the Palemoon forum to make it compatible.

But, after I uncommented the "FIXME" line for Palemoon in LaZagne-master/Linux/lazagne/softwares/browsers/firefox_browsers.py, LaZgne finds the saved passwords, and appears to decode them all correctly.

It also appears to be working correctly with Firefox 104, but not with Chrome Version 105.0.5195.102 (Official Build) (64-bit): on a previous run, it spit out a bunch of "Password encrypted and Chrome Secret Storage not found" messages, which looks like they might correspond to the number of saved passwords. But I just ran it again, and there was nothing under the heading for Chrome.

This is not a major concern for me, since (nearly??) all the saved passwords in Chrome were imported from Firefox, so I have a backup. If there are any tests you'd like me to try to get more debug info, or have a possible fix to be tested, just let me know.

Thanks,

Ran

**Comment by AlessandroZ** [comment]
Hello, 

Sorry for my super late answer. Chrome secret storage is stored on your system secret storage and it's decrypted on the another module (libsecret), without this key you cannot retrieve your passwords in plaintext. If you only specify the module chrome, it does not check for the secret key first. So try launching lazagne with all modules and you will be sure if the passwords could be decrypted or not.

**Comment by barabashka2402** [comment]
Hello, please tell me how you convert Python code into an executable file?

**Comment by AlessandroZ** [comment]
It depends of your system and how you have configured chrome to store your passwords. The easiest way would be to do it with the Chrome Gui, otherwise, you have to be sure where the passwords are stored before trying to deleting it.
