### ISSUE TITLE
Rclone addition

### ISSUE THREAD

**Issue by maaaaz** [AlessandroZ/LaZagne#612]
Hello @AlessandroZ,

For your information, a decrypter for rclone passwords that can be found in `rclone.conf` files: https://github.com/maaaaz/rclonedeobscure

Cheers.

**Comment by AlessandroZ** [comment]
Hi @maaaaz, I have added your script as a new module (https://github.com/AlessandroZ/LaZagne/commit/05fdf26da7398e0b6672f0714469daf373b2d03c). Thanks a lot. 

Have a nice day.
