### ISSUE TITLE
Configurable directories for programs

### ISSUE THREAD

**Issue by InterLinked1** [AlessandroZ/LaZagne#616]
This program seems to rely on hardcoded paths to programs which could be made more flexible if that were parameterizable.

For example, for "Thunderbird": https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/mails/thunderbird.py

There are a lot of Thunderbird-forked clients for Windows, that all use the same file format, but they store their configs in different directories, that are not usually named "Thunderbird". It would be useful to be able to provide the directory to search as a command line parameter, since it should be able to pull passwords  from any arbitrary directory that uses the same format for Thunderbird, or some other supported program.

I did try copying the relevant `login.json` file from the profile folder to a folder named "Thunderbird" to test if that would work, but unfortunately not, but I suppose someone with a better understanding might know what the trick is to this.

Using the underlying firepwd tool manually (from https://github.com/lclevy/firepwd) does work as expected.

**Comment by AlessandroZ** [comment]
Hello,

If you can give me some examples, we could do it like we have done with chrome and firefox formats: 
- https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/browsers/firefox_browsers.py#L9
- https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/browsers/chromium_browsers.py#L9

**Comment by AlessandroZ** [comment]
Thank you, let me some time to implement it. 👍🏼

**Comment by AlessandroZ** [comment]
I have added all path you mention, I have tried it before to validate it (however, I didn't add it to Linux).
