### ISSUE TITLE
Extract passwords remotely

### ISSUE THREAD

**Issue by marcelofares** [AlessandroZ/LaZagne#618]
How to decrypt a remote machine via local network? Do I need to run it on the remote machine or can I run it locally to get access to remote passwords?
I tested it on my machine local and extracted the passwords saved locally, but I want it remotely, how can I do that?
What is the parameter or syntax to capture passwords remotely?

**Comment by AlessandroZ** [comment]
Sorry for my late answer, I think you had solved your issue. 
However, I tried to answer anyway. The tool should be launched on the victim host,  so it does not work remotely. However, if you have a remote access, the best way should to upload it and then to execute it.
