### ISSUE TITLE
Hey the problem is when i run lazagne latest version source code i get result and when i convert that latest version source code into an exe using pyinstaller i got no result

### ISSUE THREAD

**Issue by jackie42** [AlessandroZ/LaZagne#619]
The problem is when i run lazagne latest version source code i get result and when i convert that latest version source code into an exe using pyinstaller i got no result                                                                           
C:\Users\redi\Desktop\9j\LaZagne-2.4.5 (1)\LaZagne-2.4.5\Windows\dist>lazagne.py all 
URL: https://accounts.google.com/v3/signin/
Login: hamzat685shades@gmail.com
Password: ehahfh321

[+] Password found !!!
URL: https://www.instagram.com/accounts/login/
Login: hamzat685shades@gmail.com
Password: ehahfh321

[+] 2 passwords have been found.
For more information launch it again with the -v option

elapsed time = 17.940216064453125

C:\Users\redi\Desktop\9j\LaZagne-2.4.5 (1)\LaZagne-2.4.5\Windows>                                                                                                                      
(c) Microsoft Corporation. All rights reserved.

C:\Users\redi\Desktop\9j\LaZagne-2.4.5 (1)\LaZagne-2.4.5\Windows\dist>lazagne.exe all

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

[+] 0 passwords have been found.
For more information launch it again with the -v option

elapsed time = 0.03132796287536621

**Comment by AlessandroZ** [comment]
This is a weird behavior. Without any information, I cannot help you to debug. I've never had this issue. 
I close it but if you managed to find a solution, it could help other users.
