### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by mkk776** [AlessandroZ/LaZagne#621]
my windows username includes some characters which i guess doesn't support...

LaZagne.exe windows

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "subprocess.py", line 1267, in _readerthread
  File "c:\Python37\lib\encodings\cp1254.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 11: character maps to <undefined>

**Comment by CyBerkAyHosT** [comment]
> my windows username includes some characters which i guess doesn't support...
> 
> 
#> 
> 
> 
> LaZagne.exe windows
> 
> 
> 
> Exception in thread Thread-1:
> 
> Traceback (most recent call last):
> 
>   File "threading.py", line 926, in _bootstrap_inner
> 
>   File "threading.py", line 870, in run
> 
>   File "subprocess.py", line 1267, in _readerthread
> 
>   File "c:\Python37\lib\encodings\cp1254.py", line 23, in decode
> 
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 11: character maps to <undefined>
> 
>

**Comment by AlessandroZ** [comment]
Sorry for my late answer. This is weird, I worked a lot trying to correct this issue. I cannot see where the error comes from. It would be more useful putting the stracktrace using the python code.
