### ISSUE TITLE
Password: b'v10\xbf\x80\xff\x94\xbd\xe9 \xff\xa2A\xcd9\x80}\xa5\x8dW\xd50M\x13m\xa0\x0e7(\xb1\x9e'

### ISSUE THREAD

**Issue by dicotom** [AlessandroZ/LaZagne#623]
Hi,

Why I do not get the password in plain text?

**Comment by Zxxxx** [comment]
windows 10 Microsoft Edge
Ver：115.0.1901.200 
not get the password

-------------------------

windows 10 Microsoft Edge 114.0.1823.67  upgrade to 115.0.1901.200
Can obtain password
