### ISSUE TITLE
Doesn't seem to launch ?

### ISSUE THREAD

**Issue by zydar16** [AlessandroZ/LaZagne#624]
Hi, 

I view your software on twitter, i was giving a try but V2.4.5 or V2.4.3 open a prompt but it automatically close in less than a second.
I disable my antivirus (ESET), still the same thing

Do you have any idea ? 
![image](https://github.com/AlessandroZ/LaZagne/assets/2142751/6d329c2a-8ec9-4ce7-b4e5-48cb42eee63f)

**Comment by AlessandroZ** [comment]
Hello,  

You should check old issues or you have some youtube videos explaining how it works.
The exe should be launched from a cmd prompt and not double clicking on it.
