### ISSUE TITLE
Informatica

### ISSUE THREAD

**Issue by maaaaz** [AlessandroZ/LaZagne#629]
Hello @AlessandroZ,

FYI, I stumbled on this article:
https://www.errno.fr/Informatica.html (@gquere)

Cheers!

**Comment by AlessandroZ** [comment]
Thank you !

**Comment by AlessandroZ** [comment]
Hello, 

Here I can read `Passwords are stored in the POU_PASSWORD field of the PO_USERINFO table.` And then it decrypt it using his tool. I won't read an Oracle database to extract a password. So I won't implement it.

Thank you anyway. Have a nice a day.
