### ISSUE TITLE
Im having trouble using lazagne on my raspberry Pi Zero W 

### ISSUE THREAD

**Issue by Ralolaflare** [AlessandroZ/LaZagne#635]
I am trying to recover passwords stored in my old Mac computer. I am using a raspberry pi zero w and im having trouble installing and using lazagne for my device would anyone please be able to help? Im new to this by the way but I am trying my hardest to learn

**Comment by Ralolaflare** [comment]
To be more specific my RPI is running P4wnP1, the requirements say I need to - 
1. Create disk using genimg: /usr/local/P4wnP1/helper/genimg -i -s 50 -o passwords -l passwords
2. Copy the "tools" directory from this repository to the "passwords" disk
but I don't know how to create a disk and im also not sure how to install this any help is appreciated am I missing something ? am I doing something wrong ?

**Comment by AlessandroZ** [comment]
Sorry for my late answer. If you still have some problem on it, you should take a look on this project that I embed into my code. It's more focus on the keychain so do not manage other applications like firefox, but could be easier to use in your case: https://github.com/n0fate/chainbreaker/

Have a nice day.
