### ISSUE TITLE
ValueError: unsupported hash type md4

### ISSUE THREAD

**Issue by popalltheshells** [AlessandroZ/LaZagne#639]
Hi, I'm trying to compile with pyinstaller for Windows version but it isn't working due to this error. Anyone encountered something similar?

I've edited my openssl.cfg to take legacy, and edited hashlib to take md4, but still having the same error. 
A little bit stump right now, any other alternatives ?

Thanks!

**Comment by AlessandroZ** [comment]
I have fixed it by adding a pure md4 python code because hashlib does not support md4 anymore. 

Have a nice day.
