### ISSUE TITLE
[Suggestion] Nirsoft products implementation

### ISSUE THREAD

**Issue by Lionir** [AlessandroZ/LaZagne#64]
Nirsoft has made various tools to recovery various passwords and logs. My personal favourites are "BrowsingHistoryView", "ProduKey", "SkypeLogView". If these could be implemented, I'd love it. Thank you :)

**Comment by AlessandroZ** [comment]
Hi, 
I'm sorry to close this issue without implementing your modules but it is not the goad of the tool. The browser history and skype logs does not follow the goal of the tool which is to retrieve passwords. 

The product key module will be maybe implemented one day, but it's not a priority. Thanks again for your proposal.

**Comment by Lionir** [comment]
@AlessandroZ It's fine, just thought I would suggest it. Thanks for making this. :)
