### ISSUE TITLE
Include self contained portable binary

### ISSUE THREAD

**Issue by ErezBinyamin** [AlessandroZ/LaZagne#640]
It may be useful to include a fully self-contained portable binary release. I recently used `pyinstaller -F --onefile ./laZagne` to generate such a binary and have had good results.

**Comment by AlessandroZ** [comment]
Thank you for your message, I have added some information on the Readme of how to compile it. 
I will see how I will build it using the Github action. I'm thinking on using nuitka instead of pyinstaller.

**Comment by ErezBinyamin** [comment]
Including link to updated [readme](https://github.com/AlessandroZ/LaZagne?tab=readme-ov-file#compile) for those who reference this issue in the future
