### ISSUE TITLE
Cryptographic API Misuse Vulnerability

### ISSUE THREAD

**Issue by lialon** [AlessandroZ/LaZagne#648]
### Description:

In the "LaZagne/Mac/lazagne/softwares/browsers/chrome.py", I have identified a security vulnerability about hardcode salt.  And do not use hardcode/static salt in the PBKDF, which would make output easy to predict.

### Location:

https://github.com/AlessandroZ/LaZagne/blob/master/Mac/lazagne/softwares/browsers/chrome.py#L91

```python
iv = ''.join(('20',) * 16)
key = pbkdf2_hmac('sha1', safe_storage_key, b'saltysalt', 1003)[:16]
```

### Reference

- CWE-330: Use of Insufficiently Random Values

### Recommendations

- Generate salt with cryptographic secure PRNG.

**Comment by AlessandroZ** [comment]
Hi, so you should contact chrome to say it to not store a static salt :)
