### ISSUE TITLE
Still cannot compile for windows 

### ISSUE THREAD

**Issue by Aggelos11** [AlessandroZ/LaZagne#649]
Hello ! Can you please explain me in detail how to compile the latest version for windows ? The tutorial you have does not work ( with the pyinstaller —onefile -w lazagne.spec )

**Comment by AlessandroZ** [comment]
- https://github.com/AlessandroZ/LaZagne?tab=readme-ov-file#compile
```
pyinstaller --additional-hooks-dir=. -F --onefile laZagne.py
```
