### ISSUE TITLE
[Suggestion] Command to ask for admin access

### ISSUE THREAD

**Issue by Lionir** [AlessandroZ/LaZagne#65]
I use a batch file to launch "Lazagne.exe all -oN" and various other software and I'd like the option to make a command such as "Lazagne.exe all -oN Admin" or something similar so it asks for admin access making it easier to get all the credentials.

**Comment by AgentBallermann** [comment]
I think this could help you. http://lmgtfy.com/?q=Batch+UAC+Bypass
