### ISSUE TITLE
Support using external Windows registry files

### ISSUE THREAD

**Issue by maaaaz** [AlessandroZ/LaZagne#653]
Hello there,

Could it be possible to have an option to provide external registry files (for instances SOFTWARE, SYSTEM, SAM) in order to recover stuff from another computer, onto copied registry files ?

Cheers!

**Comment by AlessandroZ** [comment]
Hello, 

You have other tools to do it offline, for windows check -> https://github.com/moyix/creddump. 

Have a nice day.

**Comment by maaaaz** [comment]
Thanks but there is a misunderstanding because of my wording.

I am not looking for a program to extract secrets from registry keys.

I would like, in a LaZagne option, for LaZagne modules where Windows registries are needed, to be able to provide external registry files, instead of LaZagne using the registry files of the computer executing LaZagne.
