### ISSUE TITLE
v2.4.6 .exe file

### ISSUE THREAD

**Issue by arad1367** [AlessandroZ/LaZagne#654]
Just a quick note, after download v.2.4.6 exe file and start working you can check the version (LaZagne -version) and that show version is 2.4.4. The .py version work perfect but please review .exe file. Thanks.

**Comment by AlessandroZ** [comment]
Hello, 

I have pushed the compile version using github action. The number version is extract from the tag but I forgot to change it on the code. I will do it. Thanks for the feedback.

**Comment by arad1367** [comment]
You're welcome, and thank you for LaZagne.
