### ISSUE TITLE
print_output is not defined

### ISSUE THREAD

**Issue by CarlNeuhaus** [AlessandroZ/LaZagne#67]
Running the latest Windows release v1.5 throws a python NameError regarding the print_output function referenced in wifipass.py (line 67).
This line has been commented out in the current repos code.
`Traceback (most recent call last):`
 `File "laZagne.py", line 537, in <module>`
  `File "laZagne.py", line 148, in runAllModules`
  `File "laZagne.py", line 107, in launch_module`
  `File "softwares\wifi\wifipass.py", line 67, in run`
`NameError: global name 'print_output' is not defined`

**Comment by AlessandroZ** [comment]
The version 1.6 has to correct the problem. Do not hesitate to re-open this issue if you notice any problems using the last version. Thank you
