### ISSUE TITLE
new released version failed retrieving ie password. 

### ISSUE THREAD

**Issue by simonpunk** [AlessandroZ/LaZagne#68]
@AlessandroZ 
Hi, glad to see your new release here, but seems something goes wrong when I test on my win7 machine, my screen cap as below:

![image](https://cloud.githubusercontent.com/assets/16465163/18303904/f72b0d8e-7511-11e6-8ea3-e26427346e90.png)

And I tried to look into your source code, may be there is a "Exception,e:" missing after "Except:" in line 280?? I just think, but not sure. And I have not yet tested with win10. 

Thank you very much.

**Comment by AlessandroZ** [comment]
Hi, thanks for your feedback. I had some problems with my win7 virtual machine so I will install it again this weekend and get a look on it.

**Comment by simonpunk** [comment]
Okay, just let you know it works perfect on my win10 without any problems so far.

**Comment by AlessandroZ** [comment]
I didn't have time to build a new virtual machine on win7. However, I pretty sure of the problem of the bug, so I fixed it. Could you please try again using the new release (1.7), and close the issue if it will work. Thanks again.

**Comment by simonpunk** [comment]
it works now, thank you very much!!
