### ISSUE TITLE
Why is it detected as containing HEUR/QVM20.1.0000.Malware.Gen 

### ISSUE THREAD

**Issue by biovolt** [AlessandroZ/LaZagne#69]
Hi
Where is the code that trigger this? 

HEUR/QVM20.1.0000.Malware.Gen 
Trojan.Generic.aclcm 

Why is the source clean ? 

Sorry if I am asking a stupid question. I just don't want to infect pc's

**Comment by AlessandroZ** [comment]
Hi, 
This tool has been used for illegal purpose many times, it has been used by trojan. So I'm not surprise an antivirus triggers it as a malware too. The tool is an open source project, so if you are not confident about it, I let you analyse the code. 
Please do not submit it to virus total, this is a reason that it could be triggered as malware.
