### ISSUE TITLE
Unicode issue

### ISSUE THREAD

**Issue by Etuldan** [AlessandroZ/LaZagne#7]
On a Win7 OS with French environment (keyboard & locales) : 

D:\Users\arg\Downloads>laZagne.exe all

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

------------------- Skype passwords -----------------

Password not found !!!
Username: xxxxx
Hash_md5: xxxxx
shema to bruteforce: xxxxx

------------------- Firefox passwords -----------------

Password found !!!
Website: chrome://keefox
Username: xxxxxxx
Password: xxxxxxx

D:\Users\arg\AppData\Local\Temp\_MEI76442\softwares\browsers\ie.py:206: UnicodeW
arning: Unicode equal comparison failed to convert both arguments to Unicode - i
nterpreting them as being unequal
Traceback (most recent call last):
  File "<string>", line 181, in <module>
  File "<string>", line 109, in runAllModules
  File "<string>", line 74, in launch_module
  File "C:\Users\John\LaZagne\Windows\src\LaZagne\build\laZagne\out00-PYZ.pyz\so
ftwares.browsers.ie", line 308, in run
  File "C:\Users\John\LaZagne\Windows\src\LaZagne\build\laZagne\out00-PYZ.pyz\so
ftwares.browsers.ie", line 58, in get_hash_table
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 41: ordinal
 not in range(128)

**Comment by AlessandroZ** [comment]
Hi, 
Thank you for the stacktrace. 
I have made a new commit. Could you download the new executable and try it again. I let you close the issue if it works well. Thank you.

**Comment by reversingfr** [comment]
thank you.
it work now perfect on windows 7 french version.

bye the way, I've just write an article on my french blog. (http://reversing.fr/the-lazagne-project/)

**Comment by Etuldan** [comment]
No more crash with the new binary, but still an issue : 


D:\Users\arg\Downloads>laZagne.exe all

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

------------------- Skype passwords -----------------

Password not found !!!
Username: xxxx
Hash_md5: xxxx
shema to bruteforce: xxxx

------------------- Firefox passwords -----------------

Password found !!!
Website: xxxx
Username: xxxx
Password: xxxx

D:\Users\arg\AppData\Local\Temp\_MEI28282\softwares\browsers\ie.py:209: UnicodeW
arning: Unicode equal comparison failed to convert both arguments to Unicode - i
nterpreting them as being unequal
------------------- Windows Secrets passwords -----------------

[*] Local SAM hashes (uid:rid:lmhash:nthash

Administrateur:xxxx
Invité:xxxx


------------------- Wifi passwords -----------------

Password found !!!
password: xxxx
authentication: WPA2PSK
protected: true
ssid: xxxx


[+] 2 passwords have been found.
For more information launch it again with the -v option

elapsed time = 6.625

**Comment by AlessandroZ** [comment]
I did another correction. 
I couldn't be able to reproduce the error and it was already catch by a try/except. So I hope my correction will be enough. I'm waiting for your response before to close it. Thanks.
