### ISSUE TITLE
Autoexecute the .bat file from USB

### ISSUE THREAD

**Issue by Softryder** [AlessandroZ/LaZagne#71]
Hi, i've triying to make the .bat file executes automatically on windows when i insert the USB drive, is that possible? the .inf file works but only in CD/DVDS

It will be very cool if someone manage to figure that out.  Thanks anyway! :100:

**Comment by AlessandroZ** [comment]
Hi, you could use an usb rubber ducky to do that but I cannot help you to find a better solution.

**Comment by Softryder** [comment]
Yeah, that's probably the best solution in this case, excuse me and off course the laZagne file only works with chrome saved passwords right? the ones that appear at passwords.google.com

Thanks for answering
