### ISSUE TITLE
Error when grabbing browsers passwords

### ISSUE THREAD

**Issue by ahmedbarwary** [AlessandroZ/LaZagne#76]
Hi. When I tried to retrieve browsers passwords . I got the following error:
![capture](https://cloud.githubusercontent.com/assets/9547879/20257083/706fe5fe-aa58-11e6-9ac9-84fdbb39f5a4.PNG)

I am using LaZagne on windows 10.

**Comment by AlessandroZ** [comment]
I have fixed this issue, however your file seems corrupted. You should open your profile.ini file and see what is inside. 
I will do a binary executable later. 
Thanks
