### ISSUE TITLE
How to make my own script, question:

### ISSUE THREAD

**Issue by Omardavinci** [AlessandroZ/LaZagne#79]
it is possible to make my own script using your program or your source. I will try to do one to save in a file, with all my browsers. My question is:  Where is the line to get the results of my browser's. i will try to save in my file then. Sorry a lot for all!

**Comment by n1nj4sec** [comment]
https://github.com/AlessandroZ/LaZagne/blob/master/Windows/laZagne.py#L225

**Comment by Omardavinci** [comment]
sorry one question about these steps:

Create a class using the name of the software containing 2 importants functions:

init: used to define all arguments used to launch the class.
run: will be the main function

when he say the class init, he refer to this file:
https://i.imgsafe.org/f26acef064.png

I need to include here the argument in __init__  browsers argument?
And when i say this: run: will be the main function
He refers that i need put run like main function but where?

Sorry i am little silly sorry!

**Comment by AlessandroZ** [comment]
@n1nj4sec was right, if you just want to save your browsers in a file is already implemented: 
`python lazagne.py browsers  -oN  `

If you want to create another module to manage other softwares (which I don't think it's what you trying to do), you have to follow these steps:

- Create a file using the same structure as this one (this function contains an __init__ and a __run__ method: https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/browsers/chrome.py#L11
https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/browsers/chrome.py#L16

Note: the function run should returns a dictionary of password: https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/browsers/chrome.py#L90

- Add it to the get_modules list on this file: https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/config/manageModules.py

And that's it. 

Good luck.

**Comment by Omardavinci** [comment]
sorry for opening again but how i can run command's since laZagne.py this is my question sorry i explained bad and sorry again!
