### ISSUE TITLE
Thunderbird

### ISSUE THREAD

**Issue by reversingfr** [AlessandroZ/LaZagne#8]
hello again
here some strange bugs :
On a windows 7 pro french 64bits version, with thunderbird installed, I've got the message :
 
------------------- Thunderbird passwords -----------------
[INFO] Thunderbird not installed.
--------------------------------------------------------------------

another thing : 
When I run laZagne.exe all -w
It seems that informations found are not stored on the "credentials.txt."
 (exemple : windows secret password)

**Comment by AlessandroZ** [comment]
Bonjour, 
Je me permets de répondre en français. Merci beaucoup pour ton article, ça me fait très plaisir. J'ai fait quelques corrections pour thunderbird. Normalement, il devrait bien voir que celui-ci est installé. 

Pour ce qui est de l'écriture sur le fichier "credentials.txt", il me faut plus d'informations car chez moi tout marche bien. Est-ce que le problème est visible autre part que sur le module "windows" (attention, une partie de ce module a besoin des droits admin pour qu'il marche, cela concerne la partie "secrets"). Est-ce qu'il y a bien des mots de passe dedans, etc. 

Merci beaucoup pour ton article et pour ton retour. 

Alessandro

**Comment by reversingfr** [comment]
aucun pb pour l'article, c'est tout a fait normal. Ton project est tres interessant

j'ai refait quelque test : 
- avec la commande lazagne.exe mails
il me liste bien l'ensemble de mes comptes de messagerie thunderbird

- avec la commande lazagne.exe mails -w
il m'inscrit bien dans le fichier credentials.txt l'ensemble de mes comptes de messagerie thunderbird

- avec la commande lazagne.exe all
il ne me liste pas les comptes thunderbird :-/

- avec la commande lazagne.exe all -w
il ne m'inscrit pas tout ce qu'il a listé precedemment (par exemple windows secret passwords) alors qu'il l'a bien decouvert


autre remarque. Il me detecte mon pidgin, me trouve bien un compte. mais le password trouver n'est pas le bon

les commandes sont systematiquement lancé avec un compte faisant parti du groupe administrateurs

thomas.

**Comment by AlessandroZ** [comment]
Bonjour, 

* Pour ce qui est de thunderbird, je pense avoir compris le problème. Peux-tu réessayer pour me dire si maintenant, il trouve bien ton compte thunderbird stp. 

* Pour ce qui est de Pidgin, c'est relativement étrange. J'ai retéléchargé la dernière version de Pidgin sous Win7 et je trouve bien mon mot de passe. Pidgin fait partie des logicielles où par défaut, il est stocké en clair dans un fichier de configuration. 
Peux-tu vérifier si tu as bien ce fichier et me dire s'il y a bien ton mot de passe en clair: 
```
C:\Users\<USER>\AppData\Roaming\.purple\accounts.xml
```
Quand tu dis que ce n'est pas le bon mot de passe, c'est un hash ? Un mot de passe d'un autre compte ? As-tu plusieurs comptes pidgin configuré ? As-tu installé un plugin pidgin pour gérer le mot de passe (sous linux, il est possible de lui dire d'utiliser le gnome keyring pour stocker son mdp) ? 

* Et pour finir ce qui est de l'écriture qui ne se fait pas sur le fichier, peux-tu me dire exactement quelle partie n'est pas écrite sur le fichier car je n'arrive pas à reproduire le problème (mes mots de passe sont bien écrits). C'est-à-dire, est ce que ce n'est que la partie "Windows secrets passwords" qui n'est pas écrite ou tout le module ? (soit generic Network passwords et  .Net Passport aussi). 
Si ce n'est que le module "secrets", peux-tu me dire ce qui s'affiche mais qui n'est pas écrit sur le fichier (Local Sam hashes, LSA Secrets, etc).

Merci pour toutes ces informations.

**Comment by reversingfr** [comment]
-thunderbird : 
tout semble ok pour moi

-pidgin (sous windows 7 , installation standard sans plugin): 
dans le fichier accounts.xml, j'ai un mot de passe indiqué (qui n'est pas le mien, donc j'imagine crypté ou un hash) de 16 caracteres de lettres minuscules, du genre :  Password: ationgixgszacsi
je ne dispose d'un compte Gmail uniquement (<protocol>prpl-jabber</protocol>)

-ecriture : 
semble t il uniquement : Windows Secrets passwords n'est pas repris dans le credentials.txt alors meme qu'il a trouvé un mot de passe

**Comment by AlessandroZ** [comment]
Bonjour, 

Merci pour le retour de Thunderbird. 
Pour ce qui est de pidgin, j'ai vu la documentation de Pidgin et une fonctionnalité permettant d'obfusquer le mot de passe existe (https://developer.pidgin.im/wiki/PlainTextPasswords). C'est donc une fonctionnalité que je n'ai pas encore étudié, ce n'est pas réellement une erreur. Je regarderai quand j'aurai le temps. 

Sinon pour ce qui est de l'écriture dans le fichier texte, je vais faire plus de tests, mais c'est vrai que je n'arrive pas à reproduire l'erreur. 
Je ferme le problème car il concerne Thunderbird. N'hésite pas à en ouvrir un autre en ce qui concerne l'écriture du mot de passe. Je regarderai bientôt. 

Merci et bonne journée.
