### ISSUE TITLE
avoid parsing arguments

### ISSUE THREAD

**Issue by Regardmiki** [AlessandroZ/LaZagne#81]
Hi all! I checked this project and it's great! Checking the closed issues, i saw one post very similar to my problem. does it exist some way to avoid parsing of arguments. In other ways, i could include the argument in the python file. I was checking the solution but it didnt work for me.

Are these lines:

`PWrite = argparse.ArgumentParser(add_help=False,formatter_class=lambda prog: argparse.HelpFormatter(prog, max_help_position=constant.MAX_HELP_POSITION))`

`PPoptional = argparse.ArgumentParser(add_help=False,formatter_class=lambda prog: argparse.HelpFormatter(prog, max_help_position=constant.MAX_HELP_POSITION))`

like:

> python laZagne.py all (--> i want to include this argument in my file python)

I can't put my own parser?

**Comment by AlessandroZ** [comment]
Ahaha are you @Omardavinci (https://github.com/Regardmiki/Bitcoin-mining) ?? 
You should learn python and read the main code, I won't do it for you !

**Comment by Regardmiki** [comment]
i am not omardavinci i dont know maybe because i imported project

**Comment by Regardmiki** [comment]
i can include your project too this not mean that i am omardavinci

**Comment by Omardavinci** [comment]
haha miki you are me check this:
argv = vars(arguments)['auditType']

And put your own arguments

**Comment by Omardavinci** [comment]
do this miki and you will understand:
argv = vars(arguments)['auditType']
print argv
current_filepath = sys.argv[0]
print current_filepath

**Comment by Regardmiki** [comment]
yeah i know a lot of time i didnt practice this language thanks!
