### ISSUE TITLE
Compiled .exe some error's

### ISSUE THREAD

**Issue by Axe-Usa** [AlessandroZ/LaZagne#84]
I compiled the .py to exe file but show these error's:
Traceback (most recent call last):
  File "laZagne.pyw", line 21, in <module>
  File "lazagne\softwares\browsers\mozilla.pyc", line 15, in <module>
ImportError: No module named pyasn1.codec.der

The following modules appear to be missing
['Carbon', 'Carbon.Files', 'Crypto.PublicKey._fastmath', 'ElementC14N', 'POW', '_psutil_linux', '_sysconfigdata', 'colorama', 'enum', 'ordereddict', 'ordereddict.ordereddict', 'psutil._psutil_bsd', 'psutil._psutil_osx', 'psutil._psutil_posix', 'psutil._psutil_sunos', 'pyasn1.codec.der', 'pyasn1.type', 'winreg']

The libraries are installed however never are included! Why???!!

**Comment by AlessandroZ** [comment]
Check that issue https://github.com/AlessandroZ/LaZagne/issues/77, and this one https://github.com/AlessandroZ/LaZagne/issues/78 it could help you
