### ISSUE TITLE
program crash why?

### ISSUE THREAD

**Issue by gaviromantic** [AlessandroZ/LaZagne#85]
i was using and sometimes crash why¿?

**Comment by AlessandroZ** [comment]
Without no more information, I cannot help you. I need a stacktrace of the exact message to correct it

**Comment by gaviromantic** [comment]
solved! worked! avast detected and was deleting the file.

**Comment by gaviromantic** [comment]
my avg detect program console like virus again i'm using avast the only way is desactivating it

**Comment by gaviromantic** [comment]
it's solved only close avast and work
