### ISSUE TITLE
Some libraries were not included

### ISSUE THREAD

**Issue by Axe-Usa** [AlessandroZ/LaZagne#86]
Hi Alessandro! I included your libraries but when i compile still show me missing libraries error:
['Carbon', 'Carbon.Files', 'Crypto.PublicKey._fastmath', 'ElementC14N', 'POW', ' _psutil_linux', 'enum', 'ordereddict', 'ordereddict.ordereddict', 'psutil._psuti l_bsd', 'psutil._psutil_osx', 'psutil._psutil_posix', 'psutil._psutil_sunos']

Maybe i must to install more libraries?

**Comment by AlessandroZ** [comment]
Check that issue #77, and this one #78 it could help you.
You need to install all requirements listed on the README
