### ISSUE TITLE
Not an issue, but question, can be ran with wifi argument, without admin rights?

### ISSUE THREAD

**Issue by Marekkon5** [AlessandroZ/LaZagne#88]
Can be this started with wifi argument, without admin rights?

**Comment by AlessandroZ** [comment]
No, it's not possible. 

Wifi passwords can only be decrypted having system rights. So when you launch lazagne using admin rights, it elevates itself as system and decrypt wifi credentials. However, wihtout enough privileges, this elevation will fail and no wifi passwords could be retrieved. 

Some password can only be retrieved on a specific environment and that the case for wifi password.
