### ISSUE TITLE
one question about passwords

### ISSUE THREAD

**Issue by Axe-Usa** [AlessandroZ/LaZagne#89]
Hi, i have one question because if someone use this to get my password, he can't access anyways because he will connect since other side and will be blocked with safety lock (ip detection/ block when you use other ip). In other words, it's useful to get one password if my web page will block him when he used other ip to connect to my account? It's only to be sure and say that many webpages today block you so the password is important component but not the most important element  thing. And if you know that someone can bypass this restriction or any person can be  in peace if someone has his password because he doesnt connect since the same ubication.

**Comment by AlessandroZ** [comment]
Ahaha don't feel safe with the ip detection mechanism. I could easily connect to your web applications from my browser and using your ip address (doing port forwarding or using a proxy socks).
