### ISSUE TITLE
Json format is showing actual \n in the string.

### ISSUE THREAD

**Issue by FexileTV** [AlessandroZ/LaZagne#90]
Example:

"{\n    \"Passwords\": [\n        [\n            {\n                \"Category\": \"Skype\"\n            },\n

**Comment by AlessandroZ** [comment]
Thanks for your issue, I have already corrected but I didn't compile the binary yet. I wait to do other modifications: https://github.com/AlessandroZ/LaZagne/blob/master/CHANGELOG#L5
