### ISSUE TITLE
Error installing Python dll & a Question

### ISSUE THREAD

**Issue by LaGallinaTuruleta** [AlessandroZ/LaZagne#91]
Hello
I show you my error.
![lazagneerror](https://cloud.githubusercontent.com/assets/17246362/20862313/751c09d0-b9a7-11e6-852f-8239e71afeef.png)
I have search this error on google and someone recommend to install "Adobe Shockwave Player". I didn't reboot computer, maybe that but not 4 sure.
I've installed all the stuff on Requirements, but still not working.
I've tried on another computer and it works.
And now how to take security, per example:
-It finds my filezilla passwords .
-It finds too : MicrosoftOffice16_Data:SSPI . on Network Path It founds my hotmail account linked to outlook, I suppose.
Any way to block this like Firefox using master key?
Thanks for reading ;P.

**Comment by AlessandroZ** [comment]
Hi, your problem should be more some dependency missing like microsoft redistribuable. It could happen in some system. 

To anwser to your other question, I recommend you using a tools to store all your passwords (such as keepass, revelation, lastpass, envpass,...). I think, right now, this is the better way to manage your passwords.
