### ISSUE TITLE
Error parsing the json results

### ISSUE THREAD

**Issue by coldalfred** [AlessandroZ/LaZagne#93]
Hi, i have some trouble using LaZagne everything work as expected but only when has to write the results to "results\credentials.txt" get an error.

- Version
LaZagne Release 1.8

- OS
win 7 sp1 with attached a domain

- Dir was executed LaZagne
C:\ProgramData\ms.exe

- AV
Kaspersky Endpoint Security

- Command Line
shell ms.exe all -oN -v
shell ms.exe mails -oN -v

- Platform Pentest
Cobalt Strike 3.6 

- ERROR
[ERROR] Error parsing the json results: 'ascii' codec can't decode byte 0xea in position 2: ordinal not in range(128)

- Keyboard and Language of OS Win7sp1 is on SPANISH

hope you can fix it ASAP thanks
http://stackoverflow.com/questions/22267629/unicodedecodeerror-ascii-codec-cant-decode-byte-0xea-in-position-8-ordinal

**Comment by AlessandroZ** [comment]
It should be fixed on the new version (2.0). Open again this issue, if you have the same error. Thanks.
