### ISSUE TITLE
LaZagne cant read Chrome Passwords anymore.

### ISSUE THREAD

**Issue by TheGamingMaik** [AlessandroZ/LaZagne#96]
On version 1.1 I get a full list of passwords,
but on 2.0 I get this:
------------------- Chrome passwords -----------------

[ERROR] An error occured copying the database file

[ERROR] An error occured opening the database file

[!] No passwords found

I dont know if its a general error or just for me.
![screenshot_2](https://cloud.githubusercontent.com/assets/16877165/21743520/15240bf4-d504-11e6-86c1-1cdca3f6fbe9.png)

**Comment by TheGamingMaik** [comment]
With administrator prevelieges
![screenshot_3](https://cloud.githubusercontent.com/assets/16877165/21743532/595df5a0-d504-11e6-9330-2db3c25b4832.png)

**Comment by AlessandroZ** [comment]
Hi, could you please retry with the last binary (version 2.0): https://github.com/AlessandroZ/LaZagne/releases/tag/2.0
Put it on the desktop or another directory owned by the user (not in C:\) and run it without admin rights (it should work even with admin rights and even if it's on C:\, it is only for tests).
