### ISSUE TITLE
Adding SMTP Password for Outlook module

### ISSUE THREAD

**Issue by jboss38** [AlessandroZ/LaZagne#98]
Hey !

I just try the Outlook module but didn't find my smtp password.
What about adding the SMTP password to your Outlook module ?

------------------- Outlook passwords -----------------

Password found !!!
SMTP User: smtp@Microsoft.com
SMTP Port: 587
Account Name: Jean Louis
Display Name: Jean Louis
IMAP Sentitems flag: 2
Email: Jean Louis@Microsoft.com
Organization: Microsoft
Reply-Forward Signature: Sign
SMTP Secure Connection: 0
SMTP Server: smtp.Microsoft.fr
IMAP Store EID:   Ûä©ßé╗¯öàß¿ÉÙ«Ô¿½ýëû
Password: BillGates
IMAP Deleteditems flag: 2
SMTP Use Auth: 1
SMTP Auth Method: 1
IMAP Server: imap.Microsoft.fr
IMAP User: billgates@Microsoft.fr
Delivery Store EntryID:   Ûä©ßé╗¯öàß¿ÉÙ«Ô¿
Delivery Folder EntryID:   ÚÉàßöîÚ®£õ¡┤
EnablePurgeOnSwitch: 1
Preferences UID: ¯Ø½ÙÖ¼Ýâ
Service UID: ¼8q═┼M┐Ì─Ùê
IMAP Folder Path: Inbox
New Signature: Sign

Outlook store the passwords in the same Registry key of the account settings. The accounts are stored in the Registry under HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Windows Messaging Subsystem\Profiles\[Profile Name]\9375CFF0413111d3B88A00104B2A6676\[Account Index] If you use Outlook to connect an account on Exchange server, the password is stored in the Credentials file, together with login passwords of LAN computers.

**Comment by jboss38** [comment]
Okey thanks for info.

But what about SMTP credential stored in outlook when using regular outlook ? (not exchange)

I also give you a clue, it's fake credential (for testing purpose), really, who put BillGates for password lmao

**Comment by AlessandroZ** [comment]
I don't understand which password you are talking about. 
In your previous output, it's a non exchange account that it's used and the password has been correctly retrieved. So I don't understand the problem.

**Comment by jboss38** [comment]
In outlook you have a password for User, this is retrieved here:
Email: Jean Louis@Microsoft.com
Password: BillG***

This login / password is for receive mail.

But you can also retrieve login and password of the account who send the mail via SMTP server.
Here a screen: http://nsa38.casimages.com/img/2017/01/10/170110052052788872.png

If you want test, with nirsoft mailpv you can retrieve this SMTP password: http://www.nirsoft.net/utils/mailpv.html

**Comment by AlessandroZ** [comment]
Ok I see, you're right. 
I will need to do some tests to add these functionalities. I don't know if I could do it soon, however, if you think you're able to do it, do not hesitate to do a pull request adding these changes. Otherwise, I will do it. 
Thanks !

**Comment by jboss38** [comment]
i'm kind new at python, but when i got the time i will love to look at it.

**Comment by jboss38** [comment]
I found the problem

On this def

`def retrieve_info(self, hkey, name_key):
		values = {}
		num = win32api.RegQueryInfoKey(hkey)[1]
		for x in range(0, num):
			k = win32api.RegEnumValue(hkey, x)
			if 'password' in k[0].lower():
				try:
					password = win32crypt.CryptUnprotectData(k[1][1:], None, None, None, 0)[1]
					values['Password'] = password.decode('utf16')
				except Exception,e:
					print_debug('DEBUG', '{0}'.format(e))
					values['Password'] = 'N/A'
			else:
				try:
					values[k[0]] = str(k[1]).decode('utf16')
				except:
					values[k[0]] = str(k[1])
		return values`

When you find a password you add it on values named 'Password' but here is multiple password.
So he find correclty the SMTP Password, he can decrypt it.
But after you erase by the IMAP Password because there is string PASSWORD in the two key:
IMAP Password
SMTP Password

Have a nice day !

**Comment by AlessandroZ** [comment]
Thanks for the fix !
