### ISSUE TITLE
Keepass passwords Error

### ISSUE THREAD

**Issue by hostbob** [AlessandroZ/LaZagne#99]
I keep getting this error whenever lazagne.exe is launched via CMD

Password not found !!!
Get-Process: Cannot find a process with the name "KeePass". Verify the process

kindly advice how to fix this

**Comment by jboss38** [comment]
Its because you dont have Keepass running, but Its OK, you can keep running LaZagne.

**Comment by hostbob** [comment]
yeah i know, but how do i get the keepass i can't find it in lazagne folder and do i need to execute it or run it like lazagne from CMD?

advice

**Comment by jboss38** [comment]
Keepass is a software where you keep your password.
LaZagne scan multiples applications to get password (Chrome, Firefox, Outlook...) and also Keepass. 
Look at Google If you want know what is Keepass.

**Comment by hostbob** [comment]
sorry i read about keepass here

**Comment by AlessandroZ** [comment]
Thanks for your feedback. 
I cannot reproduce the awesome work that mimikatz does to retrieve the windows password in cleartext. So at first, I wanted to embed mimikatz (the powershell version, which could be run into memory) into lazagne but then I changed my mind. So maybe, one day, it will be on it (maybe if lots of people wants it), or maybe not. I don't know yet lol. 
Have a good day.

**Comment by hostbob** [comment]
I read about mimikatz and it was awesome tool which completes part of what I'm looking for. Com on bro, u might not know when this will really be handy try impliment mimikatz into lazagne it will be rally lovely. By the the way why is lazagne being detected by AVs?
